% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Bayesian multilevel models in R: A conceptual and practical introduction for linguists},
  pdfauthor={Santiago Bareda},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=2cm]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Bayesian multilevel models in R: A conceptual and practical introduction for linguists}
\author{Santiago Bareda}
\date{2021-07-14}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{introduction}{%
\chapter*{Introduction}\label{introduction}}
\addcontentsline{toc}{chapter}{Introduction}

This book is currently under development and it may contain small errors, inconsistencies, etc. It was used for a 10-week statistics class, but is being expanded and reorganized somewhat.

Repeated measures data is extremely common in linguistics, and the norm in many linguistic subfields (phonetics, variationist sociolinguistics, psycholinguistics, etc.). Bayesian multilevel models are perfectly suited for the analysis of repeated-measures data, and offer linguists flexibility and many exciting opportunities. Because of this, there is tremendous interest in using Bayesian multilevel models in linguistics despite the lack of available resources. This book is an introduction to the analysis of repeated-measures data using Bayesian multilevel regression models, specifically aimed at linguists with no background in statistics.

This book is intended for an introductory statistics class for senior undergraduate or graduate students, and for faculty members and other researchers to use as a self-study guide. This book is aimed at 1) students who are looking for a conceptual framework to help understand multilevel Bayesian models, but not necessarily looking for `too-much' mathematical detail, and 2) researchers who are already experienced with frequentist modelling and are looking to `translate' their skillset over to a Bayesian framework.

To learn multilevel models, a student is usually first expected to learn `traditional' statistical approaches and designs, such as t-tests ANOVAS and ordinary least-squares regression. After this foundation is laid, the student can then move to the sorts of models they can actually use for their work, mainly multilevel models that can handle repeated-measures data. This approach has several drawbacks: it takes a long time (which graduate students don't have), spends substantial energy on statistical approaches that most linguists will rarely if ever use in their work (e.g., OLS regression), and front-loads difficult and abstract concepts (e.g., degrees of freedom, p-values) before students can start working with data they really understand. As a result, students may become discouraged, may become convinced that they're `not good at math', and may not realize how much they already intuitively understand about statistics.

This book presents an introduction to modelling repeated-measures data using Bayesian multilevel regression models, and building bespoke Bayesian models that are equivalent to, and better than, their `off the shelf' frequentist equivalents using the `brms' package in R. This book will provide a conceptual introduction by adopting an accessible narrative style that introduces mathematical and modelling concepts in plain English. A focus will be placed on understanding concepts and the visual/geometric consequences of different regression model structures and changes in coefficients, leaving much of the statistical foundation and mathematical rigor to other books. Chapters are organized in terms of regression model components, and how these relate to experimental designs, statistical concepts, and the geometry of figures based on the data and model coefficients. We will then cover how to use these components to `build' models that suit your needs. In addition, each chapter feature the fully worked analysis of repeated-measures linguistic data resulting from either perceptual experiments or speech production experiments involving human subjects.

If you have any comments or suggestions please let me know, and if you find any errors definitely let me know!

\hypertarget{inspecting-a-single-group-of-observations}{%
\chapter{Inspecting a single group of observations}\label{inspecting-a-single-group-of-observations}}

Placeholder

\hypertarget{data-and-research-questions}{%
\section{Data and research questions}\label{data-and-research-questions}}

\hypertarget{inspecting-the-central-location-and-spread-of-values}{%
\subsection{Inspecting the central location and spread of values}\label{inspecting-the-central-location-and-spread-of-values}}

\hypertarget{probability-distributions}{%
\section{Probability Distributions}\label{probability-distributions}}

\hypertarget{the-normal-distribution}{%
\subsection{The normal distribution}\label{the-normal-distribution}}

\hypertarget{referring-to-the-normal-distribution-to-make-inferences}{%
\subsection{Referring to the normal distribution to make inferences}\label{referring-to-the-normal-distribution-to-make-inferences}}

\hypertarget{probabilities-of-events-and-likelihoods-of-parameters}{%
\section{Probabilities of events and likelihoods of parameters}\label{probabilities-of-events-and-likelihoods-of-parameters}}

\hypertarget{making-inferences-using-likelihoods}{%
\subsection{Making inferences using likelihoods}\label{making-inferences-using-likelihoods}}

\hypertarget{bayesian-models}{%
\section{Bayesian models}\label{bayesian-models}}

\hypertarget{what-are-regression-models}{%
\subsection{What are regression models?}\label{what-are-regression-models}}

\hypertarget{whats-bayesian-about-these-models}{%
\subsection{What's `Bayesian' about these models?}\label{whats-bayesian-about-these-models}}

\hypertarget{posterior-distributions}{%
\section{Posterior distributions}\label{posterior-distributions}}

\hypertarget{sampling-from-the-posterior}{%
\subsection{Sampling from the posterior}\label{sampling-from-the-posterior}}

\hypertarget{exercises}{%
\section{Exercises}\label{exercises}}

\hypertarget{plot-code}{%
\section{Plot Code}\label{plot-code}}

\begin{verbatim}
## i SHA-1 hash of file is 554e0dd981827d5b99b6008d17225b76ac04da33
\end{verbatim}

\begin{verbatim}
## i SHA-1 hash of file is 37c0daa10d5d5a0ff7f11d3e1d9ef23c829a58bc
\end{verbatim}

\hypertarget{inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model}{%
\chapter{Inspecting a `single group' of observations using a Bayesian multilevel model}\label{inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model}}

The previous chapter was mostly introductory, it introduced some basic terminology and concepts that are required to begin talking about models. In this chapter we are going to return to questions like 'what is the average value of \(x\), however, in this chapter we are going to learn to answer these questions using Bayesian multilevel regression models in R using the \texttt{brms} package.

The models discussed in this chapter can be used for data that comes from a single group of subjects. By a `single' group I just mean that you are not trying to compare things here, you are just trying to understand the average values of some variable for a single group of observations. The data:

\begin{itemize}
\tightlist
\item
  comes from from one speaker/subject or many speakers/subjects.
\item
  each speaker/subject can contribute multiple data points, and the number does not need to be balanced across subjects.
\end{itemize}

The `traditional' design equivalent to these models is a one-sample t-test, although the Bayesian approach has many advantages (as discussed at the end of the chapter).

\hypertarget{data-and-research-questions-1}{%
\section{Data and research questions}\label{data-and-research-questions-1}}

We're going to keep analyzing the female f0 data from the Hillenbrand et al.~(1995) dataset, discussed in chapter 1. These are 576 observations, 12 production collected from each of 48 women in the sample. So, our data comes from multiple speakers and we has multiple observations from each speaker, and the women are in the single group ``adult women form Michigan''. Of course, we could divide these women into any number of smaller groups based on hair color, handedness, and so on. These women are considered to be in a single group because our model, our \emph{conceptualization} of these speakers, places them in a single group.

We're going to try to address the same questions we talked about last week:

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\item
  What is the average f0 of the whole \emph{population} likely to be?
\item
  Can we set bounds on likely mean f0 values based on the data we collected?
\end{enumerate}

However, this time we are going to do this with a Bayesian multilevel model. We're going to see how the model provides us with the same information we got in the last chapter, in addition to providing us with additional useful information.

\hypertarget{estimating-a-single-mean-with-the-brms-package}{%
\section{\texorpdfstring{Estimating a single mean with the \texttt{brms} package}{Estimating a single mean with the brms package}}\label{estimating-a-single-mean-with-the-brms-package}}

The \texttt{brms} \href{https://github.com/paul-buerkner/brms}{(`Bayesian regression models')} package in R lets you fit Bayesian models using the STAN probabilistic programming language using R. The package is really amazing and makes Bayesian multilevel modeling easy and accessible for anyone. It also includes a lot of helper functions that make working with these models very convenient.

\texttt{brms} should be installed in R so that the models described below will work. Make sure you have the latest version of R (and Rstudio) and the latest version of the \texttt{brms} package installed. Sometimes using older versions can cause R to crash when fitting models. Anecdotal experience suggests that if all of the sudden trying to fit these models causes crashes or mysterious errors, its time to update one or more of R, Rstudio, or \texttt{brms}.

\hypertarget{description-of-the-model}{%
\subsection{Description of the model}\label{description-of-the-model}}

We're going to learn to read and write formal descriptions of our models. The notation we will learn will help us describe our models efficiently, and it will help us understand the models used by other people.

The relationship between statistical concepts and the formal notation used to represent them is very similar to musical notation and the ability to play music. Someone who can play a song undoubtedly \emph{knows} that song. However, in the absence of formal musical training that same person might not recognize sheet music recognizing the song. The person would also lack the vocabulary to discuss components of the song, and may find it difficult to learn to play new pieces. In the same way, most people have excellent intuitive understanding of many statistical concepts such as slopes, interactions, error, and so on. However, they lack the notational knowledge to understand these relations when expressed in the formal notation often used to express these ideas.

Recall from Chapter 1 that our `model' for a single group of normally distributed values can be thought of in one of two two ways:

\begin{equation}
\begin{split}
\\
y_{[i]} = \mu_{[i]} + \varepsilon_{[i]} \\ \\
y_{[i]} \sim \mathcal{N}(\mu_{[i]},\sigma) \\ \\
\end{split}
\label{eq:21}
\end{equation}

The top line says that your observed variable for any given trial \(y_{[i]}\) is the sum of some of some average expected value for that trial, (\(\mu_{[i]}\)) and some specific random error for that trial (\(\varepsilon_{[i]}\)). The random error is expected to be normally distributed with a mean of 0 and some unknown standard deviation (as in: \(\varepsilon_{[i]} \sim \mathcal{N}(0,\sigma)\)). The second line presents the \(y\) variable as being a normally-distributed variable with a trial-specific mean of \(\mu_i\), and a fixed standard deviation \(\sigma_{error}\)

In general, we use regression models to understand orderly variation in \(\mu_{[i]}\) from trial to trial by breaking it up into predictors (\(\mathrm{x}_{1}, \mathrm{x}_{2},...\)) that are combined using some weights (\(\alpha_1, \alpha_2,...\)). If this statement makes no sense please see Chapter 1!.

\[
\mu_{[i]} = \alpha_1*\mathrm{x}_{1{[i]}} + \alpha_2*\mathrm{x}_{2i}+...+\alpha_j*\mathrm{x}_{j{[i]}}
\label{eq:22}
\]

`Fitting' a regression model consists of trying to `guess' the values of the weighing factors (\(\alpha\)), called the \emph{model coefficients}. When we are only trying to estimate a single average, we don't have any predictors to explain variation in \(\mu_{[i]}\). In fact, our model structure suggests we expect no variation in \(\mu_{[i]}\) from trial to trial!.

Mathematically, we can't just say `we have no predictor' since everything needs to be represented by a number. As a result, we use a single `predictor' \(\mathrm{x}\) with a value of 1 so that our regression equation is:

\[
\mu_{[i]} = \alpha_1*1
\label{eq:23}
\]

Now our model is trying to guess the value of a single coefficient (\(\alpha_1\)), and we expect this coefficient to be equal to \(\mu_{[i]}\) since it is being multiplied by a `predictor' with a constant value of 1.

This kind of model is called an `Intercept only' model. Regression models are really about representing \emph{differences}, differences between groups and across conditions. When you are encoding differences, you need an overall reference point. For example, saying that something is 5 miles north is only interpretable given some reference point. The `reference point' used by your model is called your `Intercept', it is the center of your model's universe.

Basically, our model consists \emph{only} of a single reference point, and the \(\alpha_1\) parameter reflects its value (as shown in Equation \eqref{eq:23}). As a result, the \(\alpha_1\) coefficient is called the `intercept' in our model. When a coefficient is just being multiplied by a `fake' predictor that just equals 1, we can omit it from the regression model (but its still secretly there).

Based on the above, our model investigating the f0 produced by adult women from Michigan can be thought of like this:

\begin{equation}
\begin{split}
\\
f0_{[i]} \sim \mathcal{N}(\mu_{[i]},\sigma) \\ \\ 
\mu_{[i]} = Intercept \\ \\
\end{split}
\label{eq:24}
\end{equation}

Put in plain English, each line in the model says the following:

\begin{itemize}
\item
  We expect that f0 for a given observation \(i\) is normally distributed according to some trial-specific expected value and some unknown (but fixed) standard deviation.
\item
  The expected value for any given trial (\(\mu_{[i]}\)) is equal to the intercept of the model for all trials. This means its fixed and we have the same expected value for all tokens!
\end{itemize}

What the model also implicitly says that the error is drawn from a normal distribution with a mean of 0 and a standard deviation of \(\sigma\). This distribution represents all deviations in f0 around the mean f0 for the sample (\(\mu_{[i]}\)). In other words, the error for this model is expected to look like:

\[
\varepsilon_{[i]} \sim \mathcal{N}(0,\sigma)
\label{eq:25}
\]

\hypertarget{the-model-formula}{%
\subsection{The model formula}\label{the-model-formula}}

Model structures are expressed in R using a very specific syntax. Think of writing a model formula as writing a language within R. Generally, model formulas in R have the form:

\texttt{y\ \textasciitilde{}\ predictors}

The variable we are interested in understanding (\(y\)) goes on the left hand side of the \(\sim\), and on our predictors go on the right hand side. Notice that the random term (\(\varepsilon\)) is not included in the model formula.

The formula above can be read as `y is distributed according to some predictor', which really means ``we think there is systematic variation in our y variable that can be understood by considering its joint variation with our predictor variable(s).''

For intercept only models, the number \texttt{1} is included in the model formula to indicate that a single constant value is being estimated (as in \eqref{eq:23}). As a result, our model formula will have the form:

\texttt{f0\ \textasciitilde{}\ 1}

This model could be said out loud like ``we are trying to estimate the mean of f0'' or ``we are predicting mean f0 given only an intercept''.

\hypertarget{fitting-the-model-calling-the-brm-function}{%
\subsection{\texorpdfstring{Fitting the model: Calling the \texttt{brm} function}{Fitting the model: Calling the brm function}}\label{fitting-the-model-calling-the-brm-function}}

Below, I load the \texttt{brms} package, which contains the \texttt{brm} function. The \texttt{brm} function takes a model specification, data and some other information, and fits a model that estimates all the model parameters. Unless otherwise specified, \texttt{brm} assumes that the error component (\(\varepsilon\)) of your model is normally distributed. The first argument in the function call is the model formula, and the second argument tells the function where to find the data (a dataframe called \texttt{w}). The other arguments tell the function to estimates a single set of samples (chains = 1) using a single processor on your CPU (cores = 1). These arguments will be discussed more later.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Get data from course website}
\NormalTok{url1 }\OtherTok{=} \StringTok{"https://raw.githubusercontent.com/santiagobarreda"}
\NormalTok{url2 }\OtherTok{=} \StringTok{"/stats{-}class/master/data/h95\_vowel\_data.csv"}
\NormalTok{h95 }\OtherTok{=} \FunctionTok{read.csv}\NormalTok{ (}\FunctionTok{url}\NormalTok{(}\FunctionTok{paste0}\NormalTok{ (url1, url2)))}
\CommentTok{\# select women only}
\NormalTok{w }\OtherTok{=}\NormalTok{ h95[h95}\SpecialCharTok{$}\NormalTok{group }\SpecialCharTok{==} \StringTok{\textquotesingle{}w\textquotesingle{}}\NormalTok{,]}

\CommentTok{\# To ensure predictable results in examples, I will be using the same random  }
\CommentTok{\# seed throughout, and resetting it before running any \textquotesingle{}random\textquotesingle{} process.  }
\FunctionTok{set.seed}\NormalTok{ (}\DecValTok{1}\NormalTok{)}
\NormalTok{model }\OtherTok{=}\NormalTok{ brms}\SpecialCharTok{::}\FunctionTok{brm}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{, }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{chains =} \DecValTok{1}\NormalTok{, }\AttributeTok{cores =} \DecValTok{1}\NormalTok{)}

\DocumentationTok{\#\# SAMPLING FOR MODEL \textquotesingle{}77bdac4488ef47de193e19dae81fc150\textquotesingle{} NOW (CHAIN 1).}
\DocumentationTok{\#\# Chain 1: }
\DocumentationTok{\#\# Chain 1: Gradient evaluation took 0 seconds}
\DocumentationTok{\#\# Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.}
\DocumentationTok{\#\# Chain 1: Adjust your expectations accordingly!}
\DocumentationTok{\#\# Chain 1: }
\DocumentationTok{\#\# Chain 1: }
\DocumentationTok{\#\# Chain 1: Iteration:    1 / 2000 [  0\%]  (Warmup)}
\DocumentationTok{\#\# Chain 1: Iteration:  200 / 2000 [ 10\%]  (Warmup)}
\DocumentationTok{\#\# Chain 1: Iteration:  400 / 2000 [ 20\%]  (Warmup)}
\DocumentationTok{\#\# Chain 1: Iteration:  600 / 2000 [ 30\%]  (Warmup)}
\DocumentationTok{\#\# Chain 1: Iteration:  800 / 2000 [ 40\%]  (Warmup)}
\DocumentationTok{\#\# Chain 1: Iteration: 1000 / 2000 [ 50\%]  (Warmup)}
\DocumentationTok{\#\# Chain 1: Iteration: 1001 / 2000 [ 50\%]  (Sampling)}
\DocumentationTok{\#\# Chain 1: Iteration: 1200 / 2000 [ 60\%]  (Sampling)}
\DocumentationTok{\#\# Chain 1: Iteration: 1400 / 2000 [ 70\%]  (Sampling)}
\DocumentationTok{\#\# Chain 1: Iteration: 1600 / 2000 [ 80\%]  (Sampling)}
\DocumentationTok{\#\# Chain 1: Iteration: 1800 / 2000 [ 90\%]  (Sampling)}
\DocumentationTok{\#\# Chain 1: Iteration: 2000 / 2000 [100\%]  (Sampling)}
\DocumentationTok{\#\# Chain 1: }
\DocumentationTok{\#\# Chain 1:  Elapsed Time: 0.08 seconds (Warm{-}up)}
\DocumentationTok{\#\# Chain 1:                0.058 seconds (Sampling)}
\DocumentationTok{\#\# Chain 1:                0.138 seconds (Total)}
\DocumentationTok{\#\# Chain 1: }
\end{Highlighting}
\end{Shaded}

By default, \texttt{brms} takes 2000 samples, throwing out the first 1000 and returning the last 1000. The output above shows you that the sampler is working, and tells you about the progress as it works. This is a small amount of data so it should be pretty fast.

This is the last time I will be actually fitting a model in the code chunks. I am going to be relying on pre-fit models that you can load after downloading from the course GitHub. Models can be found in the folder corresponding to each chapter.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# download pre{-}fit model from: }
\CommentTok{\# github.com/santiagobarreda/stats{-}class/tree/master/models}
\CommentTok{\# and load after placing in working directory}
\NormalTok{model }\OtherTok{=} \FunctionTok{readRDS}\NormalTok{ (}\StringTok{\textquotesingle{}2\_model.RDS\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{interpreting-the-model-the-print-statement}{%
\subsection{Interpreting the model: the print statement}\label{interpreting-the-model-the-print-statement}}

Typing the model name into the console and hitting enter prints the default \texttt{brms} model print statement:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# inspect model}
\NormalTok{model}
\DocumentationTok{\#\#  Family: gaussian }
\DocumentationTok{\#\#   Links: mu = identity; sigma = identity }
\DocumentationTok{\#\# Formula: f0 \textasciitilde{} 1 }
\DocumentationTok{\#\#    Data: w (Number of observations: 576) }
\DocumentationTok{\#\# Samples: 1 chains, each with iter = 2000; warmup = 1000; thin = 1;}
\DocumentationTok{\#\#          total post{-}warmup samples = 1000}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Population{-}Level Effects: }
\DocumentationTok{\#\#           Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# Intercept   220.40      0.97   218.33   222.30 1.00      851      557}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Family Specific Parameters: }
\DocumentationTok{\#\#       Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sigma    23.24      0.69    21.99    24.61 1.00      653      550}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Samples were drawn using sampling(NUTS). For each parameter, Bulk\_ESS}
\DocumentationTok{\#\# and Tail\_ESS are effective sample size measures, and Rhat is the potential}
\DocumentationTok{\#\# scale reduction factor on split chains (at convergence, Rhat = 1).}
\end{Highlighting}
\end{Shaded}

The first part just tells you some technical details that we don't have to worry about for now (though some are obvious).

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#  Family: gaussian }
\DocumentationTok{\#\#   Links: mu = identity; sigma = identity }
\DocumentationTok{\#\# Formula: f0 \textasciitilde{} 1 }
\DocumentationTok{\#\#    Data: w (Number of observations: 576) }
\DocumentationTok{\#\# Samples: 1 chains, each with iter = 2000; warmup = 1000; thin = 1;}
\DocumentationTok{\#\#          total post{-}warmup samples = 1000}
\end{Highlighting}
\end{Shaded}

Next we see estimated effects for out predictors, in this case only an intercept. This is a `population' level effect because is is shared by all observations in our sample, and not specific to any one observation.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Population{-}Level Effects: }
\DocumentationTok{\#\#           Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# Intercept   220.40      0.97   218.33   222.30 1.00      851      557}
\end{Highlighting}
\end{Shaded}

The information above provides the mean (Estimate) and standard deviation (Est. Error) of the posterior distribution of \(\mu\) (\texttt{Intercept}). The values of \texttt{l-95\%\ CI} and \texttt{u-95\%\ CI} represent the upper and lower `95\% credible intervals' for the posterior distribution of this parameter.

The \emph{X\% credible interval} for a parameter is the smallest interval that encloses X\% of the distribution. This parameter has an X\% chance (0.X probability) of falling inside the X\% credible interval. So, this means that there is a 95\% probability that \(\mu\) is between 218 and 222 Hz given our data and model structure.

Notice that the parameter estimate and intervals almost exactly match the estimate and intervals we obtain by referencing the theoretical likelihood function (discussed in Chapter 1):

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# sample mean}
\FunctionTok{mean}\NormalTok{ (f0)}
\DocumentationTok{\#\# [1] 220.401}

\CommentTok{\# theoretical quantiles for likelihood of mean}
\FunctionTok{qnorm}\NormalTok{ (}\FunctionTok{c}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\FloatTok{0.975}\NormalTok{), }\FunctionTok{mean}\NormalTok{ (f0), }\FunctionTok{sd}\NormalTok{ (f0) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{ (}\FunctionTok{length}\NormalTok{ (f0) ) )}
\DocumentationTok{\#\# [1] 218.5047 222.2974}
\end{Highlighting}
\end{Shaded}

As noted in Chapter 1, `frequentist' and `Bayesian' estimation differ in terms of whether they rely on the posterior or likelihoods to make inferences. However, for most real cases we expect the posterior to be dominated by the likelihood (see \ref{fig:F1-posterior}, and as a result we expect Bayesian and frequentist estimation to provide roughly equivalent answers given equivalent model structures.

Our model also provides us an estimate of the error standard deviation(\(\sigma\)), under `Family Specific Parameters: sigma'. This estimate closely matches our sample standard deviation estimate (\texttt{sd(f0)}) of 23.2 Hz. In addition, we also get a 95\% credible interval for this parameter (2.5\% = 21.99, 97.5\% = 24.61).

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Family Specific Parameters: }
\DocumentationTok{\#\#       Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sigma    23.24      0.69    21.99    24.61 1.00      653      550}
\end{Highlighting}
\end{Shaded}

This last section is just boilerplate and contains some basic reminders. This text will look the same after all models.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Samples were drawn using sampling(NUTS). For each parameter, Bulk\_ESS}
\DocumentationTok{\#\# and Tail\_ESS are effective sample size measures, and Rhat is the potential}
\DocumentationTok{\#\# scale reduction factor on split chains (at convergence, Rhat = 1).}
\end{Highlighting}
\end{Shaded}

\hypertarget{seeing-the-samples}{%
\subsection{Seeing the samples}\label{seeing-the-samples}}

In Chapter 1 I discussed that samplers (like \texttt{brm}, or STAN) take samples of the posterior distributions of parameters given the data and model structure. It's helpful to see that this is quite literally what is happening, and that the print statement above just summarizes the information contained in the posterior samples. Actually, one of the great things about Bayesian models is that you can make your own summaries of the posterior samples, and summarize them in several ways as required.

Below I get the posterior samples from the model. We have 1000 samples, as indicated in the model output above. The first column represents the model intercept (\texttt{b\_Intercept}), the middle column is the error (\texttt{sigma}), and the third column is a statistic related to model fit (\texttt{lp\_\_}).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# get posterior samples from model}
\NormalTok{samples }\OtherTok{=}\NormalTok{ brms}\SpecialCharTok{::}\FunctionTok{posterior\_samples}\NormalTok{ (model)}
\FunctionTok{str}\NormalTok{ (samples)}
\DocumentationTok{\#\# \textquotesingle{}data.frame\textquotesingle{}:    1000 obs. of  3 variables:}
\DocumentationTok{\#\#  $ b\_Intercept: num  221 221 220 222 220 ...}
\DocumentationTok{\#\#  $ sigma      : num  22.1 21.9 23.2 21.9 22.9 ...}
\DocumentationTok{\#\#  $ lp\_\_       : num  {-}2635 {-}2635 {-}2634 {-}2637 {-}2634 ...}
\end{Highlighting}
\end{Shaded}

We can plot the individual samples for the mean parameter on the left below. On the right I plot a histogram of the same samples, superimposed with the theoretical distribution of the likelihood we calculated in Chapter 1.

\begin{figure}
\centering
\includegraphics{02_files/figure-latex/F2-1-1.pdf}
\caption{\label{fig:F2-1}(left) Individual samples from posterior of mean f0 parameter. (right) a histogram of the same samples.}
\end{figure}

Recall that our model output provides information about expected values for the mean parameter:

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Population{-}Level Effects: }
\DocumentationTok{\#\#           Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# Intercept   220.40      0.97   218.33   222.30 1.00      851      557}
\end{Highlighting}
\end{Shaded}

These simply correspond to the quantiles of the posterior samples! We can confirm this by checking the quantiles on the vector containing the posterior samples for the mean parameter as below:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{quantile}\NormalTok{ (samples[,}\StringTok{"b\_Intercept"}\NormalTok{], }\FunctionTok{c}\NormalTok{(.}\DecValTok{025}\NormalTok{, .}\DecValTok{5}\NormalTok{, .}\DecValTok{975}\NormalTok{))}
\DocumentationTok{\#\#     2.5\%      50\%    97.5\% }
\DocumentationTok{\#\# 218.3288 220.3997 222.3001}
\end{Highlighting}
\end{Shaded}

And we can see that these exactly correspond to the values of \texttt{Estimate}, \texttt{l-95\%\ CI}, and \texttt{u-95\%\ CI} in the model print statement above. There is no special status for these quantiles. We can check the values of other ones:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{quantile}\NormalTok{ (samples[,}\StringTok{"b\_Intercept"}\NormalTok{], }\FunctionTok{c}\NormalTok{(.}\DecValTok{25}\NormalTok{, .}\DecValTok{75}\NormalTok{))}
\DocumentationTok{\#\#      25\%      75\% }
\DocumentationTok{\#\# 219.8043 221.0296}
\end{Highlighting}
\end{Shaded}

Or even use the posterior distribution to find the probability that the mean parameter is over/under any arbitrary value:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{ (samples[,}\StringTok{"b\_Intercept"}\NormalTok{] }\SpecialCharTok{\textless{}} \DecValTok{221}\NormalTok{) }\SpecialCharTok{/} \DecValTok{576}
\DocumentationTok{\#\# [1] 1.284722}
\end{Highlighting}
\end{Shaded}

Let's take a second to think about why this works. Recall that the probability is the odds that something will occur out of all the possible outcomes. Our vector \texttt{samples{[},"b\_Intercept"{]}} represents 1000 observations of a random variable, 1000 possible values of the average f0 produced by adult women from Michigan. If we find the total number of these observations that were below 221 Hz and then divide by the total number of observations (576), we are calculating the probability of observing a mean estimate below 221 Hz. As a result, the calculation above says that there is a 0.74 probability (a 74\% chance) that the mean f0 for female speakers in this population is under 221 Hz, given our data and model structure. We come to this conclusion by finding that 74\% of the posterior samples of the parameter of interest are below 221 Hz.

\hypertarget{repeated-measures-data}{%
\section{Repeated measures data}\label{repeated-measures-data}}

The model we fit above is a reasonable starting point, but it has many weaknesses. Importantly, our data consists of 12 productions from each speaker in our sample, meaning we have `repeated measures' data. However, our model does not contain this information an thinks that the 576 observations in our data are entirely independent. Treating repeated measures data as if it were \emph{not} repeated measures data can cause problems for our inferences. This is because it can give us a warped perspective of how much variability there really is in the sample.

For example, if I told you I had 1,000,000 samples of speech from male speakers from Los Angeles, you may be confident that I can estimate the average f0 male speakers from Los Angeles very accurately. But what if I told you that all these samples were from only three different people? You know instinctively that this makes my data less reliable for making inferences about Los Angeles in general, although it may provide excellent information about these three speakers.

The reason repeated-measures data can cause problems is because the measurements are correlated: multiple measurements from the same person are obviously going to be related to each other. If you measure the height of a tall person today, they will still be tall tomorrow. This can be seen quite clearly below. The top panel shows the distribution of all our f0 measurements. The bottom panel shows speaker boxplots (one for each speaker's data). If we were to `push down' on the bottom panel and collapse all our boxplots into a single distribution, we would end up with the boxplot in the top panel.

These boxplots shows that each speaker has their own average f0, and that their productions tend to vary around their `natural average. As a result, we might have something closer to 48 independent observations (one average value per speaker) than 576. For example, if we look at the top boxplot there appear to be 'outliers' around 150 Hz. In the bottom plot we see that these productions all come from one speaker, and actually reflect her average f0. As a result, it seems that the \emph{speaker} is the outlier, and that the values are actually perfectly average for this speaker.

\begin{figure}
\centering
\includegraphics{02_files/figure-latex/F2-2-1.pdf}
\caption{\label{fig:F2-2}(top) Boxplot of overall distribution. (bottom) Speaker-specific boxplot of our f0 data.}
\end{figure}

\hypertarget{multilevel-models}{%
\subsection{Multilevel models}\label{multilevel-models}}

In linguistics (and many other similar fields) almost all of our data is repeated measures data. The methods most commonly-used by linguists (e.g., experiments, interviews, corpora, \ldots{} etc.) yield many observations per person, and typically all involve data from multiple people/sources. As a result, the analysis of this data requires that models be able to account for within \emph{and} between speaker variation in our data. Multilevel models address the correlated nature of repeated measures data by estimating multiple sources of variation simultaneously.

We can think about how this applies to our f0 sample. Each person picked at random has some average f0 they produce. This is \emph{between-speaker} variation: If you pick to people at random they will differ. However, each person also produces a different random f0 every time they speak, so that they will never produce exactly their average f0: this is \emph{within-speaker} variation.

Repeated-measures data leads to random variation in parameters that is \emph{indistinguishable} from that of our `data'. For example, consider the figure below. First we consider a single speaker's production (left) and produce a histogram that suggests a normal distribution reminiscent in shape to the overall aggregated data. In the middle, we see individual boxplots showing variation in speaker averages. Here we see that although each speakers productions are a distribution, variation in the distribution of the speaker averages is its own sort of distribution. Finally, on the right we see a histogram of the speaker averages and see that these are also normally distributed.

To a large extent, whether something is a parameter or a data point depends somewhat on your perspective. For example, consider the figure below. If you are trying to estimate a speaker's mean f0, then the individual productions might be `data' and the mean can be thought of as a `parameter'. If you were instead only interested in the population average, maybe now your subject mean is actually just a single data point, and the \emph{population} mean is actually your `parameter'.

\begin{figure}
\centering
\includegraphics{02_files/figure-latex/F2-3-1.pdf}
\caption{\label{fig:F2-3}(top left) All the f0 data (top right) A boxplot of the same data. (bottom left) Speaker-specific boxplots, with a vertical line for speaker 107. (bottom right) The histogram of data produced by speaker 107.}
\end{figure}

A multilevel model is able to simultaneously estimate variation at multiple `levels'. This is actually why it's called a \emph{multilevel} model! For our f0 data, our `levels' are:

\begin{itemize}
\item
  The `upper' level: Between-speaker variation in mean f0. This can be thought of as variation in a new variable, which we will call \(\mu_{speaker}\). Speakers have an average f0 (\(\mu_{speaker}\)) that they produce over time. However, speakers are chosen randomly from a larger population, and so any given speaker's \(\mu_{speaker}\) is unpredictable a priori.
\item
  The `lower' level: Within-speaker variation, random error analogous to \(\varepsilon\). When an individual speaker produces speech, their productions will vary around their average from token to token. Our model cannot explain this and so this is `error'
\end{itemize}

As seen in the figure above, the variation at the lower and upper levels are analogous. Just like individual speakers will rarely have an average f0 exactly like the population average, individual speakers will rarely produce f0 values exactly at their speaker average. Importantly, variation at the two levels is independent and logically distinct: within-speaker variation can be small or large independently of whether between-speaker variation is large or small.

Basically, each subject's productions form a little normal distribution around their average, and the mix of these little distributions results in the overall `big' distribution of data across all subjects. By using multilevel models, we can estimate the effects of multiple sources of variation at the same time.

\hypertarget{estimating-a-multilevel-model-with-brms}{%
\section{\texorpdfstring{Estimating a multilevel model with \texttt{brms}}{Estimating a multilevel model with brms}}\label{estimating-a-multilevel-model-with-brms}}

We're now going to fit the same model we fit above, but with a structure that reflects the repeated-measures nature of the data. Whereas the last model was a pedagogical device, this model structure is actually appropriate to analyze this particular dataset.

\hypertarget{description-of-the-model-1}{%
\subsection{Description of the model}\label{description-of-the-model-1}}

We're going to keep working on developing an intuitive understanding for model notation, and using it to describe models. Just keep in mind that this is nothing more than an efficient way to denote the concepts being discussed in the text.

To specify a multilevel model, you need to write a slightly more complicated model formula. This explanation assumes that you have a dataframe or matrix where one column contains the variable you are interested in predicting (in this case \texttt{f0}), and another column contains a vector containing unique labels for each speaker/listener/participant (in this case a unique speaker label \texttt{speaker}).

To indicate that your model contains an `upper' level where you have clusters of data coming from different individuals, you have to put another model inside your main model!

Before, the model formula looked like this:

\texttt{f0\ \textasciitilde{}\ 1}

which meant `predict f0 using only an intercept'. Now the model formula will look like this:

\texttt{f0\ \textasciitilde{}\ 1\ +\ (\ 1\ \textbar{}\ speaker)}

When you place a predictor in the formula in parenthesis and on the right-hand-side of a pipe, like this \texttt{(\ \textbar{}\ predictor\ )}, you tell \texttt{brm} that you expect data to be clustered according to each category represented in the grouping vector. In this case, we are telling \texttt{brm} that each unique speaker is a cluster of data. Whatever you put in the left-hand-side of the parentheses \texttt{(\ in\ here\ \textbar{}\ predictor\ )} is the model for each subcluster!

So what does this model formula mean: \texttt{f0\ \textasciitilde{}\ 1\ +\ (\ 1\ \textbar{}\ speaker)}? Remember a model formula consisting only of a \texttt{1} tells \texttt{brm} that we have an Intercept-only model. So, our new formula tells \texttt{brm}: predict f0 based on only an overall intercept, but also estimate a different intercept for each speaker. Effectively, this model formula is telling \texttt{brm} to figure out all the information presented in the figures above.

This regression model is now something like this:

\begin{equation}
\begin{split}
\\
f0_{[i]} \sim \mathcal{N}(\mu_{[i]},\sigma) \\ \\
\mu_{[i]} = Intercept + \alpha_{speaker_{[i]}} \\
\\
\end{split}
\label{eq:26}
\end{equation}

In plain English, the model above says: we expect f0 to be normally distributed. The f0 value we expect for any given token is equal to some overall average (\(Intercept\)), and some value associated with the individual speaker (\(\alpha_{speaker_{[i]}}\)) who uttered the trial.

We now have another term \(\alpha_{speaker}\), in addition to the intercept. This coefficient is actually a set of coefficients since it has a different value for each speaker (it's a vector). Notice that the although the Intercept is fixed, value of \(\alpha_{speaker}\) that should be used will vary from trial to trial based on the speaker associated with the trial. We will discuss coefficients like these in more detail later, we don't really need to worry about it for now.

The value of \(\alpha_{speaker}\) has a different value for each speaker because it will reflect variation in \(\mu_{speaker}\), the average f0 value produced by each speaker. However, \(\mu_{speaker}\) is a random variable since it reflects the random average f0 of each person drawn from the population. If \(\mu_{speaker}\) behaves like a random variable, then the coefficients that reflect this value in our model (\(\alpha_{speaker}\)) will behave in the same way.

This means that our model actually has \emph{two} random variables. The first one is the error term \(\varepsilon_{[i]} \sim \mathcal{N}(0,\sigma_{error})\), which has a mean of 0 and a standard deviation which we can refer to as \(\sigma_{error}\). The second is the random coefficients that allow for speaker-specific adjustments to the intercept (\(\alpha_{speaker}\)). These can also be thought of as random draw from a normal distribution.

A careful consideration of the model in equation 2.4 suggests that the (\(\alpha_{speaker}\)) coefficients can't actually be exactly equal to \(\mu_{speaker}\), the average f0 for a speaker. If the overall mean (the intercept) is 220 Hz and a speaker's average is 230, this would suggest a predicted average of 450 (\(Intercept + \mu_{speaker}\)) for this speaker. Clearly that is not how the model should be working.

Recall that regression models encode \emph{differences}, rather than absolute values. Our model already represents the overall data average in the intercept parameter. Thus, the speaker-specific averages only need to contain information about \emph{differences} to this reference value. As a result, coefficients such as \(\alpha_{speaker}\) are modelled as being normally distributed with a mean of 0, and with some population-specific standard deviation.

Since our model coefficients reflect speaker-specific \emph{deviations} rather than the actual mean f0 of different speakers, people often use this symbol, \(\gamma\), for them instead of \(\mu\), where \(\gamma\) reflects the difference between the speaker means and the mean for the population of speakers, \(\gamma_{speaker} = \mu_{speaker} - \mu_{population}\).

We can show the expected distribution of this variable below, where \(\sigma_{speakers}\) is a population-specific standard deviation term. Note the similarity of this to the expected variation in our original data in Equation \eqref{eq:24}.

\begin{equation}
\begin{split}
\\
\gamma_{speaker} \sim \mathcal{N}(0,\sigma_{speakers}) \\ \\ 
\gamma_{speaker} = \alpha_{speaker} \\ \\
\end{split}
\label{eq:27}
\end{equation}

Our overall model is now as shown below, made specific for the data we have, and using expected parameter names.

\begin{equation}
\begin{split}
\\
f0_{[i]} \sim \mathcal{N}(\mu_{[i]},\sigma_{error}) \\ \\
\mu_{[i]} = Intercept + \alpha_{speaker_{[i]}} \\ \\
\alpha_{speaker} \sim \mathcal{N}(0,\sigma_{speakers}) \\ \\
\end{split}
\label{eq:28}
\end{equation}

Each line in the model says the following:

\begin{itemize}
\item
  observed f0 is expected to be normally distributed around a trial-specific mean, with some unknown but fixed standard deviation (\(\sigma_{error}\)).
\item
  the expected value for a given trial (\(\mu_{[i]}\)) is equal to the model intercept, plus some speaker-specific deviation/difference from the intercept for the speaker that produced that trial (\(\alpha_{speaker_{[i]}}\)).
\item
  the speaker effects (\(\alpha_{speaker}\)) are also drawn from a normal distribution with a mean of 0 and a standard deviation of \(\sigma_{speakers}\). This distribution represents the random, but systematic, between-speaker variation in average productions that exists within any population of speakers.
\end{itemize}

All of this information can be seen in the speaker boxplots below. The model intercept (horizontal dotted line) represents the overall mean, and the variation in \(\alpha_{speaker}\) is what causes the middle of each little box to differ from the mean. Finally, the error causes there to be a spread, a \emph{distribution}, around each speaker's individual mean.

\begin{figure}
\centering
\includegraphics{02_files/figure-latex/F2-4-1.pdf}
\caption{\label{fig:F2-4}Speaker-specific boxplots for the f0 data.}
\end{figure}

There is a very important difference in how the first and second models we fit view and partition the variation in our model. The initial model we fit broke down the total variation in the model (\(\sigma_{total}\)) like this:

\[
\sigma_{total} = \sigma_{error}
\label{eq:29}
\]

In other words, all variation was error. We don't know why values vary from the mean. Our multilevel model views the variation in our data like this:

\[
\sigma_{total} = \sigma_{speaker} + \sigma_{error}
\label{eq:210}
\]

From the perspective of this model, only the variation \emph{within} a speaker's individual boxplot is error. The differences from box to box represent random (but systematic) between-speaker variation in f0.

\hypertarget{fitting-the-model}{%
\subsection{Fitting the model}\label{fitting-the-model}}

We can fit a model with a formula that appropriately specifies the clustering we expect in our data. As a result, this model can estimate both between- and within-speaker variability.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit the model yourself, or}
\FunctionTok{set.seed}\NormalTok{ (}\DecValTok{1}\NormalTok{)}
\NormalTok{multilevel\_model }\OtherTok{=}  
  \FunctionTok{brm}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{speaker), }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{chains =} \DecValTok{1}\NormalTok{, }\AttributeTok{cores =} \DecValTok{1}\NormalTok{)}

\CommentTok{\# download pre{-}fit model from: }
\CommentTok{\# github.com/santiagobarreda/stats{-}class/tree/master/models}
\CommentTok{\# and load after placing in working directory}
\NormalTok{multilevel\_model }\OtherTok{=} \FunctionTok{readRDS}\NormalTok{ (}\StringTok{"2\_multilevel\_model.RDS"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# inspect model}
\NormalTok{multilevel\_model}
\DocumentationTok{\#\#  Family: gaussian }
\DocumentationTok{\#\#   Links: mu = identity; sigma = identity }
\DocumentationTok{\#\# Formula: f0 \textasciitilde{} (1 | uspeaker) }
\DocumentationTok{\#\#    Data: w (Number of observations: 576) }
\DocumentationTok{\#\# Samples: 1 chains, each with iter = 2000; warmup = 1000; thin = 1;}
\DocumentationTok{\#\#          total post{-}warmup samples = 1000}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Group{-}Level Effects: }
\DocumentationTok{\#\# \textasciitilde{}uspeaker (Number of levels: 48) }
\DocumentationTok{\#\#               Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sd(Intercept)    20.19      2.10    16.65    25.06 1.00      135      192}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Population{-}Level Effects: }
\DocumentationTok{\#\#           Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# Intercept   220.39      3.10   214.49   226.13 1.03       51      108}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Family Specific Parameters: }
\DocumentationTok{\#\#       Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sigma    12.54      0.39    11.83    13.34 1.01      400      700}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Samples were drawn using sampling(NUTS). For each parameter, Bulk\_ESS}
\DocumentationTok{\#\# and Tail\_ESS are effective sample size measures, and Rhat is the potential}
\DocumentationTok{\#\# scale reduction factor on split chains (at convergence, Rhat = 1).}
\end{Highlighting}
\end{Shaded}

This new model contains one new chunk its print statement. This section tells us about the standard deviation for the Intercept (\texttt{sd(Intercept)}) for the \texttt{\textasciitilde{}speaker} cluster:

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Group{-}Level Effects: }
\DocumentationTok{\#\# \textasciitilde{}speaker (Number of levels: 48) }
\DocumentationTok{\#\#               Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sd(Intercept)    20.19      2.10    16.65    25.06 1.00      135      192}
\end{Highlighting}
\end{Shaded}

This parameter corresponds to \(\sigma_{speaker}\) above, the standard deviation of between-speaker averages (\(\alpha_{speaker}\)) in the sample. Below, we calculate the speaker mean f0 values, the standard deviation of these, and the amount of within-speaker variation in f0s.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# find mean f0 for each speaker}
\NormalTok{speaker\_means }\OtherTok{=} \FunctionTok{aggregate}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{FUN =}\NormalTok{ mean) }
\CommentTok{\# find the within speaker standard deviation This is the within{-}talker \textquotesingle{}error\textquotesingle{}.}
\NormalTok{speaker\_sigmas }\OtherTok{=} \FunctionTok{aggregate}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{FUN =}\NormalTok{ sd) }

\CommentTok{\# the mean of the speaker means corresponds to our overall mean estimate}
\FunctionTok{mean}\NormalTok{ (speaker\_means}\SpecialCharTok{$}\NormalTok{f0)}
\DocumentationTok{\#\# [1] 220.401}

\CommentTok{\# the standard deviation of the speaker means corresponds to \textquotesingle{}sd(Intercept)\textquotesingle{}, the }
\CommentTok{\# estimate of the standard deviation of speaker intercepts}
\FunctionTok{sd}\NormalTok{ (speaker\_means}\SpecialCharTok{$}\NormalTok{f0)}
\DocumentationTok{\#\# [1] 20.07397}

\CommentTok{\# the average within{-}speaker standard deviation corresponds to \textquotesingle{}sigma\textquotesingle{}, the }
\CommentTok{\# estimated error}
\FunctionTok{mean}\NormalTok{ (speaker\_sigmas}\SpecialCharTok{$}\NormalTok{f0)}
\DocumentationTok{\#\# [1] 11.6791}
\end{Highlighting}
\end{Shaded}

We are going to discuss the calculations we made above in terms of what they represent in the boxplots below. The overall mean f0 in our data (220.4) corresponds quite well to our model estimate of 220.4. This reflects the central location of the overall distribution below (the horizontal line in the figure below). The standard deviation of the speaker means (20.1) is again very similar to our model estimate (sd(Intercept) = 20.2). This reflects the average distance from each speaker's average to the overall average. Finally, the average of the within speaker standard deviation in our data (11.7) corresponds closely to our model's error estimate (sigma = 12.5). This reflects the average spread of each speaker's data relative to their own mean, within their own little boxplot. We can see that the information provided by \texttt{brms} is quite similar to what we can estimate directly using our data. However, \emph{brms} does this all for us, in addition to giving us a lot more information.

\begin{figure}
\centering
\includegraphics{02_files/figure-latex/F2-5-1.pdf}
\caption{\label{fig:F2-5}Speaker-specific boxplots for the f0 data we are analyzing.}
\end{figure}

\hypertarget{checking-model-convergence}{%
\section{Checking model convergence}\label{checking-model-convergence}}

Remember that our parameter estimates are based of a set of samples from the posterior distribution of a parameter. If we don't take enough of these samples, our parameter estimates will be unreliable.

For this reason, it's important to look at the ESS values (the `expected sample size'), and the `Rhat' values provided by \texttt{brm}. ESS tells you about how many independent samples you have taken from the likelihood. Bulk ESS is how many samples the sampler took in the thick part of the density, and Tail ESS reflects how much time the sampler spent in the thin part, the `tails'. Rhat tells you about whether your `chains' have converged (more on this later). As noted above, values of Rhat near 1 are good, and values higher than around 1.1 are a bad sign.

We haven't really taken many samples here, so we can't be confident in our parameter estimates. Ideally we would like several hundred samples (at least) for mean estimates, and thousands to be confident in the 95\% confidence intervals. If you fit a model and get a warning message like this:

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Warning messages:}
\DocumentationTok{\#\# 1: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.}
\DocumentationTok{\#\# Running the chains for more iterations may help. See}
\DocumentationTok{\#\# http://mc{-}stan.org/misc/warnings.html\#bulk{-}ess}
\DocumentationTok{\#\# 2: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.}
\DocumentationTok{\#\# Running the chains for more iterations may help. See}
\DocumentationTok{\#\# http://mc{-}stan.org/misc/warnings.html\#tail{-}ess}
\end{Highlighting}
\end{Shaded}

That is \texttt{brms} telling you that you need to collect more samples in order to be confident in your parameter estimates. To get more samples we can run the model longer, or we can use more \emph{chains}. A chain is basically a separate set of samples for your parameter values. A model can be fit in parallel across several chains, and then the estimates can be merged across chains. When you do this across multiple cores, you can get N times as many samples when you use N cores. Since many computers these days have 4-8 (or more) cores, we can take advantage of parallel processing to fit models faster.

Before fitting a model across multiple cores, you should confirm how many you have. You can use the following command (you may need to install the \texttt{parallel} package):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{parallel}\SpecialCharTok{::}\FunctionTok{detectCores}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

I will be using four cores to fit models throughout. If you only have 4 total cores, consider changing the model fits to 2-3 chains and cores. One thing to keep in mind is that these models are computationally intensive to fit. As the datasets become larger and the models become more complicated, more powerful computers are needed in order to fit a model in a reasonable amount of time.

Below, I refit the same model from above but run it on 4 chains, and on 4 cores at once.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit the model yourself, or}
\FunctionTok{set.seed}\NormalTok{ (}\DecValTok{1}\NormalTok{)}
\NormalTok{multilevel\_multicore }\OtherTok{=}  
\NormalTok{  brms}\SpecialCharTok{::}\FunctionTok{brm}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{speaker), }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{chains =} \DecValTok{4}\NormalTok{, }\AttributeTok{cores =} \DecValTok{4}\NormalTok{)}

\CommentTok{\# download pre{-}fit model from: }
\CommentTok{\# github.com/santiagobarreda/stats{-}class/tree/master/models}
\CommentTok{\# and load after placing in working directory}
\NormalTok{multilevel\_multicore }\OtherTok{=} \FunctionTok{readRDS}\NormalTok{ (}\StringTok{\textquotesingle{}2\_multilevel\_multicore.RDS\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# inspect model}
\NormalTok{multilevel\_multicore}
\DocumentationTok{\#\#  Family: gaussian }
\DocumentationTok{\#\#   Links: mu = identity; sigma = identity }
\DocumentationTok{\#\# Formula: f0 \textasciitilde{} 1 + (1 | uspeaker) }
\DocumentationTok{\#\#    Data: w (Number of observations: 576) }
\DocumentationTok{\#\# Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;}
\DocumentationTok{\#\#          total post{-}warmup samples = 4000}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Group{-}Level Effects: }
\DocumentationTok{\#\# \textasciitilde{}uspeaker (Number of levels: 48) }
\DocumentationTok{\#\#               Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sd(Intercept)    20.22      2.19    16.54    25.19 1.02      345      615}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Population{-}Level Effects: }
\DocumentationTok{\#\#           Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# Intercept   220.47      2.91   214.67   226.14 1.02      228      543}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Family Specific Parameters: }
\DocumentationTok{\#\#       Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sigma    12.54      0.39    11.81    13.34 1.00     3427     2943}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Samples were drawn using sampling(NUTS). For each parameter, Bulk\_ESS}
\DocumentationTok{\#\# and Tail\_ESS are effective sample size measures, and Rhat is the potential}
\DocumentationTok{\#\# scale reduction factor on split chains (at convergence, Rhat = 1).}
\end{Highlighting}
\end{Shaded}

If we compare the ESS for this new model to the previous model, we see that using 4 chains has substantially increased our ESS, without taking up any more computing time.

One final tweak that I will be using going forward is to `thin' samples. Notice that we have collected \texttt{total\ post-warmup\ samples\ =\ 4000}. This means our model has 4000 samples for every parameter in the model. However, for some parameter we have only about 400 `effective samples'. This means that a lot of our samples are basically dead weight, taking up space and slowing down future computations for no good reason.

The discrepancy between the number of samples and the `effective' number of samples is due to something called \emph{autocorrelation}. Sometimes consecutive samples can be too similar and so don't given you that much \emph{independent} information. When this happens you end up with less information about a parameter than you might think based on the number of samples you have. One way to fix this is to run longer chains and keep only every Nth one. This lets your models be smaller while containing approximately the same information.

To do this you have to change the \texttt{iter}, \texttt{warmup} and \texttt{thin} parameters. You will keep every sample after the warmup is done, up to the \texttt{iter} maximum. So if \texttt{iter=3000} and \texttt{warmup=1000} you will end up with 2000 samples. After this, you keep only one every \texttt{thin} samples. Basically, you will end up with \((iter-warmup) / thin\) samples per chain. If you are doing this across \texttt{Ncores} cores, then you will end up with \(((iter-warmup) / thin) \times Ncores\) samples in total.

Below, I ask for 11,000 sample per chain. Since the warmup is 1000 this means we will keep 10,000 post warm-up. However, since \texttt{thin=10}, we will keep only 1000 of these. Finally, since we are fitting the model on four cores, we will end up with 4000 samples in total. As a resul, despite having the same number of samples as the \texttt{multilevel\_multicore}, the ESS for this model is much higher for important parameters such as the model intercept.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit the model yourself, or}
\FunctionTok{set.seed}\NormalTok{ (}\DecValTok{1}\NormalTok{)}
\NormalTok{multilevel\_thinned }\OtherTok{=}  
  \FunctionTok{brm}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{speaker), }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{chains =} \DecValTok{4}\NormalTok{, }\AttributeTok{cores =} \DecValTok{4}\NormalTok{,}
       \AttributeTok{warmup =} \DecValTok{1000}\NormalTok{, }\AttributeTok{iter =} \DecValTok{11000}\NormalTok{, }\AttributeTok{thin =} \DecValTok{10}\NormalTok{)}

\CommentTok{\# download pre{-}fit model from: }
\CommentTok{\# github.com/santiagobarreda/stats{-}class/tree/master/models}
\CommentTok{\# and load after placing in working directory}
\NormalTok{multilevel\_thinned }\OtherTok{=} \FunctionTok{readRDS}\NormalTok{ (}\StringTok{\textquotesingle{}2\_multilevel\_thinned.RDS\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# inspect model}
\NormalTok{multilevel\_thinned}
\DocumentationTok{\#\#  Family: gaussian }
\DocumentationTok{\#\#   Links: mu = identity; sigma = identity }
\DocumentationTok{\#\# Formula: f0 \textasciitilde{} 1 + (1 | uspeaker) }
\DocumentationTok{\#\#    Data: w (Number of observations: 576) }
\DocumentationTok{\#\# Samples: 4 chains, each with iter = 11000; warmup = 1000; thin = 10;}
\DocumentationTok{\#\#          total post{-}warmup samples = 4000}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Group{-}Level Effects: }
\DocumentationTok{\#\# \textasciitilde{}uspeaker (Number of levels: 48) }
\DocumentationTok{\#\#               Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sd(Intercept)    20.06      2.23    16.24    24.98 1.00     2775     3392}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Population{-}Level Effects: }
\DocumentationTok{\#\#           Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# Intercept   220.40      2.95   214.57   226.19 1.00     1987     2625}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Family Specific Parameters: }
\DocumentationTok{\#\#       Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sigma    12.54      0.38    11.81    13.31 1.00     3908     3891}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Samples were drawn using sampling(NUTS). For each parameter, Bulk\_ESS}
\DocumentationTok{\#\# and Tail\_ESS are effective sample size measures, and Rhat is the potential}
\DocumentationTok{\#\# scale reduction factor on split chains (at convergence, Rhat = 1).}
\end{Highlighting}
\end{Shaded}

\hypertarget{specifying-prior-probabilities}{%
\section{Specifying prior probabilities}\label{specifying-prior-probabilities}}

In Chapter 1 we discussed that Bayesian models require that prior probabilities be specified for all parameters. You may have noticed that to this point I haven't discussed priors at all.

If you don't specify prior probabilities for your parameters, \texttt{brm} will use a `flat/uniform' prior for all parameters. When you do this, you are basically relying only on the likelihood for your analysis. You are also telling your model that, a priori, \emph{any} value of average f0 is equally believable. Empirically, this is false. As a practical matter this can cause problems for samplers like STAN (which is what \texttt{brm} relies on). Basically, in the absence of proper priors the sampler has a harder time figuring out the most likely values when you tell it to look anywhere from positive to negative infinity. Even a bit of guidance can help.

\texttt{brms} makes it really easy to specify prior probabilities for specific parameters or whole groups of parameters. Below, I set priors for whole classes of parameters. In the example below, I use this information to set reasonable bounds on the parameters in the model. I do this by class of parameter:

\begin{itemize}
\tightlist
\item
  \texttt{Intercept}: this is a unique class, only for intercepts.
\item
  \texttt{b}: this is for all the non-intercept predictors. There are none in this model for now.
\item
  \texttt{sd}: this is for our standard deviation parameters that relate to `batches' of parameters. In our example this is \texttt{sd(Intercept)} for \texttt{speaker} (\(\sigma_{speakers}\)).
\item
  \texttt{sigma}: this is for any error parameters. Our only has one (but it could have more!), that is \texttt{sigma} (\(\sigma_{error}\)).
\end{itemize}

We're not going to worry about priors too much for now, and we're just going to set what are called `weakly informative' prior probabilities for our parameters. These are priors that encode a bit of information about our prior beliefes for a parameter, but are not \emph{too} strong. To set these, you have to use what you know about your variables, the world, and a healthy does of `common sense'. We will see a lot of examples of, and strategies for, setting priors in this book so you will get a chance to build your intuitions about it.

Both priors below use a `t' distribution, which is just like a normal distribution but it's more pointy, and has more density in the outer parts of the distribution. You can use normal priors, or any other priors that you think work for your model. Rather than focusing on the \emph{mathematical} properties of priors, the most important thing is that their \emph{shape} reflect the distribution of credible parameter values a priori (before you conducted your experiment).

The code to set the priors for our model looks like this:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{  prior }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\FunctionTok{set\_prior}\NormalTok{(}\StringTok{"student\_t(3, 220, 50)"}\NormalTok{, }\AttributeTok{class =} \StringTok{"Intercept"}\NormalTok{),}
            \FunctionTok{set\_prior}\NormalTok{(}\StringTok{"student\_t(3, 0, 100)"}\NormalTok{, }\AttributeTok{class =} \StringTok{"sd"}\NormalTok{),}
            \FunctionTok{set\_prior}\NormalTok{(}\StringTok{"student\_t(3, 0, 100)"}\NormalTok{, }\AttributeTok{class =} \StringTok{"sigma"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

The format for the priors is like this \texttt{student\_t(nu,\ mean,\ sd)}, where \texttt{nu} is a parameter that determines how pointy the distribution is, and \texttt{mean} and \texttt{sd} are the same mean and standard deviation parameters from the normal distribution. The nu parameter ranges from 1 to infinity, and large numbers result in a more normal-like distribution. We will talk about the t-distribution ins more detail later.

For the overall model intercept we set a prior probability of \texttt{student\_t(3,\ 220,\ 110)}. Around 90-95\% of the distribution of normal and t distributions is within two standard deviations of the mean. This means that I am saying the intercept should be between around 0 and 440 Hz. Since this range is higher than the range of human speaker f0s (about 80-300 Hz), this prior is not going to affect our outcomes very much.

The prior for the speaker standard deviation parameter (\(\sigma_{speakers}\)) is \texttt{student\_t(3,\ 0,\ 100)}, which specifies a t distribution centered at 0, with a standard deviation of 100. Since standard deviations can only be positive, the sampler (STAN) used by \texttt{brm} ignores the negative half, and uses only the positive values in the prior distribution. This prior just says that we expect the average difference between speakers to be less than 200 Hz (which it definitely is).

Finally, the prior for the random error is also \texttt{student\_t(3,\ 0,\ 100)}. Again, this says that we expect that the standard deviation of our random error to be less than 200 Hz. Since our random error is within-speaker variation, this is a again a massive overestimation of the likely magnitude of the random error in this data.

The left panel below compares the t distribution we used (blue) to the equivalent normal distribution (red). Although it may not seem like much of a difference, the t distribution can tolerate more extreme values because of its `fatter' (more dense) tails. As we will discuss later, using t distributions can make our models more robust to outliers. This is really important in linguistics where subjects/speakers sometimes do weird stuff! As we can see, the prior distribution we used for the intercept is much broader (more vague) than the data distribution so that it will have basically no effect on our results (but will help our model fit properly).

The right panel compares the prior for the standard deviation parameters to the absolute value of the centered f0 data. This presentation shows how far each observation is from the mean f0 (at 220 Hz). Obviously, people can't differ from each other by more than deviations differ from the mean. As a result, we see that the prior distribution we have assigned for the \texttt{sigma} (i.e., \(\sigma_{[speaker]}\)) and speaker \texttt{sd(Intercept)} parameter (i.e., \(\sigma_{[speaker]}\)) are much broader than these parameters could be, given the data. As a result, neither of these priors is going to have much of an effect on our parameter estimates.

\begin{figure}
\centering
\includegraphics{02_files/figure-latex/F2-6-1.pdf}
\caption{\label{fig:F2-6}(left) A comparison of the densities of normal and t distributions with the same means and sigma parameters. The histogram shows our f0 data. (right) The distribution of absolute deviations from the mean for our f0 data, compared to the prior distributions of our standard deviation parameters in our model.}
\end{figure}

We can fit this new model below, and inspect the output. If we compare the output of this model to \texttt{multilevel\_thinned}, we see that specifying a prior has has no noticeable effect on our results. This is because the prior matters less and less when you have a lot of data, and because we have set wide priors that are appropriate (but vague) given our data. Although the priors may not matter much for models as simple as these, they can be very important when working with more complex data, and are a necessary component of Bayesian modeling.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit the model yourself, or}
\FunctionTok{set.seed}\NormalTok{ (}\DecValTok{1}\NormalTok{)}
\NormalTok{multilevel\_priors }\OtherTok{=}  
  \FunctionTok{brm}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{speaker), }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{chains =} \DecValTok{4}\NormalTok{, }\AttributeTok{cores =} \DecValTok{4}\NormalTok{,}
       \AttributeTok{warmup =} \DecValTok{1000}\NormalTok{, }\AttributeTok{iter =} \DecValTok{11000}\NormalTok{, }\AttributeTok{thin =} \DecValTok{10}\NormalTok{,}
       \AttributeTok{prior =} \FunctionTok{c}\NormalTok{(}\FunctionTok{set\_prior}\NormalTok{(}\StringTok{"student\_t(3, 220, 100)"}\NormalTok{, }\AttributeTok{class =} \StringTok{"Intercept"}\NormalTok{),}
                 \FunctionTok{set\_prior}\NormalTok{(}\StringTok{"student\_t(3, 0, 100)"}\NormalTok{, }\AttributeTok{class =} \StringTok{"sd"}\NormalTok{),}
                 \FunctionTok{set\_prior}\NormalTok{(}\StringTok{"student\_t(3, 0, 100)"}\NormalTok{, }\AttributeTok{class =} \StringTok{"sigma"}\NormalTok{)))}

\CommentTok{\# download pre{-}fit model from: }
\CommentTok{\# github.com/santiagobarreda/stats{-}class/tree/master/models}
\CommentTok{\# and load after placing in working directory}
\NormalTok{multilevel\_priors }\OtherTok{=} \FunctionTok{readRDS}\NormalTok{ (}\StringTok{\textquotesingle{}2\_multilevel\_priors.RDS\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# inspect model}
\NormalTok{multilevel\_priors}
\DocumentationTok{\#\#  Family: gaussian }
\DocumentationTok{\#\#   Links: mu = identity; sigma = identity }
\DocumentationTok{\#\# Formula: f0 \textasciitilde{} 1 + (1 | uspeaker) }
\DocumentationTok{\#\#    Data: w (Number of observations: 576) }
\DocumentationTok{\#\# Samples: 4 chains, each with iter = 11000; warmup = 1000; thin = 10;}
\DocumentationTok{\#\#          total post{-}warmup samples = 4000}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Group{-}Level Effects: }
\DocumentationTok{\#\# \textasciitilde{}uspeaker (Number of levels: 48) }
\DocumentationTok{\#\#               Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sd(Intercept)    20.19      2.24    16.29    25.06 1.00     3114     3663}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Population{-}Level Effects: }
\DocumentationTok{\#\#           Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# Intercept   220.42      2.97   214.44   226.38 1.00     1796     2841}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Family Specific Parameters: }
\DocumentationTok{\#\#       Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sigma    12.54      0.39    11.81    13.34 1.00     3968     3972}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Samples were drawn using sampling(NUTS). For each parameter, Bulk\_ESS}
\DocumentationTok{\#\# and Tail\_ESS are effective sample size measures, and Rhat is the potential}
\DocumentationTok{\#\# scale reduction factor on split chains (at convergence, Rhat = 1).}
\end{Highlighting}
\end{Shaded}

\hypertarget{answering-our-research-questions}{%
\section{Answering our research questions}\label{answering-our-research-questions}}

Let's return to the research questions we posed initially in Chapoter 1, and again at the beginning of this chapter:

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\item
  What is the average f0 of the whole \emph{population} likely to be?
\item
  Can we set bounds on likely mean f0 values based on the data we collected?
\end{enumerate}

And we can compare the answers provided to this question by our initial model (which contained no priors or information about repeated measured) and final models (which contained information about speakers and appropriate priors).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model}
\DocumentationTok{\#\#  Family: gaussian }
\DocumentationTok{\#\#   Links: mu = identity; sigma = identity }
\DocumentationTok{\#\# Formula: f0 \textasciitilde{} 1 }
\DocumentationTok{\#\#    Data: w (Number of observations: 576) }
\DocumentationTok{\#\# Samples: 1 chains, each with iter = 2000; warmup = 1000; thin = 1;}
\DocumentationTok{\#\#          total post{-}warmup samples = 1000}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Population{-}Level Effects: }
\DocumentationTok{\#\#           Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# Intercept   220.40      0.97   218.33   222.30 1.00      851      557}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Family Specific Parameters: }
\DocumentationTok{\#\#       Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sigma    23.24      0.69    21.99    24.61 1.00      653      550}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Samples were drawn using sampling(NUTS). For each parameter, Bulk\_ESS}
\DocumentationTok{\#\# and Tail\_ESS are effective sample size measures, and Rhat is the potential}
\DocumentationTok{\#\# scale reduction factor on split chains (at convergence, Rhat = 1).}

\NormalTok{multilevel\_priors}
\DocumentationTok{\#\#  Family: gaussian }
\DocumentationTok{\#\#   Links: mu = identity; sigma = identity }
\DocumentationTok{\#\# Formula: f0 \textasciitilde{} 1 + (1 | uspeaker) }
\DocumentationTok{\#\#    Data: w (Number of observations: 576) }
\DocumentationTok{\#\# Samples: 4 chains, each with iter = 11000; warmup = 1000; thin = 10;}
\DocumentationTok{\#\#          total post{-}warmup samples = 4000}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Group{-}Level Effects: }
\DocumentationTok{\#\# \textasciitilde{}uspeaker (Number of levels: 48) }
\DocumentationTok{\#\#               Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sd(Intercept)    20.19      2.24    16.29    25.06 1.00     3114     3663}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Population{-}Level Effects: }
\DocumentationTok{\#\#           Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# Intercept   220.42      2.97   214.44   226.38 1.00     1796     2841}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Family Specific Parameters: }
\DocumentationTok{\#\#       Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# sigma    12.54      0.39    11.81    13.34 1.00     3968     3972}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# Samples were drawn using sampling(NUTS). For each parameter, Bulk\_ESS}
\DocumentationTok{\#\# and Tail\_ESS are effective sample size measures, and Rhat is the potential}
\DocumentationTok{\#\# scale reduction factor on split chains (at convergence, Rhat = 1).}
\end{Highlighting}
\end{Shaded}

Our initial model (\texttt{model}) and our final model (\texttt{multilevel\_priors}) agree on what the average f0 is. However, they disagree on a credible interval for that parameter. Our initial model did not specify information about repeated measures. This causes our model to think that it has more independent observations than it does, and so it returns an overly-precise estimate.

Another difference is that the final model has a much smaller \texttt{sigma} parameter (12.5 vs 23.2). This indicates that the error (\(\varepsilon\)) is much smaller in the final model than in the initial model. Keep in mind that `error' is just what your model can't explain. Our final model explains much more and so there is less error. The reduced error is a direct consequence of the fact that the final model splits the variation in the data into between-speaker and within-speaker components (i.e., \(\sigma_{total}=\sigma_{speaker}+\sigma_{error}\)), estimating the between-speaker variation (\(\sigma_{speaker}\)) to be about 20 Hz. Since \(\sigma_{total}\) is a fixed value (given the data), obviously the larger your between-speaker variation is (\(\sigma_{speaker}\)), the smaller your random error ((\(\sigma_{error}\))) \emph{must} be.

Usually, when I report parameters I provide the mean and standard deviations of the posterior distribution, in addition to the bounds of the 95\% credible interval of the parameter. Based on the result of our final model, I think a thorough description of the general properties of our data might go something like:

\begin{quote}
"Based on our model the average f0 produced by adult females in Michigan is likely to be 220 Hz (s.d. = 2.97, 95\% CI = 214.4, 226.4). However, consistent between-speaker variation averages about 20 Hz (s.d. = 2.24, 95\% CI = 16.29, 25.06), meaning that we can expect the average f0 produced by individuals to deviate substantially from 220 Hz. Finally, the standard deviation of production error was about 12.5 Hz (s.d. = 0.39, 95\% CI = 11.81, 13.34) indicating that the amount of random within-speaker variation in production is about half the magnitude of the systematic between-speaker differences in f0.
\end{quote}

I'm again including the speaker boxplots below because I think this image basically presents the same information as the paragraph above, but in visual form. In general, any data relationship or result can be presented in a figure, and the relationships presented in a figure can also be expressed as a mathematical model.

When you are thinking about the relationships in your data, or that you expect in your data, its a good idea to think: what kind of picture could illustrate this relationship? Conversely, if you see a figure of your results that you feel really expresses something interesting about your data you should think, how can these relationships be represented in a model?

\begin{figure}
\centering
\includegraphics{02_files/figure-latex/F2-7-1.pdf}
\caption{\label{fig:F2-7}Speaker-specific boxplots for the f0 data.}
\end{figure}

\hypertarget{simulating-data-using-our-model-parameters}{%
\section{Simulating data using our model parameters}\label{simulating-data-using-our-model-parameters}}

One way to think about what all these numbers mean is to simulate data that has the same characteristics, and build fake data from the individual component parts. The code chunk below does exactly this for the data we have been discussing thus far.

First, there is an intercept equal to 220.4 Hz. Then, I create effects representing 48 simulated `female talkers' from a population just like our observed population. These effects are stored in a vector called \texttt{alpha\_speaker}, and they represent the values of \(\alpha_{speaker}\) for our different speakers. These speaker effects come from a population with a mean of 0 and a standard deviation (\(\sigma_{speaker}\)) equal to 20.4 (like our data). Each of these simulated speakers produces 12 productions, and so we need a \texttt{speakers} vector with values that repeat 12 times each to index the \texttt{alpha\_speaker} vector containing the effects.

I also draw our error, \(\varepsilon\). This error comes from a distribution with a mean of 0 and a standard deviation equal to \(\sigma_{error}\). It's important to note that the error is just 48x12 random draws from this population. There is no distinction between one person's productions and another when it comes to the error. If there were, this would indicate differences in sigma between speakers! Our model assumes a single error population for all speakers (but it doesn't \emph{have} to be this way).

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# don\textquotesingle{}t run this line if you want a new simulated dataset. }
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{5}\NormalTok{)}
\DocumentationTok{\#\# this is the value of our intercept}
\NormalTok{Intercept }\OtherTok{=} \FloatTok{220.4}
\DocumentationTok{\#\# this is a vector of 48 speaker effects}
\NormalTok{alpha\_speaker }\OtherTok{=} \FunctionTok{rnorm}\NormalTok{ (}\DecValTok{48}\NormalTok{, }\DecValTok{0}\NormalTok{, }\FloatTok{20.2}\NormalTok{)}
\DocumentationTok{\#\# this is a vector indicating which speaker produced which utterance}
\NormalTok{speaker }\OtherTok{=} \FunctionTok{rep}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{:}\DecValTok{48}\NormalTok{, }\AttributeTok{each =} \DecValTok{12}\NormalTok{)}
\DocumentationTok{\#\# this vector contains the error}
\NormalTok{epsilon }\OtherTok{=} \FunctionTok{rnorm}\NormalTok{ (}\DecValTok{48} \SpecialCharTok{*} \DecValTok{12}\NormalTok{, }\DecValTok{0}\NormalTok{, }\FloatTok{12.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

After creating our components, we add the Intercept, speaker deflections and random error to make our fake `replicated' data. Since this data has the same statistical properties as our real data, it should look a lot like it.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# the sum of an intercept, speaker deflections and random error makes our fake data}
\NormalTok{f0\_rep }\OtherTok{=}\NormalTok{ Intercept }\SpecialCharTok{+}\NormalTok{ alpha\_speaker[speaker] }\SpecialCharTok{+}\NormalTok{ epsilon}
\end{Highlighting}
\end{Shaded}

Below I compare the results of our simulation to our real data. If you didn't have a clear impression of what the data looked like, I doubt you could tell which is the real data. This tells us our model is a good reflection of the data!

\begin{figure}
\centering
\includegraphics{02_files/figure-latex/F2-8-1.pdf}
\caption{\label{fig:F2-8}Comparison of real and simulated f0 production data.}
\end{figure}

Below I make two datasets that are `incomplete' with respect to the variation in our data. The first contains the intercept and noise only, the second contains the intercept and speaker effects only.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# this fake data is missing between speaker variation}
\NormalTok{f0\_rep\_1 }\OtherTok{=}\NormalTok{ Intercept }\SpecialCharTok{+}\NormalTok{ epsilon}

\CommentTok{\# this fake data is missing within speaker variation}
\NormalTok{f0\_rep\_2 }\OtherTok{=}\NormalTok{ Intercept }\SpecialCharTok{+}\NormalTok{ alpha\_speaker[speaker]}
\end{Highlighting}
\end{Shaded}

In the figure below, I compare these `incomplete' datasets to the full simulated data. The top row contains only error (\(\varepsilon, \sigma_{error}\)). As a result, f0 varies around the intercept, but there is no speaker to speaker variation. This is what that data would look like if there is no random variation in means across subjects.

However, notice that each little box is not centered at 0. Although the error distribution is centered at 0, the small number of errors added to the speaker mean are \textbf{extremely} unlikely to add up to exactly 0. So, error contributes some unknown amount to each speaker's apparent average. This makes estimations of the \emph{real} speaker effects impossible in practice.

In the middle plot, the figure shows only between-speaker variation (\(\alpha_{speaker}, \sigma_{speaker}\)) but no within-speaker variation (i.e., no noise/error). Now we see that speakers vary from the intercept, but this representation does not show the fact that speakers also vary relative to their own average.

The final plot is the combination of the variation in the top two figures. The final plot shows the simulated data: the sum of the intercept, the within speaker variation and the between-speaker variation reflected in the values of the speaker intercepts.

\begin{figure}

{\centering \includegraphics{02_files/figure-latex/F2-9-1} 

}

\caption{(top) Simulated error variation around the intercept. (middle) Simulated between-speaker variation, but no production error. (bottom) Simulated data containing both within and between-speaker variation in f0.}\label{fig:F2-9}
\end{figure}

\hypertarget{frequentist-corner}{%
\section{Frequentist corner}\label{frequentist-corner}}

We're going to compare the output of \texttt{brms} to some more `traditional' approaches. I'm not going to talk about the traditional models in any detail, the focus of this section is simply to highlight the similarities between different approaches, and to point out where to find equivalent information in the different models. As a result, this section will mostly be useful for people familiar with the traditional approaches.

\hypertarget{bayesian-multilevel-modesl-vs.-lmer}{%
\subsection{Bayesian multilevel modesl vs.~lmer}\label{bayesian-multilevel-modesl-vs.-lmer}}

First, we will compare the output of our multilevel Bayesian modesl to the output of the \texttt{lmer} (``linear mixed-effects regression'') function, a very popular function for fitting multilevel models in the \texttt{lme4} R package.

Below we fit a model just like our \texttt{multilevel\_priors} model. Note that the model syntax is identical and that, actually, the whole function call is quite similar to how we would fit the model using \texttt{brm}. This is a good thing, it means that much of the material we use in this book can also be used to work with the \texttt{lmer} function, should you find this more convenient.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{ (lme4)}

\FunctionTok{set.seed}\NormalTok{ (}\DecValTok{1}\NormalTok{)}
\NormalTok{lmer\_model }\OtherTok{=} \FunctionTok{lmer}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{speaker), }\AttributeTok{data =}\NormalTok{ w)}
\end{Highlighting}
\end{Shaded}

Below I've annotated the print statements for the equivalent \texttt{lmer} and \texttt{brm} models, and provide explanations for each section below.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# print model summary}
\FunctionTok{summary}\NormalTok{ (lmer\_model)}

\DocumentationTok{\#\# (1) Linear mixed model fit by REML [\textquotesingle{}lmerMod\textquotesingle{}]}
\DocumentationTok{\#\# (1) Formula: f0 \textasciitilde{} (1 | speaker)}
\DocumentationTok{\#\# (1) Data: w}
\DocumentationTok{\#\# (1) }
\DocumentationTok{\#\# (1) REML criterion at convergence: 4705.8}
\DocumentationTok{\#\# (1)}
\DocumentationTok{\#\# (1) Scaled residuals: }
\DocumentationTok{\#\# (1)     Min      1Q  Median      3Q     Max }
\DocumentationTok{\#\# (1) {-}4.3792 {-}0.5962 {-}0.1005  0.4771  3.9273 }
\DocumentationTok{\#\#  }
\DocumentationTok{\#\#     Random effects:}
\DocumentationTok{\#\#      Groups   Name        Variance Std.Dev.}
\DocumentationTok{\#\# (2)  speaker  (Intercept) 389.9    19.75   }
\DocumentationTok{\#\# (3)  Residual             156.8    12.52   }
\DocumentationTok{\#\#     Number of obs: 576, groups:  speaker, 48}
\DocumentationTok{\#\#  }
\DocumentationTok{\#\#     Fixed effects:}
\DocumentationTok{\#\#                 Estimate Std. Error t value}
\DocumentationTok{\#\# (4) (Intercept)  220.401      2.897   76.07}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{multilevel\_priors}

\DocumentationTok{\#\# (1)  Family: gaussian }
\DocumentationTok{\#\# (1)   Links: mu = identity; sigma = identity }
\DocumentationTok{\#\# (1) Formula: f0 \textasciitilde{} 1 + (1 | speaker) }
\DocumentationTok{\#\# (1)    Data: w (Number of observations: 576) }
\DocumentationTok{\#\# (1) Samples: 4 chains, each with iter = 11000; warmup = 1000; thin = 10;}
\DocumentationTok{\#\# (1)          total post{-}warmup samples = 4000}
\DocumentationTok{\#\#  }
\DocumentationTok{\#\#     Group{-}Level Effects: }
\DocumentationTok{\#\# (2) \textasciitilde{}speaker (Number of levels: 48) }
\DocumentationTok{\#\# (2)               Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# (2) sd(Intercept)    20.32      2.23    16.44    25.32 1.00     2777     3254}
\DocumentationTok{\#\#  }
\DocumentationTok{\#\#     Population{-}Level Effects: }
\DocumentationTok{\#\#               Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# (4) Intercept   220.38      3.00   214.55   226.18 1.00     1639     2497}
\DocumentationTok{\#\#  }
\DocumentationTok{\#\# (3) Family Specific Parameters: }
\DocumentationTok{\#\# (3)        Estimate Est.Error l{-}95\% CI u{-}95\% CI Rhat Bulk\_ESS Tail\_ESS}
\DocumentationTok{\#\# (3) sigma    12.55      0.38    11.83    13.32 1.00     3963     3892}
\DocumentationTok{\#\# }
\DocumentationTok{\#\# (5) Samples were drawn using sampling(NUTS). For each parameter, Bulk\_ESS}
\DocumentationTok{\#\# (5) and Tail\_ESS are effective sample size measures, and Rhat is the potential}
\DocumentationTok{\#\# (5) scale reduction factor on split chains (at convergence, Rhat = 1).}
\end{Highlighting}
\end{Shaded}

Section (1) contains basic information about data and model structure, and is unique to each function. Generally, you won't pay much attention to this section when you use either function, but it does contain useful basic information about your model.

Section (2) in the \texttt{lmer} output presents the variance (389.9) and standard deviation (19.75) of the speaker effects (\(\alpha_{[speaker]}\)). Notice that in the equivalent section, \texttt{brm} gives you a mean (20.32) of a very similar values. However, unlike \texttt{lmer} which only returns what are called `point estimates', \texttt{brm} also gives you a credible interval around this parameter estimate. So, only \texttt{brm} tells you about a range of believable values, in addition to telling you the \emph{most} believable value.

Section (3) in \texttt{lmer} presents the variance (156.8) and standard deviation (12.52) of the \texttt{Residual}, which is what is calls the random error. In section (2) in the \texttt{brms} output we that the error is called \texttt{sigma}, although the estimate is about the same (12.55). Just as with the between-speaker variation about, \texttt{brm} returns an interval for this parameter while \texttt{lmer} returns only a point estimate.

In section (4) \texttt{lmer} and \texttt{brm} presents the model intercept. We see that the \texttt{Std.\ Error} estimate provided by \texttt{lmer} (2.897) corresponds closely to the standard deviation of the posterior distribution of the intercept parameter provided by \texttt{brm} (3.00). In addition, \texttt{brm} provides an interval around the intercept whereas \texttt{lmer} does not. Finally, in section (5) \texttt{brm} presnts some boilerplate that will look almost the same every time you fit a model.

In general, we see that \texttt{lmer} provides a subset of the information provided by \texttt{brm}, and that the two approaches provide basically the same values for estimates. This is because in both cases, results are being dominated by the likelihoods of different parameters. Although iit is to be expectem it is still reassuring, we woulnd't want there to be huge differences in our results just by being `Bayesian'.

\hypertarget{bayesian-multilevel-modesl-vs.-the-one-sample-t-test}{%
\subsection{Bayesian multilevel modesl vs.~the one-sample t-test}\label{bayesian-multilevel-modesl-vs.-the-one-sample-t-test}}

We can fit a one-sample t-test to our f0 vector.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{ (w}\SpecialCharTok{$}\NormalTok{f0)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  w$f0
## t = 227.8, df = 575, p-value < 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  218.5007 222.3014
## sample estimates:
## mean of x 
##   220.401
\end{verbatim}

This usage is incorrect however, since this test requires that all the observations be independent from each other. Since we have 12 samples per speaker, these are not independent of each other. Notice however that the interval provided around the mean (\texttt{95\ percent\ confidence\ interval:\ 218.5007\ 222.3014}) corresponds very well to the interval around the intercept provided by our initial model above (\texttt{218.33\ \ \ 222.30}). The reason they align so well is because they both (inappropriately) treated all our observations as independent.

Below we use the one-sample t-test appropriately. We find the average for each speaker, and then use only those 48 values in our test.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{speaker\_means }\OtherTok{=} \FunctionTok{aggregate}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{FUN =}\NormalTok{ mean) }
\FunctionTok{t.test}\NormalTok{ (speaker\_means}\SpecialCharTok{$}\NormalTok{f0)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  speaker_means$f0
## t = 76.068, df = 47, p-value < 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  214.5722 226.2299
## sample estimates:
## mean of x 
##   220.401
\end{verbatim}

Now the interval provided closely resembles that of our final, \texttt{multilevel\_priors} model (\texttt{214.55\ \ \ 226.18}). So, if all we care about is estimating a mean and credible interval around the mean, then a one-sample t-test will help us do that. However, our \texttt{multilevel\_priors} clearly provides us with substantially more information than is returned by the t-test.

\hypertarget{exercises-1}{%
\section{Exercises}\label{exercises-1}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\item
  Use the code below to fit the final model we considered to the f0s produced by another group of speakers. See if you can get all of the same information out of the model that we considered above. Make a plot of this new data using the plot code provided.
\item
  See if you can use the information from your new data to update the simulated data created above. This entails finding the intercept, within-speaker, and between-speaker variation estimates in your new data and using this to generate a new batch of fake/replicated data.
\item
  Use the code below to fit the model below to your own data. Remember, this data should come from a single group of speakers/participants who each produce one or more data points. You will need to change \texttt{f0} and \texttt{speaker} in the model below to match the names of the columns containing this information in your data. You may also need to change the priors based on the ranges of your variables. If in doubt, you can just set all the priors to have means of 0 and standard deviations of 10,000 for now.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Get data from course website}
\NormalTok{url1 }\OtherTok{=} \StringTok{"https://raw.githubusercontent.com/santiagobarreda"}
\NormalTok{url2 }\OtherTok{=} \StringTok{"/stats{-}class/master/data/h95\_vowel\_data.csv"}
\NormalTok{h95 }\OtherTok{=} \FunctionTok{read.csv}\NormalTok{ (}\FunctionTok{url}\NormalTok{(}\FunctionTok{paste0}\NormalTok{ (url1, url2)))}

\CommentTok{\# uncomment only one of the options below}

\CommentTok{\# select women only}
\CommentTok{\# f0\_data = h95[h95$group == \textquotesingle{}w\textquotesingle{},]}

\CommentTok{\# select boys only}
\CommentTok{\# f0\_data = h95[h95$group == \textquotesingle{}b\textquotesingle{},]}

\CommentTok{\# select girls only}
\CommentTok{\# f0\_data = h95[h95$group == \textquotesingle{}g\textquotesingle{},]}

\CommentTok{\# select men only}
\CommentTok{\# f0\_data = h95[h95$group == \textquotesingle{}m\textquotesingle{},]}

\NormalTok{exercise\_model }\OtherTok{=}  
  \FunctionTok{brm}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{speaker), }\AttributeTok{data =}\NormalTok{ f0\_data, }\AttributeTok{chains =} \DecValTok{4}\NormalTok{, }\AttributeTok{cores =} \DecValTok{4}\NormalTok{,}
       \AttributeTok{warmup =} \DecValTok{1000}\NormalTok{, }\AttributeTok{iter =} \DecValTok{11000}\NormalTok{, }\AttributeTok{thin =} \DecValTok{10}\NormalTok{,}
       \AttributeTok{prior =} \FunctionTok{c}\NormalTok{(}\FunctionTok{set\_prior}\NormalTok{(}\StringTok{"student\_t(3, 220, 100)"}\NormalTok{, }\AttributeTok{class =} \StringTok{"Intercept"}\NormalTok{),}
                 \FunctionTok{set\_prior}\NormalTok{(}\StringTok{"student\_t(3, 0, 100)"}\NormalTok{, }\AttributeTok{class =} \StringTok{"sd"}\NormalTok{),}
                 \FunctionTok{set\_prior}\NormalTok{(}\StringTok{"student\_t(3, 0, 100)"}\NormalTok{, }\AttributeTok{class =} \StringTok{"sigma"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\hypertarget{plot-code-1}{%
\section{Plot Code}\label{plot-code-1}}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\DocumentationTok{\#\#\# Figure 2.1}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}

\FunctionTok{par}\NormalTok{ (}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}

\FunctionTok{plot}\NormalTok{ (samples[,}\DecValTok{1}\NormalTok{], }\AttributeTok{xlab =} \StringTok{\textquotesingle{}Sample number\textquotesingle{}}\NormalTok{,}\AttributeTok{ylab =} \StringTok{\textquotesingle{}f0\textquotesingle{}}\NormalTok{,}\AttributeTok{col=}\NormalTok{teal,}\AttributeTok{pch=}\DecValTok{16}\NormalTok{)}

\FunctionTok{hist}\NormalTok{ (samples[,}\DecValTok{1}\NormalTok{], }\AttributeTok{freq =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{breaks =} \DecValTok{20}\NormalTok{,}\AttributeTok{main=}\StringTok{\textquotesingle{}\textquotesingle{}}\NormalTok{,}\AttributeTok{xlab=}\StringTok{\textquotesingle{}f0\textquotesingle{}}\NormalTok{,}\AttributeTok{col=}\NormalTok{maroon)}

\FunctionTok{curve}\NormalTok{ (}\FunctionTok{dnorm}\NormalTok{ (x, }\FunctionTok{mean}\NormalTok{ (f0), }\FunctionTok{sd}\NormalTok{ (f0) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{ (}\FunctionTok{length}\NormalTok{ (f0) )), }\AttributeTok{add =} \ConstantTok{TRUE}\NormalTok{,}
       \AttributeTok{lwd =} \DecValTok{4}\NormalTok{, }\AttributeTok{col =}\NormalTok{ yellow)}

\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\DocumentationTok{\#\#\# Figure 2.2}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}

\FunctionTok{par}\NormalTok{ (}\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{)); }\FunctionTok{layout}\NormalTok{ (}\AttributeTok{mat =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{), }\AttributeTok{heights =} \FunctionTok{c}\NormalTok{(.}\DecValTok{3}\NormalTok{,.}\DecValTok{7}\NormalTok{))}

\FunctionTok{boxplot}\NormalTok{ (f0, }\AttributeTok{main =} \StringTok{"Overall Boxplot"}\NormalTok{, }\AttributeTok{col=}\StringTok{"lavender"}\NormalTok{, }
         \AttributeTok{horizontal =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{140}\NormalTok{,}\DecValTok{320}\NormalTok{)) }

\FunctionTok{boxplot}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{main =} \StringTok{"Speaker Boxplots"}\NormalTok{, }\AttributeTok{col=}\FunctionTok{c}\NormalTok{(yellow,coral,}
\NormalTok{         deepgreen,teal), }\AttributeTok{horizontal =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{140}\NormalTok{,}\DecValTok{320}\NormalTok{)) }

\FunctionTok{abline}\NormalTok{ (}\AttributeTok{h =} \FloatTok{220.4}\NormalTok{,}\AttributeTok{lty=}\DecValTok{3}\NormalTok{,}\AttributeTok{col=}\StringTok{\textquotesingle{}grey\textquotesingle{}}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{)}

\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\DocumentationTok{\#\#\# Figure 2.3}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}

\FunctionTok{par}\NormalTok{ (}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\NormalTok{graphics}\SpecialCharTok{::}\FunctionTok{layout}\NormalTok{ (}\AttributeTok{mat =} \FunctionTok{t}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{)),}\AttributeTok{widths =} \FunctionTok{c}\NormalTok{(.}\DecValTok{25}\NormalTok{,.}\DecValTok{5}\NormalTok{,.}\DecValTok{25}\NormalTok{))}
\FunctionTok{hist}\NormalTok{ (w}\SpecialCharTok{$}\NormalTok{f0[w}\SpecialCharTok{$}\NormalTok{speaker }\SpecialCharTok{==} \DecValTok{107}\NormalTok{], }\AttributeTok{main =} \StringTok{"Histogram of speaker 107"}\NormalTok{,}
      \AttributeTok{xlim =} \FunctionTok{c}\NormalTok{(}\DecValTok{140}\NormalTok{, }\DecValTok{310}\NormalTok{), }\AttributeTok{freq =} \ConstantTok{FALSE}\NormalTok{,}\AttributeTok{col=}\NormalTok{yellow)}
\FunctionTok{boxplot}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{main =} \StringTok{"Speaker Boxplots"}\NormalTok{,}\AttributeTok{col=}\NormalTok{deepgreen, }\AttributeTok{horizontal=}\ConstantTok{TRUE}\NormalTok{,}\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{140}\NormalTok{, }\DecValTok{310}\NormalTok{) )}
\FunctionTok{abline}\NormalTok{ (}\AttributeTok{h =} \DecValTok{16}\NormalTok{,}\AttributeTok{lty=}\DecValTok{3}\NormalTok{)}
\FunctionTok{hist}\NormalTok{ (}\FunctionTok{tapply}\NormalTok{ (w}\SpecialCharTok{$}\NormalTok{f0, w}\SpecialCharTok{$}\NormalTok{speaker, mean), }\AttributeTok{main =} \StringTok{"Histogram of speaker f0 means"}\NormalTok{,}\AttributeTok{xlim =} \FunctionTok{c}\NormalTok{(}\DecValTok{140}\NormalTok{, }\DecValTok{310}\NormalTok{), }\AttributeTok{freq =} \ConstantTok{FALSE}\NormalTok{,}
      \AttributeTok{col=}\DecValTok{4}\NormalTok{)}


\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\DocumentationTok{\#\#\# Figure 2.4}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}

\FunctionTok{par}\NormalTok{ (}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\FunctionTok{boxplot}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{main =} \StringTok{"Speaker Boxplots"}\NormalTok{,}\AttributeTok{col=}\NormalTok{cols[}\DecValTok{3}\SpecialCharTok{:}\DecValTok{6}\NormalTok{]) }
\FunctionTok{abline}\NormalTok{ (}\AttributeTok{h =} \FloatTok{220.4}\NormalTok{,}\AttributeTok{lty=}\DecValTok{3}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{3}\NormalTok{)}

\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\DocumentationTok{\#\#\# Figure 2.5}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}

\FunctionTok{par}\NormalTok{ (}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{))}

\FunctionTok{boxplot}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{main =} \StringTok{"Speaker Boxplots"}\NormalTok{,}\AttributeTok{col=}\FunctionTok{c}\NormalTok{(yellow,coral,}
\NormalTok{         deepgreen,teal)) }

\FunctionTok{abline}\NormalTok{ (}\AttributeTok{h =} \FloatTok{220.4}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{3}\NormalTok{,}\AttributeTok{lty=}\DecValTok{3}\NormalTok{)}

\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\DocumentationTok{\#\#\# Figure 2.6}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}

\CommentTok{\# get t density}
\NormalTok{x1 }\OtherTok{=} \FunctionTok{seq}\NormalTok{ (}\SpecialCharTok{{-}}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,.}\DecValTok{1}\NormalTok{)}
\NormalTok{y1 }\OtherTok{=} \FunctionTok{dt}\NormalTok{ (x1, }\DecValTok{3}\NormalTok{); y1 }\OtherTok{=}\NormalTok{ y1 }\SpecialCharTok{/} \FunctionTok{max}\NormalTok{ (y1) }\SpecialCharTok{/} \DecValTok{100}
\NormalTok{x2 }\OtherTok{=} \DecValTok{220}\SpecialCharTok{+}\NormalTok{(x1}\SpecialCharTok{*}\DecValTok{100}\NormalTok{)}
\NormalTok{y2 }\OtherTok{=} \FunctionTok{dnorm}\NormalTok{ (x2, }\DecValTok{220}\NormalTok{, }\DecValTok{100}\NormalTok{); y2 }\OtherTok{=}\NormalTok{ y2 }\SpecialCharTok{/} \FunctionTok{max}\NormalTok{ (y2) }\SpecialCharTok{/} \DecValTok{100}

\FunctionTok{par}\NormalTok{ (}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\DocumentationTok{\#\# plot t}
\FunctionTok{plot}\NormalTok{ (x2, y1, }\AttributeTok{type =} \StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{, }\AttributeTok{ylab =} \StringTok{\textquotesingle{}Density\textquotesingle{}}\NormalTok{, }\AttributeTok{xlab =} \StringTok{\textquotesingle{}f0\textquotesingle{}}\NormalTok{, }\AttributeTok{col =} \DecValTok{4}\NormalTok{, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{0.018}\NormalTok{))}
\DocumentationTok{\#\# compare to equivalent normal}
\FunctionTok{lines}\NormalTok{ (x2, y2, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{,}\AttributeTok{col=}\DecValTok{2}\NormalTok{)}
\FunctionTok{hist}\NormalTok{ (f0, }\AttributeTok{add =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{freq =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{col =}\NormalTok{ deepgreen)}


\DocumentationTok{\#\# plot prior for standard deviations}
\NormalTok{x3 }\OtherTok{=}\NormalTok{ x2 }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{ (x2)}
\NormalTok{y3 }\OtherTok{=} \FunctionTok{dt}\NormalTok{ (x1, }\DecValTok{3}\NormalTok{); y3 }\OtherTok{=}\NormalTok{ y3 }\SpecialCharTok{/} \FunctionTok{max}\NormalTok{ (y3) }\SpecialCharTok{/} \DecValTok{20}
\FunctionTok{plot}\NormalTok{ (x3[x3}\SpecialCharTok{\textgreater{}}\DecValTok{0}\NormalTok{], y3[x3}\SpecialCharTok{\textgreater{}}\DecValTok{0}\NormalTok{], }\AttributeTok{type =} \StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{, }\AttributeTok{ylab =} \StringTok{\textquotesingle{}Density\textquotesingle{}}\NormalTok{, }
      \AttributeTok{xlab =} \StringTok{\textquotesingle{}f0\textquotesingle{}}\NormalTok{, }\AttributeTok{col =} \DecValTok{4}\NormalTok{)}
\FunctionTok{hist}\NormalTok{ (}\FunctionTok{abs}\NormalTok{ (f0 }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{ (f0)), }\AttributeTok{add =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{freq =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{col =}\NormalTok{ yellow)}

\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\DocumentationTok{\#\#\# Figure 2.7}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}

\FunctionTok{par}\NormalTok{ (}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{))}

\FunctionTok{boxplot}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{main =} \StringTok{"Speaker Boxplots"}\NormalTok{,}\AttributeTok{col=}\FunctionTok{c}\NormalTok{(yellow,coral,}
\NormalTok{         deepgreen,teal)) }

\FunctionTok{abline}\NormalTok{ (}\AttributeTok{h =} \FloatTok{220.4}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{3}\NormalTok{,}\AttributeTok{lty=}\DecValTok{3}\NormalTok{)}

\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\DocumentationTok{\#\#\# Figure 2.8}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}

\FunctionTok{par}\NormalTok{ (}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{), }\AttributeTok{oma =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\FunctionTok{boxplot}\NormalTok{ (f0\_rep }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{140}\NormalTok{,}\DecValTok{320}\NormalTok{), }\AttributeTok{xaxt=}\StringTok{\textquotesingle{}n\textquotesingle{}}\NormalTok{,}\AttributeTok{xlab=}\StringTok{\textquotesingle{}\textquotesingle{}}\NormalTok{,}
         \AttributeTok{col=}\FunctionTok{c}\NormalTok{(yellow,coral,deepgreen,teal))}
\FunctionTok{abline}\NormalTok{ (}\AttributeTok{h =} \FloatTok{220.4}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{3}\NormalTok{,}\AttributeTok{lty=}\DecValTok{3}\NormalTok{)}
\FunctionTok{boxplot}\NormalTok{ (f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{data =}\NormalTok{ w, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{140}\NormalTok{,}\DecValTok{320}\NormalTok{), }\AttributeTok{xaxt=}\StringTok{\textquotesingle{}n\textquotesingle{}}\NormalTok{,}\AttributeTok{xlab=}\StringTok{\textquotesingle{}\textquotesingle{}}\NormalTok{,}
         \AttributeTok{col=}\FunctionTok{c}\NormalTok{(yellow,coral,deepgreen,teal))}
\FunctionTok{abline}\NormalTok{ (}\AttributeTok{h =} \FloatTok{220.4}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{3}\NormalTok{,}\AttributeTok{lty=}\DecValTok{3}\NormalTok{)}
\FunctionTok{mtext}\NormalTok{ (}\AttributeTok{text =} \StringTok{"f0"}\NormalTok{, }\AttributeTok{side=}\DecValTok{2}\NormalTok{, }\AttributeTok{outer=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{line =} \DecValTok{1}\NormalTok{)}

\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\DocumentationTok{\#\#\# Figure 2.9}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}

\FunctionTok{par}\NormalTok{ (}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{1}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{), }\AttributeTok{oma =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\FunctionTok{boxplot}\NormalTok{ (f0\_rep\_1 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{140}\NormalTok{,}\DecValTok{320}\NormalTok{),}\AttributeTok{xaxt=}\StringTok{\textquotesingle{}n\textquotesingle{}}\NormalTok{,}
         \AttributeTok{col=}\FunctionTok{c}\NormalTok{(yellow,coral,deepgreen,teal))}
\FunctionTok{text}\NormalTok{ (}\DecValTok{5}\NormalTok{, }\DecValTok{290}\NormalTok{, }\AttributeTok{label =} \FunctionTok{expression}\NormalTok{(}\FunctionTok{paste}\NormalTok{(sigma[}\StringTok{"error"}\NormalTok{])), }\AttributeTok{cex =} \FloatTok{1.5}\NormalTok{)}
\FunctionTok{abline}\NormalTok{ (}\AttributeTok{h=}\DecValTok{220}\NormalTok{,}\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}

\FunctionTok{boxplot}\NormalTok{ (f0\_rep\_2 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{140}\NormalTok{,}\DecValTok{320}\NormalTok{),}\AttributeTok{xaxt=}\StringTok{\textquotesingle{}n\textquotesingle{}}\NormalTok{,}
         \AttributeTok{col=}\FunctionTok{c}\NormalTok{(yellow,coral,deepgreen,teal))}
\FunctionTok{abline}\NormalTok{ (}\AttributeTok{h=}\DecValTok{220}\NormalTok{,}\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}
\FunctionTok{text}\NormalTok{ (}\DecValTok{5}\NormalTok{, }\DecValTok{290}\NormalTok{, }\AttributeTok{label =} \FunctionTok{expression}\NormalTok{(}\FunctionTok{paste}\NormalTok{(sigma[}\StringTok{"speaker"}\NormalTok{])), }\AttributeTok{cex =} \FloatTok{1.5}\NormalTok{)}

\FunctionTok{boxplot}\NormalTok{ (f0\_rep }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speaker, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{140}\NormalTok{,}\DecValTok{320}\NormalTok{),}\AttributeTok{xaxt=}\StringTok{\textquotesingle{}n\textquotesingle{}}\NormalTok{,}
         \AttributeTok{col=}\FunctionTok{c}\NormalTok{(yellow,coral,deepgreen,teal)  )}
\FunctionTok{abline}\NormalTok{ (}\AttributeTok{h=}\DecValTok{220}\NormalTok{,}\AttributeTok{lty=}\DecValTok{2}\NormalTok{)}
\FunctionTok{text}\NormalTok{ (}\DecValTok{5}\NormalTok{, }\DecValTok{290}\NormalTok{, }\AttributeTok{label =} \FunctionTok{expression}\NormalTok{(}\FunctionTok{paste}\NormalTok{(sigma[}\StringTok{"error"}\NormalTok{]}\SpecialCharTok{+}\NormalTok{sigma[}\StringTok{"speaker"}\NormalTok{])), }\AttributeTok{cex =} \FloatTok{1.5}\NormalTok{)}

\FunctionTok{mtext}\NormalTok{ (}\AttributeTok{side=}\DecValTok{2}\NormalTok{,}\AttributeTok{text=}\StringTok{"f0"}\NormalTok{, }\AttributeTok{outer =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{line=}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{comparing-two-groups-of-observations}{%
\chapter{Comparing two groups of observations}\label{comparing-two-groups-of-observations}}

Placeholder

\hypertarget{data-and-research-questions-2}{%
\section{Data and research questions}\label{data-and-research-questions-2}}

\hypertarget{estimating-the-difference-between-two-means-with-brms}{%
\section{Estimating the difference between two means with `brms'}\label{estimating-the-difference-between-two-means-with-brms}}

\hypertarget{fitting-the-model-1}{%
\subsection{Fitting the model}\label{fitting-the-model-1}}

\hypertarget{interpreting-the-model}{%
\subsection{Interpreting the model}\label{interpreting-the-model}}

\hypertarget{contrasts}{%
\section{Contrasts}\label{contrasts}}

\hypertarget{treatment-coding}{%
\subsection{Treatment coding}\label{treatment-coding}}

\hypertarget{sum-coding}{%
\subsection{Sum coding}\label{sum-coding}}

\hypertarget{comparison-of-sum-and-treatment-coding}{%
\subsection{Comparison of sum and treatment coding}\label{comparison-of-sum-and-treatment-coding}}

\hypertarget{refitting-the-model-with-sum-coding}{%
\section{Refitting the model with sum coding}\label{refitting-the-model-with-sum-coding}}

\hypertarget{fitting-the-model-2}{%
\subsection{Fitting the model}\label{fitting-the-model-2}}

\hypertarget{description-of-the-model-2}{%
\subsection{Description of the model}\label{description-of-the-model-2}}

\hypertarget{interpreting-the-model-1}{%
\subsection{Interpreting the model}\label{interpreting-the-model-1}}

\hypertarget{random-effects}{%
\section{`Random' Effects}\label{random-effects}}

\hypertarget{random-effects-priors-and-pooling}{%
\subsection{Random effects, priors and pooling}\label{random-effects-priors-and-pooling}}

\hypertarget{inspecting-the-random-effects}{%
\subsection{Inspecting the random effects}\label{inspecting-the-random-effects}}

\hypertarget{but-what-does-it-all-mean}{%
\section{But what does it all mean?}\label{but-what-does-it-all-mean}}

\hypertarget{simulating-the-two-group-model}{%
\section{Simulating the two-group model}\label{simulating-the-two-group-model}}

\hypertarget{frequentist-corner-1}{%
\section{Frequentist corner}\label{frequentist-corner-1}}

\hypertarget{lmer-corner}{%
\section{Lmer corner}\label{lmer-corner}}

\hypertarget{exercises-2}{%
\section{Exercises}\label{exercises-2}}

\hypertarget{plot-code-2}{%
\section{Plot Code}\label{plot-code-2}}

\hypertarget{comparing-many-groups}{%
\chapter{Comparing many groups}\label{comparing-many-groups}}

Placeholder

\hypertarget{data-and-research-questions-3}{%
\section{Data and research questions}\label{data-and-research-questions-3}}

\hypertarget{comparing-four-or-any-number-of-groups}{%
\section{Comparing four (or any number of) groups}\label{comparing-four-or-any-number-of-groups}}

\hypertarget{the-model}{%
\subsection{The model}\label{the-model}}

\hypertarget{investigating-many-groups-using-predictors-analysis-of-variance}{%
\section{Investigating many groups using predictors: Analysis of Variance}\label{investigating-many-groups-using-predictors-analysis-of-variance}}

\hypertarget{description-of-the-model-3}{%
\subsection{Description of the model}\label{description-of-the-model-3}}

\hypertarget{fitting-the-model-and-interpreting-the-results}{%
\subsection{Fitting the model and interpreting the results}\label{fitting-the-model-and-interpreting-the-results}}

\hypertarget{investigating-model-fit}{%
\subsection{Investigating model fit}\label{investigating-model-fit}}

\hypertarget{interactions-and-interaction-plots}{%
\section{Interactions and interaction plots}\label{interactions-and-interaction-plots}}

\hypertarget{interactions-in-our-f0-data}{%
\subsection{Interactions in our f0 data}\label{interactions-in-our-f0-data}}

\hypertarget{investigating-interactions-with-a-model}{%
\section{Investigating interactions with a model}\label{investigating-interactions-with-a-model}}

\hypertarget{fitting-the-model-and-interpreting-the-results-1}{%
\subsection{Fitting the model and interpreting the results}\label{fitting-the-model-and-interpreting-the-results-1}}

\hypertarget{assessing-model-fit}{%
\subsection{Assessing model fit}\label{assessing-model-fit}}

\hypertarget{investigating-the-interactions-the-easy-way}{%
\subsection{Investigating the interactions the easy way}\label{investigating-the-interactions-the-easy-way}}

\hypertarget{making-plots}{%
\subsection{Making plots}\label{making-plots}}

\hypertarget{lmer-corner-1}{%
\section{Lmer corner}\label{lmer-corner-1}}

\hypertarget{exercises-3}{%
\section{Exercises}\label{exercises-3}}

\hypertarget{plot-code-3}{%
\section{Plot Code}\label{plot-code-3}}

\hypertarget{including-continuous-predictors-in-our-model}{%
\chapter{Including continuous predictors in our model}\label{including-continuous-predictors-in-our-model}}

Placeholder

\hypertarget{data-and-research-questions-4}{%
\section{Data and research questions}\label{data-and-research-questions-4}}

\hypertarget{continuous-predictors-modeling-variation-along-lines}{%
\section{Continuous predictors: modeling variation along lines}\label{continuous-predictors-modeling-variation-along-lines}}

\hypertarget{models-with-a-single-slope-and-intercept}{%
\section{Models with a single slope and intercept}\label{models-with-a-single-slope-and-intercept}}

\hypertarget{description-of-the-model-4}{%
\subsection{Description of the model}\label{description-of-the-model-4}}

\hypertarget{fitting-the-model-3}{%
\subsection{Fitting the model}\label{fitting-the-model-3}}

\hypertarget{interpreting-the-model-2}{%
\subsection{Interpreting the model}\label{interpreting-the-model-2}}

\hypertarget{centering-predictors}{%
\subsection{Centering predictors}\label{centering-predictors}}

\hypertarget{interactions-in-our-line-parameters}{%
\section{Interactions in our line parameters}\label{interactions-in-our-line-parameters}}

\hypertarget{models-with-group-dependent-intercepts-but-shared-slopes}{%
\section{Models with group-dependent intercepts, but shared slopes}\label{models-with-group-dependent-intercepts-but-shared-slopes}}

\hypertarget{description-of-the-model-5}{%
\subsection{Description of the model}\label{description-of-the-model-5}}

\hypertarget{fitting-the-model-4}{%
\subsection{Fitting the model}\label{fitting-the-model-4}}

\hypertarget{the-effect-of-including-a-slope}{%
\subsection{The effect of including a slope}\label{the-effect-of-including-a-slope}}

\hypertarget{interpreting-group-effects-in-the-presence-of-a-continuous-predictor}{%
\subsection{Interpreting group effects in the presence of a continuous predictor}\label{interpreting-group-effects-in-the-presence-of-a-continuous-predictor}}

\hypertarget{models-with-group-dependent-slopes-and-intercepts}{%
\section{Models with group-dependent slopes and intercepts}\label{models-with-group-dependent-slopes-and-intercepts}}

\hypertarget{description-of-the-model-6}{%
\subsection{Description of the model}\label{description-of-the-model-6}}

\hypertarget{fitting-the-model-5}{%
\subsection{Fitting the model}\label{fitting-the-model-5}}

\hypertarget{interpreting-the-model-3}{%
\subsection{Interpreting the model}\label{interpreting-the-model-3}}

\hypertarget{exercises-4}{%
\section{Exercises}\label{exercises-4}}

\hypertarget{plot-code-4}{%
\section{Plot Code}\label{plot-code-4}}

\hypertarget{random-slopes}{%
\chapter{Random slopes}\label{random-slopes}}

Placeholder

\hypertarget{data-and-research-questions-5}{%
\section{Data and research questions}\label{data-and-research-questions-5}}

\hypertarget{repeated-measures-and-speaker-dependent-parameter-values}{%
\section{Repeated measures and speaker-dependent parameter values}\label{repeated-measures-and-speaker-dependent-parameter-values}}

\hypertarget{description-of-the-model-7}{%
\subsection{Description of the model}\label{description-of-the-model-7}}

\hypertarget{fitting-the-model-6}{%
\subsection{Fitting the model}\label{fitting-the-model-6}}

\hypertarget{interpreting-the-model-4}{%
\subsection{Interpreting the model}\label{interpreting-the-model-4}}

\hypertarget{random-effects-and-the-multivariate-normal-distribution}{%
\section{Random effects and the multivariate normal distribution}\label{random-effects-and-the-multivariate-normal-distribution}}

\hypertarget{random-slopes-1}{%
\section{Random slopes}\label{random-slopes-1}}

\hypertarget{description-of-the-model-8}{%
\subsection{Description of the model}\label{description-of-the-model-8}}

\hypertarget{fitting-the-model-7}{%
\subsection{Fitting the model}\label{fitting-the-model-7}}

\hypertarget{interpreting-the-model-5}{%
\subsection{Interpreting the model}\label{interpreting-the-model-5}}

\hypertarget{more-predictors-and-more-random-slopes}{%
\section{More predictors and more random slopes}\label{more-predictors-and-more-random-slopes}}

\hypertarget{adding-another-random-slope}{%
\subsection{Adding another random slope}\label{adding-another-random-slope}}

\hypertarget{adding-random-factors}{%
\subsection{Adding random factors}\label{adding-random-factors}}

\hypertarget{the-independence-of-continuous-predictors}{%
\subsection{The independence of continuous predictors}\label{the-independence-of-continuous-predictors}}

\hypertarget{answering-our-research-questions-1}{%
\section{Answering our research questions}\label{answering-our-research-questions-1}}

\hypertarget{lmer-corner-2}{%
\section{Lmer corner}\label{lmer-corner-2}}

\hypertarget{exercises-5}{%
\section{Exercises}\label{exercises-5}}

\hypertarget{plot-code-5}{%
\section{Plot Code}\label{plot-code-5}}

\hypertarget{logistic-regression}{%
\chapter{Logistic regression}\label{logistic-regression}}

Placeholder

\hypertarget{data-and-research-questions-6}{%
\section{Data and research questions}\label{data-and-research-questions-6}}

\hypertarget{dichotomous-variables-and-data}{%
\subsection{Dichotomous variables and data}\label{dichotomous-variables-and-data}}

\hypertarget{generalizing-our-linear-models}{%
\section{Generalizing our linear models}\label{generalizing-our-linear-models}}

\hypertarget{link-functions}{%
\subsection{Link functions}\label{link-functions}}

\hypertarget{logits}{%
\subsection{Logits}\label{logits}}

\hypertarget{the-logistic-link-function}{%
\subsection{The logistic link function}\label{the-logistic-link-function}}

\hypertarget{building-intuitions-about-logits}{%
\subsection{Building intuitions about logits}\label{building-intuitions-about-logits}}

\hypertarget{logistic-regression-with-one-predictor}{%
\section{Logistic regression with one predictor}\label{logistic-regression-with-one-predictor}}

\hypertarget{description-of-the-model-9}{%
\subsection{Description of the model}\label{description-of-the-model-9}}

\hypertarget{fitting-the-model-8}{%
\subsection{Fitting the model}\label{fitting-the-model-8}}

\hypertarget{interpreting-the-model-6}{%
\subsection{Interpreting the model}\label{interpreting-the-model-6}}

\hypertarget{answering-our-research-question}{%
\section{Answering our research question}\label{answering-our-research-question}}

\hypertarget{plot-code-6}{%
\section{Plot Code}\label{plot-code-6}}

\hypertarget{bayesian-anova-and-interpreting-complicated-models}{%
\chapter{Bayesian ANOVA and interpreting complicated models}\label{bayesian-anova-and-interpreting-complicated-models}}

Placeholder

\hypertarget{data-and-research-questions-7}{%
\section{Data and research questions}\label{data-and-research-questions-7}}

\hypertarget{the-experiment}{%
\subsection{The experiment}\label{the-experiment}}

\hypertarget{deciding-on-a-model}{%
\section{Deciding on a model}\label{deciding-on-a-model}}

\hypertarget{fitting-the-models}{%
\section{Fitting the models}\label{fitting-the-models}}

\hypertarget{the-maximal-models}{%
\subsection{The `maximal' models}\label{the-maximal-models}}

\hypertarget{fitting-the-final-models-in-lmer-and-brms}{%
\subsection{Fitting the `final' models in lmer and brms}\label{fitting-the-final-models-in-lmer-and-brms}}

\hypertarget{comparing-the-maximal-and-final-models}{%
\section{Comparing the maximal and final models}\label{comparing-the-maximal-and-final-models}}

\hypertarget{bayesian-analysis-of-variance}{%
\section{Bayesian Analysis of Variance}\label{bayesian-analysis-of-variance}}

\hypertarget{getting-the-superpopulation-standard-deviations-from-our-models}{%
\subsection{Getting the superpopulation standard deviations from our models}\label{getting-the-superpopulation-standard-deviations-from-our-models}}

\hypertarget{getting-the-finite-population-standard-deviations-from-our-models}{%
\subsection{Getting the finite-population standard deviations from our models}\label{getting-the-finite-population-standard-deviations-from-our-models}}

\hypertarget{using-the-banova-function}{%
\subsection{\texorpdfstring{Using the \texttt{banova} function}{Using the banova function}}\label{using-the-banova-function}}

\hypertarget{applying-the-banova-function-to-our-gender-perception-model}{%
\subsection{\texorpdfstring{Applying the \texttt{banova} function to our gender perception model}{Applying the banova function to our gender perception model}}\label{applying-the-banova-function-to-our-gender-perception-model}}

\hypertarget{applying-a-bayesian-anova-to-a-more-complicated-model}{%
\section{Applying a Bayesian ANOVA to a more-complicated model}\label{applying-a-bayesian-anova-to-a-more-complicated-model}}

\hypertarget{description-of-the-model-10}{%
\subsection{Description of the model}\label{description-of-the-model-10}}

\hypertarget{fitting-the-model-9}{%
\subsection{Fitting the model}\label{fitting-the-model-9}}

\hypertarget{interpreting-the-model-7}{%
\subsection{Interpreting the model}\label{interpreting-the-model-7}}

\hypertarget{plot-code-7}{%
\section{Plot Code}\label{plot-code-7}}

\hypertarget{multivariate-models-predictive-accuracy-and-handling-outliers}{%
\chapter{Multivariate models, predictive accuracy, and handling outliers}\label{multivariate-models-predictive-accuracy-and-handling-outliers}}

Placeholder

\hypertarget{data-and-research-questions-8}{%
\section{Data and research questions}\label{data-and-research-questions-8}}

\hypertarget{using-multiple-continuous-predictors}{%
\section{Using multiple continuous predictors}\label{using-multiple-continuous-predictors}}

\hypertarget{describing-and-fitting-the-model}{%
\subsection{Describing and fitting the model}\label{describing-and-fitting-the-model}}

\hypertarget{interpreting-the-model-8}{%
\subsection{Interpreting the model}\label{interpreting-the-model-8}}

\hypertarget{considering-predictive-accuracy}{%
\section{Considering predictive accuracy}\label{considering-predictive-accuracy}}

\hypertarget{handling-outliers-t-distributed-errors}{%
\section{Handling outliers: t-distributed errors}\label{handling-outliers-t-distributed-errors}}

\hypertarget{fitting-and-interpreting-the-model}{%
\subsection{Fitting and interpreting the model}\label{fitting-and-interpreting-the-model}}

\hypertarget{plot-code-8}{%
\section{Plot Code}\label{plot-code-8}}

\hypertarget{modeling-standard-deviations}{%
\chapter{Modeling Standard Deviations}\label{modeling-standard-deviations}}

Placeholder

\hypertarget{data}{%
\section{Data}\label{data}}

\hypertarget{modeling-variation-in-the-error}{%
\section{Modeling variation in the error}\label{modeling-variation-in-the-error}}

\hypertarget{fitting-and-interpreting-our-model}{%
\subsection{Fitting and interpreting our model}\label{fitting-and-interpreting-our-model}}

\hypertarget{modeling-group-variation-in-our-random-effects}{%
\section{Modeling group variation in our random effects}\label{modeling-group-variation-in-our-random-effects}}

\hypertarget{fitting-and-interpreting-our-model-1}{%
\subsection{Fitting and interpreting our model}\label{fitting-and-interpreting-our-model-1}}

\hypertarget{two-dimensional-response-surfaces}{%
\subsection{Two-dimensional response surfaces}\label{two-dimensional-response-surfaces}}

\hypertarget{plot-code-9}{%
\section{Plot Code}\label{plot-code-9}}

\end{document}
