<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Comparing two groups of observations | A Quick Introduction to Multilevel Bayesian Models for Linguistic Researchers</title>
  <meta name="description" content="Bayesian Models for Linguists" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Comparing two groups of observations | A Quick Introduction to Multilevel Bayesian Models for Linguistic Researchers" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://santiagobarreda.com" />
  
  <meta property="og:description" content="Bayesian Models for Linguists" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Comparing two groups of observations | A Quick Introduction to Multilevel Bayesian Models for Linguistic Researchers" />
  
  <meta name="twitter:description" content="Bayesian Models for Linguists" />
  

<meta name="author" content="Santiago Bareda" />


<meta name="date" content="2021-01-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"/>
<link rel="next" href="comparing-many-groups.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-29379Y1Q2X"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-29379Y1Q2X');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bayesian Models for Linguists</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html"><i class="fa fa-check"></i><b>1</b> Inspecting a single group of observations</a>
<ul>
<li class="chapter" data-level="1.1" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#data-and-research-questions"><i class="fa fa-check"></i><b>1.1</b> Data and research questions</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#inspecting-the-central-location-and-spread-of-values"><i class="fa fa-check"></i><b>1.1.1</b> Inspecting the central location and spread of values</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#probability-distributions"><i class="fa fa-check"></i><b>1.2</b> Probability Distributions</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#the-normal-distribution"><i class="fa fa-check"></i><b>1.2.1</b> The normal distribution</a></li>
<li class="chapter" data-level="1.2.2" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#referring-to-the-normal-distribution-to-make-inferences"><i class="fa fa-check"></i><b>1.2.2</b> Referring to the normal distribution to make inferences</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#probabilities-of-events-and-likelihoods-of-parameters"><i class="fa fa-check"></i><b>1.3</b> Probabilities of events and likelihoods of parameters</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#making-inferences-using-likelihoods"><i class="fa fa-check"></i><b>1.3.1</b> Making inferences using likelihoods</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#bayesian-models"><i class="fa fa-check"></i><b>1.4</b> Bayesian models</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#what-are-regression-models"><i class="fa fa-check"></i><b>1.4.1</b> What are regression models?</a></li>
<li class="chapter" data-level="1.4.2" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#whats-bayesian-about-these-models"><i class="fa fa-check"></i><b>1.4.2</b> What’s ‘Bayesian’ about these models?</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#posterior-distributions"><i class="fa fa-check"></i><b>1.5</b> Posterior distributions</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#sampling-from-the-posterior"><i class="fa fa-check"></i><b>1.5.1</b> Sampling from the posterior</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="inspecting-a-single-group-of-observations.html"><a href="inspecting-a-single-group-of-observations.html#plot-code"><i class="fa fa-check"></i><b>1.6</b> Plot Code</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><i class="fa fa-check"></i><b>2</b> Inspecting a ‘single group’ of observations using a Bayesian multilevel model</a>
<ul>
<li class="chapter" data-level="2.1" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#data-and-research-questions-1"><i class="fa fa-check"></i><b>2.1</b> Data and research questions</a></li>
<li class="chapter" data-level="2.2" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#estimating-a-single-mean-with-the-brms-package"><i class="fa fa-check"></i><b>2.2</b> Estimating a single mean with the <code>brms</code> package</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#the-model"><i class="fa fa-check"></i><b>2.2.1</b> The model</a></li>
<li class="chapter" data-level="2.2.2" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#the-model-formula"><i class="fa fa-check"></i><b>2.2.2</b> The model formula</a></li>
<li class="chapter" data-level="2.2.3" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#calling-the-brm-function"><i class="fa fa-check"></i><b>2.2.3</b> Calling the <code>brm</code> function</a></li>
<li class="chapter" data-level="2.2.4" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#interpreting-the-model-print-statement"><i class="fa fa-check"></i><b>2.2.4</b> Interpreting the model print statement</a></li>
<li class="chapter" data-level="2.2.5" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#seeing-the-samples"><i class="fa fa-check"></i><b>2.2.5</b> Seeing the samples</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#repeated-measures-data"><i class="fa fa-check"></i><b>2.3</b> Repeated measures data</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#multilevel-models"><i class="fa fa-check"></i><b>2.3.1</b> Multilevel models</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#estimating-a-multilevel-model-with-brms"><i class="fa fa-check"></i><b>2.4</b> Estimating a multilevel model with <code>brms</code></a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#the-model-1"><i class="fa fa-check"></i><b>2.4.1</b> The model</a></li>
<li class="chapter" data-level="2.4.2" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#fitting-the-model"><i class="fa fa-check"></i><b>2.4.2</b> Fitting the model</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#checking-model-convergence"><i class="fa fa-check"></i><b>2.5</b> Checking model convergence</a></li>
<li class="chapter" data-level="2.6" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#specifying-prior-probabilities"><i class="fa fa-check"></i><b>2.6</b> Specifying prior probabilities</a></li>
<li class="chapter" data-level="2.7" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#answering-our-research-questions"><i class="fa fa-check"></i><b>2.7</b> Answering our research questions</a></li>
<li class="chapter" data-level="2.8" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#plot-code-1"><i class="fa fa-check"></i><b>2.8</b> Plot Code</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html"><i class="fa fa-check"></i><b>3</b> Comparing two groups of observations</a>
<ul>
<li class="chapter" data-level="3.1" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#data-and-research-questions-2"><i class="fa fa-check"></i><b>3.1</b> Data and research questions</a></li>
<li class="chapter" data-level="3.2" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#estimating-the-difference-two-means-with-brms"><i class="fa fa-check"></i><b>3.2</b> Estimating the difference two means with ‘brms’</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#fitting-the-model-1"><i class="fa fa-check"></i><b>3.2.1</b> Fitting the model</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#contrasts"><i class="fa fa-check"></i><b>3.3</b> Contrasts</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#treatment-coding"><i class="fa fa-check"></i><b>3.3.1</b> Treatment coding</a></li>
<li class="chapter" data-level="3.3.2" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#sum-coding"><i class="fa fa-check"></i><b>3.3.2</b> Sum coding</a></li>
<li class="chapter" data-level="3.3.3" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#comparison-of-sum-and-treatment-coding"><i class="fa fa-check"></i><b>3.3.3</b> Comparison of sum and treatment coding</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#refitting-the-model-with-sum-coding"><i class="fa fa-check"></i><b>3.4</b> Refitting the model with sum coding</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#fitting-the-model-2"><i class="fa fa-check"></i><b>3.4.1</b> Fitting the model</a></li>
<li class="chapter" data-level="3.4.2" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#the-model-2"><i class="fa fa-check"></i><b>3.4.2</b> The model</a></li>
<li class="chapter" data-level="3.4.3" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#interpreting-the-two-group-model"><i class="fa fa-check"></i><b>3.4.3</b> Interpreting the two-group model</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#random-effects"><i class="fa fa-check"></i><b>3.5</b> ‘Random’ Effects</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#random-effects-priors-and-pooling"><i class="fa fa-check"></i><b>3.5.1</b> Random effects, priors and pooling</a></li>
<li class="chapter" data-level="3.5.2" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#inspecting-the-random-effects"><i class="fa fa-check"></i><b>3.5.2</b> Inspecting the random effects</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="comparing-two-groups-of-observations.html"><a href="comparing-two-groups-of-observations.html#but-what-does-it-all-mean"><i class="fa fa-check"></i><b>3.6</b> But what does it all mean?</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html"><i class="fa fa-check"></i><b>4</b> Comparing many groups</a>
<ul>
<li class="chapter" data-level="4.1" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#data-and-research-questions-3"><i class="fa fa-check"></i><b>4.1</b> Data and research questions</a></li>
<li class="chapter" data-level="4.2" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#comparing-four-or-any-number-of-groups"><i class="fa fa-check"></i><b>4.2</b> Comparing four (or any number of) groups</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#the-model-3"><i class="fa fa-check"></i><b>4.2.1</b> The model</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#investigating-many-groups-using-predictors-analysis-of-variance"><i class="fa fa-check"></i><b>4.3</b> Investigating many groups using predictors: Analysis of Variance</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#the-model-4"><i class="fa fa-check"></i><b>4.3.1</b> The model</a></li>
<li class="chapter" data-level="4.3.2" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#fitting-the-model-and-interpreting-the-results"><i class="fa fa-check"></i><b>4.3.2</b> Fitting the model and interpreting the results</a></li>
<li class="chapter" data-level="4.3.3" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#investigating-model-fit"><i class="fa fa-check"></i><b>4.3.3</b> Investigating model fit</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#interactions-and-interaction-plots"><i class="fa fa-check"></i><b>4.4</b> Interactions and interaction plots</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#interactions-in-our-f0-data"><i class="fa fa-check"></i><b>4.4.1</b> Interactions in our f0 data</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#investigating-interactions-with-a-model"><i class="fa fa-check"></i><b>4.5</b> Investigating interactions with a model</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#fitting-the-model-and-interpreting-the-results-1"><i class="fa fa-check"></i><b>4.5.1</b> Fitting the model and interpreting the results</a></li>
<li class="chapter" data-level="4.5.2" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#assessing-model-fit"><i class="fa fa-check"></i><b>4.5.2</b> Assessing model fit</a></li>
<li class="chapter" data-level="4.5.3" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#investigating-the-interactions-the-easy-way"><i class="fa fa-check"></i><b>4.5.3</b> Investigating the interactions the easy way</a></li>
<li class="chapter" data-level="4.5.4" data-path="comparing-many-groups.html"><a href="comparing-many-groups.html#making-plots"><i class="fa fa-check"></i><b>4.5.4</b> Making plots</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="http://www.santiagobarreda.com" target="blank">Written by Santiago Barreda</a></li>
<li><a href="A-Quick-Introduction-to-Multilevel-Bayesian-Models-for-Linguistic-Researchers.pdf" target="blank">Download possibly outdated and badly-formatted PDF</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Quick Introduction to Multilevel Bayesian Models for Linguistic Researchers</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="comparing-two-groups-of-observations" class="section level1" number="3">
<h1><span class="header-section-number">Chapter 3</span> Comparing two groups of observations</h1>
<p>In the previous chapter, I focused on investigating values from a single group, which is the simplest data you can deal with. In this chapter we are going to compare data from two groups to see how similar/different they really are. The models we will discuss are similar to two-sample t-tests (and some ANOVA designs) in the types of research questions they can help investigate.</p>
<div id="data-and-research-questions-2" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Data and research questions</h2>
<p>We are going to be using the same Hillenbrand et al. f0 data we used in the other chapters, but this time we are going to compare the f0 measurements for adult females to those of girls between 10-12 years of age.</p>
<p>Below I load in the Hillenbrand et al. data, and include a new variable that indicates whether the talker is an adult or a child. I also split the data up by gender. The variable <code>speaker</code> is a speaker number that is unique across all speaker groups, and <code>group</code> indicates speaker group from among <code>b</code> (boys), <code>g</code> (girls), <code>m</code> (men), and <code>w</code> (women).</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="comparing-two-groups-of-observations.html#cb122-1" aria-hidden="true" tabindex="-1"></a>url1 <span class="ot">=</span> <span class="st">&quot;https://raw.githubusercontent.com/santiagobarreda&quot;</span></span>
<span id="cb122-2"><a href="comparing-two-groups-of-observations.html#cb122-2" aria-hidden="true" tabindex="-1"></a>url2 <span class="ot">=</span> <span class="st">&quot;/stats-class/master/data/h95_vowel_data.csv&quot;</span></span>
<span id="cb122-3"><a href="comparing-two-groups-of-observations.html#cb122-3" aria-hidden="true" tabindex="-1"></a>h95 <span class="ot">=</span> <span class="fu">read.csv</span> (<span class="fu">url</span>(<span class="fu">paste0</span> (url1, url2)))</span>
<span id="cb122-4"><a href="comparing-two-groups-of-observations.html#cb122-4" aria-hidden="true" tabindex="-1"></a><span class="do">## make variable that indicates if the talker is an adult</span></span>
<span id="cb122-5"><a href="comparing-two-groups-of-observations.html#cb122-5" aria-hidden="true" tabindex="-1"></a>h95<span class="sc">$</span>adult <span class="ot">=</span> <span class="st">&quot;&quot;</span></span>
<span id="cb122-6"><a href="comparing-two-groups-of-observations.html#cb122-6" aria-hidden="true" tabindex="-1"></a>h95<span class="sc">$</span>adult[h95<span class="sc">$</span>group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;w&#39;</span>,<span class="st">&#39;m&#39;</span>)] <span class="ot">=</span> <span class="st">&quot;adult&quot;</span></span>
<span id="cb122-7"><a href="comparing-two-groups-of-observations.html#cb122-7" aria-hidden="true" tabindex="-1"></a>h95<span class="sc">$</span>adult[h95<span class="sc">$</span>group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;g&#39;</span>,<span class="st">&#39;b&#39;</span>)] <span class="ot">=</span> <span class="st">&quot;child&quot;</span></span>
<span id="cb122-8"><a href="comparing-two-groups-of-observations.html#cb122-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-9"><a href="comparing-two-groups-of-observations.html#cb122-9" aria-hidden="true" tabindex="-1"></a><span class="do">## split up data by into male and female groups, only some columns</span></span>
<span id="cb122-10"><a href="comparing-two-groups-of-observations.html#cb122-10" aria-hidden="true" tabindex="-1"></a>males <span class="ot">=</span> h95[h95<span class="sc">$</span>group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;m&#39;</span>,<span class="st">&#39;b&#39;</span>),<span class="fu">c</span>(<span class="st">&#39;f0&#39;</span>, <span class="st">&#39;adult&#39;</span>, <span class="st">&#39;group&#39;</span>, <span class="st">&#39;speaker&#39;</span>)]</span>
<span id="cb122-11"><a href="comparing-two-groups-of-observations.html#cb122-11" aria-hidden="true" tabindex="-1"></a>females <span class="ot">=</span> h95[h95<span class="sc">$</span>group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;w&#39;</span>,<span class="st">&#39;g&#39;</span>),<span class="fu">c</span>(<span class="st">&#39;f0&#39;</span>, <span class="st">&#39;adult&#39;</span>, <span class="st">&#39;group&#39;</span>, <span class="st">&#39;speaker&#39;</span>)]</span>
<span id="cb122-12"><a href="comparing-two-groups-of-observations.html#cb122-12" aria-hidden="true" tabindex="-1"></a>f0 <span class="ot">=</span> females[[<span class="st">&#39;f0&#39;</span>]]</span>
<span id="cb122-13"><a href="comparing-two-groups-of-observations.html#cb122-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-14"><a href="comparing-two-groups-of-observations.html#cb122-14" aria-hidden="true" tabindex="-1"></a><span class="co"># re-factor to remove excluded subjects</span></span>
<span id="cb122-15"><a href="comparing-two-groups-of-observations.html#cb122-15" aria-hidden="true" tabindex="-1"></a>males<span class="sc">$</span>speaker <span class="ot">=</span> <span class="fu">factor</span> (males<span class="sc">$</span>speaker)  </span>
<span id="cb122-16"><a href="comparing-two-groups-of-observations.html#cb122-16" aria-hidden="true" tabindex="-1"></a><span class="co"># re-factor to remove excluded subjects</span></span>
<span id="cb122-17"><a href="comparing-two-groups-of-observations.html#cb122-17" aria-hidden="true" tabindex="-1"></a>females<span class="sc">$</span>speaker <span class="ot">=</span> <span class="fu">factor</span> (females<span class="sc">$</span>speaker)  </span>
<span id="cb122-18"><a href="comparing-two-groups-of-observations.html#cb122-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-19"><a href="comparing-two-groups-of-observations.html#cb122-19" aria-hidden="true" tabindex="-1"></a><span class="do">## set up colors</span></span>
<span id="cb122-20"><a href="comparing-two-groups-of-observations.html#cb122-20" aria-hidden="true" tabindex="-1"></a>lightpink <span class="ot">=</span> <span class="fu">rgb</span> (<span class="dv">247</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">181</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">197</span><span class="sc">/</span><span class="dv">255</span>, <span class="fl">0.75</span>)</span>
<span id="cb122-21"><a href="comparing-two-groups-of-observations.html#cb122-21" aria-hidden="true" tabindex="-1"></a>lavender <span class="ot">=</span> <span class="fu">rgb</span> (<span class="dv">202</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">135</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">185</span><span class="sc">/</span><span class="dv">255</span>, <span class="fl">0.75</span>)</span>
<span id="cb122-22"><a href="comparing-two-groups-of-observations.html#cb122-22" aria-hidden="true" tabindex="-1"></a>coral <span class="ot">=</span> <span class="fu">rgb</span> (<span class="dv">238</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">78</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">98</span><span class="sc">/</span><span class="dv">255</span>, <span class="fl">0.75</span>)</span>
<span id="cb122-23"><a href="comparing-two-groups-of-observations.html#cb122-23" aria-hidden="true" tabindex="-1"></a>yellow <span class="ot">=</span> <span class="fu">rgb</span> (<span class="dv">248</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">166</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">27</span><span class="sc">/</span><span class="dv">255</span>, <span class="fl">0.75</span>)</span>
<span id="cb122-24"><a href="comparing-two-groups-of-observations.html#cb122-24" aria-hidden="true" tabindex="-1"></a>deepgreen <span class="ot">=</span> <span class="fu">rgb</span> (<span class="dv">12</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">130</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">117</span><span class="sc">/</span><span class="dv">255</span>, <span class="fl">0.75</span>)</span>
<span id="cb122-25"><a href="comparing-two-groups-of-observations.html#cb122-25" aria-hidden="true" tabindex="-1"></a>teal <span class="ot">=</span> <span class="fu">rgb</span> (<span class="dv">39</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">192</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">216</span><span class="sc">/</span><span class="dv">255</span>, <span class="fl">0.75</span>)</span>
<span id="cb122-26"><a href="comparing-two-groups-of-observations.html#cb122-26" aria-hidden="true" tabindex="-1"></a>skyblue <span class="ot">=</span><span class="fu">rgb</span> (<span class="dv">58</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">101</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">175</span><span class="sc">/</span><span class="dv">255</span>, <span class="fl">0.75</span>)</span>
<span id="cb122-27"><a href="comparing-two-groups-of-observations.html#cb122-27" aria-hidden="true" tabindex="-1"></a>maroon <span class="ot">=</span> <span class="fu">rgb</span> (<span class="dv">130</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">43</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">50</span><span class="sc">/</span><span class="dv">255</span>, .<span class="dv">75</span>)</span>
<span id="cb122-28"><a href="comparing-two-groups-of-observations.html#cb122-28" aria-hidden="true" tabindex="-1"></a>deeppurple <span class="ot">=</span> <span class="fu">rgb</span> (<span class="dv">96</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">45</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">69</span><span class="sc">/</span><span class="dv">255</span>, <span class="fl">0.75</span>)</span>
<span id="cb122-29"><a href="comparing-two-groups-of-observations.html#cb122-29" aria-hidden="true" tabindex="-1"></a>cols <span class="ot">=</span> <span class="fu">c</span>(lightpink,lavender,coral,yellow,deepgreen,teal,skyblue,maroon,deeppurple)</span></code></pre></div>
<p>One of the simplest questions a researcher can ask (from a modeling perspective) is: Are two groups of observations different or are they the same? For example in phonetics, researchers ask questions like, have these vowels merged in this dialect (are these two things different)? Does visual information speed up speech perception or not (are two sets of reaction times the same)?</p>
<p>A good way to isolate a single difference is to create groups that differ primarily according to the characteristic you are interested in testing, but are otherwise the same ‘on average’. For the reaction-time example above, I might present the same listeners with very similar words in the same conditions, but half with and half without visual information. The difference in reaction times between the groups should reflect the advantage provided by visual information. The question would then be, are reaction times with visual information <em>the same thing</em> as reaction times without visual information? Are these two sets of observations samples from the same population? Or is the set of observations “reaction times for speech recognized <em>with</em> visual information” a different set of things than “reaction times for speech recognized <em>without</em> visual information”?</p>
<p>In our data we have male and female talkers of the same dialect, who differ primarily in terms of age. Basically, these groups differ mostly in terms of ‘adultness’, and so we can use the characteristics of these groups to investigate the effect of ‘adultness’ on average f0. Below I present boxplots of the effect of adultness on f0, first overall and then divided by speaker gender.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="comparing-two-groups-of-observations.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span> (<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb123-2"><a href="comparing-two-groups-of-observations.html#cb123-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span> (f0 <span class="sc">~</span> adult, <span class="at">data =</span> h95, <span class="at">main =</span> <span class="st">&quot;Overall&quot;</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">90</span>,<span class="dv">330</span>), </span>
<span id="cb123-3"><a href="comparing-two-groups-of-observations.html#cb123-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="fu">c</span>(teal, yellow))</span>
<span id="cb123-4"><a href="comparing-two-groups-of-observations.html#cb123-4" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span> (f0 <span class="sc">~</span> adult, <span class="at">data =</span> females, <span class="at">main =</span> <span class="st">&quot;Females&quot;</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">90</span>,<span class="dv">330</span>), </span>
<span id="cb123-5"><a href="comparing-two-groups-of-observations.html#cb123-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="fu">c</span>(deepgreen,skyblue))</span>
<span id="cb123-6"><a href="comparing-two-groups-of-observations.html#cb123-6" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span> (f0 <span class="sc">~</span> adult, <span class="at">data =</span> males, <span class="at">main =</span> <span class="st">&quot;Males&quot;</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">90</span>,<span class="dv">330</span>), </span>
<span id="cb123-7"><a href="comparing-two-groups-of-observations.html#cb123-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="fu">c</span>(maroon,lightpink))</span></code></pre></div>
<p><img src="week-3_files/figure-html/unnamed-chunk-2-1.png" width="768" /></p>
<p>Clearly there is a difference in f0 between children and adults, but the difference also seems to be gender-dependent: there is more of a difference between men and boys than between women and girls. We are going to focus on the female data for now, and I leave the male data so that the reader can modify the analysis presented here to analyze that data.</p>
<p>Below, the figure on the left highlights both between- and within-speaker variation in f0 by women (cyan) and girls (red). On the right, we see the overall distributions of f0 for women (cyan) and girls (red). Obviously the distributions seem a <em>bit</em> different, but they are also not <em>that</em> different. We can also clearly see that there is substantial overlap between individual girls and women (in the figure on the left). As a result, a cautious analysis of this data would recognize this overlap even if somehow ‘differentess’ were found. We are going to fit a model that can help us quantify all of the variability shown in the figures below.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="comparing-two-groups-of-observations.html#cb124-1" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">=</span> </span>
<span id="cb124-2"><a href="comparing-two-groups-of-observations.html#cb124-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(coral,teal)[ <span class="fu">apply</span> (<span class="fu">table</span>(females<span class="sc">$</span>speaker, females<span class="sc">$</span>adult),<span class="dv">1</span>,which.max) ]</span>
<span id="cb124-3"><a href="comparing-two-groups-of-observations.html#cb124-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-4"><a href="comparing-two-groups-of-observations.html#cb124-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span> (<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)); <span class="fu">layout</span> (<span class="at">mat =</span> <span class="fu">t</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)), <span class="at">widths =</span> <span class="fu">c</span>(.<span class="dv">7</span>,.<span class="dv">3</span>))</span>
<span id="cb124-5"><a href="comparing-two-groups-of-observations.html#cb124-5" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span> (f0 <span class="sc">~</span> speaker, <span class="at">data=</span>females, <span class="at">col =</span> colors)</span>
<span id="cb124-6"><a href="comparing-two-groups-of-observations.html#cb124-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-7"><a href="comparing-two-groups-of-observations.html#cb124-7" aria-hidden="true" tabindex="-1"></a><span class="do">## I rotate the density figures so that you can see how these correspond to</span></span>
<span id="cb124-8"><a href="comparing-two-groups-of-observations.html#cb124-8" aria-hidden="true" tabindex="-1"></a><span class="do">## the boxplots on the left. </span></span>
<span id="cb124-9"><a href="comparing-two-groups-of-observations.html#cb124-9" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">=</span> <span class="fu">density</span> (females<span class="sc">$</span>f0[females<span class="sc">$</span>adult<span class="sc">==</span><span class="st">&quot;child&quot;</span>])</span>
<span id="cb124-10"><a href="comparing-two-groups-of-observations.html#cb124-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> (tmp<span class="sc">$</span>y, tmp<span class="sc">$</span>x, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> teal, <span class="at">ylab =</span> <span class="st">&quot;f0&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Density&quot;</span>, </span>
<span id="cb124-11"><a href="comparing-two-groups-of-observations.html#cb124-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">140</span>,<span class="dv">320</span>), <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.025</span>), <span class="at">type =</span> <span class="st">&#39;l&#39;</span>)</span>
<span id="cb124-12"><a href="comparing-two-groups-of-observations.html#cb124-12" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">=</span> <span class="fu">density</span> (females<span class="sc">$</span>f0[females<span class="sc">$</span>adult<span class="sc">==</span><span class="st">&quot;adult&quot;</span>])</span>
<span id="cb124-13"><a href="comparing-two-groups-of-observations.html#cb124-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span> (tmp<span class="sc">$</span>y, tmp<span class="sc">$</span>x, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> coral)</span></code></pre></div>
<p><img src="week-3_files/figure-html/unnamed-chunk-3-1.png" width="768" /></p>
</div>
<div id="estimating-the-difference-two-means-with-brms" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Estimating the difference two means with ‘brms’</h2>
<p>In chapter 2 the model we fit had the simplest possible formula, just an intercept. Here, we need to extend this to include an actual predictor: a vector indicating ‘adultness’. Remember that formulas look like this <code>variable ~ predictor</code>. So, if we want to predict f0 based on whether the talker is an adult or not, our model is going to have a formula that looks basically like this <code>f0 ~ adult + (1|speaker)</code>. You can think of this meaning something like ‘We expect the distribution to vary based on whether the talker is an adult or not, in addition to speaker-specific adjustments to the intercept’.</p>
<p>Note that the model calculates an intercept (mean value) for each speaker, but does <strong>not</strong> include an effect for <code>adult</code> for each speaker (i.e., the model does <em>not</em> include a term like <code>(adult|speaker)</code>). This is because we are estimating a mean for each speaker, but not the effect for ‘adultness’ for each speaker. Each speaker is only either an adult or a child, and so we cannot estimate the effect for ‘adultness’ for each speaker. Doing things that don’t ‘make sense’ from the model’s perspective will cause it to crash or return strange values.</p>
<p>I’m not going to go into so much detail about the structure of the regression model right now because an explanation involves some of the less intuitive concepts relating to regression. We are going to to fit the model first and discuss its structure, and then get to the details of the model later.</p>
<div id="fitting-the-model-1" class="section level3" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Fitting the model</h3>
<p>First we find the mean and the standard deviation of our data to use in the priors. As before, I intend to use the data mean for the intercept, and use a standard deviation twice as wide as the data standard deviation.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="comparing-two-groups-of-observations.html#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="do">## establish data statistics for priors</span></span>
<span id="cb125-2"><a href="comparing-two-groups-of-observations.html#cb125-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span> (f0)</span></code></pre></div>
<pre><code>## [1] 225.4913</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="comparing-two-groups-of-observations.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span> (f0)</span></code></pre></div>
<pre><code>## [1] 23.98959</code></pre>
<p>We load the <code>brms</code> package and fit the model. Notice that I now include a prior for <code>class = "b"</code>, which is the class for all predictors that are not the intercept. Our model now includes a non-intercept term, and so I need to include this prior:</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="comparing-two-groups-of-observations.html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span> (brms)</span></code></pre></div>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="comparing-two-groups-of-observations.html#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span> (<span class="dv">1</span>)</span>
<span id="cb130-2"><a href="comparing-two-groups-of-observations.html#cb130-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span>  </span>
<span id="cb130-3"><a href="comparing-two-groups-of-observations.html#cb130-3" aria-hidden="true" tabindex="-1"></a>  brms<span class="sc">::</span><span class="fu">brm</span> (f0 <span class="sc">~</span> adult <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>speaker), <span class="at">data =</span> females, <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">cores =</span> <span class="dv">4</span>,</span>
<span id="cb130-4"><a href="comparing-two-groups-of-observations.html#cb130-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">iter =</span> <span class="dv">11000</span>, <span class="at">thin =</span> <span class="dv">10</span>,</span>
<span id="cb130-5"><a href="comparing-two-groups-of-observations.html#cb130-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 225.5, 48)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;Intercept&quot;</span>),</span>
<span id="cb130-6"><a href="comparing-two-groups-of-observations.html#cb130-6" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 0, 48)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;b&quot;</span>),</span>
<span id="cb130-7"><a href="comparing-two-groups-of-observations.html#cb130-7" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 0, 48)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;sd&quot;</span>)))</span></code></pre></div>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="comparing-two-groups-of-observations.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="do">## load and inspect pre-fit model</span></span>
<span id="cb131-2"><a href="comparing-two-groups-of-observations.html#cb131-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">readRDS</span> (<span class="st">&#39;3_model.RDS&#39;</span>)</span>
<span id="cb131-3"><a href="comparing-two-groups-of-observations.html#cb131-3" aria-hidden="true" tabindex="-1"></a>model</span></code></pre></div>
<pre><code>##  Family: gaussian 
##   Links: mu = identity; sigma = identity 
## Formula: f0 ~ adult + (1 | uspeaker) 
##    Data: females (Number of observations: 804) 
## Samples: 4 chains, each with iter = 11000; warmup = 1000; thin = 10;
##          total post-warmup samples = 4000
## 
## Group-Level Effects: 
## ~uspeaker (Number of levels: 67) 
##               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sd(Intercept)    19.10      1.77    16.00    22.88 1.00     2781     3089
## 
## Population-Level Effects: 
##            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept    220.47      2.80   215.10   226.16 1.00     1827     2813
## adultchild    17.63      5.22     7.34    27.88 1.00     1987     2068
## 
## Family Specific Parameters: 
##       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sigma    12.93      0.34    12.28    13.59 1.00     3537     3773
## 
## Samples were drawn using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
<p>The output is mostly familiar, but there is a new predictor in the section on <code>Population-Level Effects</code>:</p>
<pre><code>           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept    220.47      2.80   215.10   226.16 1.00     1827     2813
adultchild    17.63      5.22     7.34    27.88 1.00     1987     2068</code></pre>
<p>In addition to the ‘Intercept’ term, we now get estimates for a term called <code>adultchild</code>. Admittedly, this is a strange name, but its how R handles predictors that are words (called ‘factors’ in R). In general, r names predictors like these <code>factornameFactorlevel</code>. For example, a factor called <code>colors</code> with levels <code>red</code>, <code>green</code> and <code>blue</code> might have a level represented like <code>colorsred</code>. So, the <code>adultchild</code> name tells us is that this is the estimate for the <code>child</code> level of the <code>adult</code> factor.</p>
<p>A couple of questions arise. First, the ‘Intercept’ term in the model above seems to correspond to the mean f0 for adult females. We can confirm this:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="comparing-two-groups-of-observations.html#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="do">## calculate means of f0 based on values of adult vector</span></span>
<span id="cb134-2"><a href="comparing-two-groups-of-observations.html#cb134-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span> (females<span class="sc">$</span>f0, females<span class="sc">$</span>adult, mean)</span></code></pre></div>
<pre><code>##    adult    child 
## 220.4010 238.3509</code></pre>
<p>However, the estimate for children is 17.6 Hz, which is odd. This is obviously not the mean f0 for the girls in our sample. Why not? To understand model coefficients we are going to have to talk about contrasts</p>
</div>
</div>
<div id="contrasts" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Contrasts</h2>
<p>Contrasts are the numerical implementation of factors in your model. Factors are variables like adult vs. child that are not inherently numerical. You may initially think that we can separately estimate the women’s average, the girl’s average, and the overall mean. However, our models can’t actually do this. The general problem is this: if you have two groups you can’t independently calculate:</p>
<ol style="list-style-type: decimal">
<li>group 1 mean.</li>
<li>group 2 mean.</li>
<li>the overall mean.</li>
</ol>
<p>Why not? Because once you know 2 of those things you know the 3rd. For example, if the group 1 mean is 5 and the overall mean is 6, obviously the group 2 mean <strong>must</strong> be 7. Why does this matter? Because when things are entirely predictable based on each other, they are not actually separate things, even though they may seem that way to us. When things are entirely predictable in this way we say they are linearly dependent, and regression models don’t like this. Here’s three perspectives on why this is a problem:</p>
<ol style="list-style-type: decimal">
<li><p>Imagine you were trying to predict a person’s weight from their height. You want to include height in centimeters <em>and</em> height in meters in your model, and you want to independently estimate effects for both predictors. Since height in centimeters = height in meters / 100, that is obviously not going to be possible. The effect of one must be 100 times the effect of the other! Even though it may be less transparent, this is the same reason why we can’t estimate all the group means <em>and</em> the overall mean.</p></li>
<li><p>With two groups, or any two points in a space, you can estimate one distance, not two. If each group could really be a different distance from the mean, you would need to estimate <em>two</em> distances. Instead, we are really only in a position to estimate <em>one</em> difference, that between our two group averages.</p></li>
<li><p>When we had one group we obviously couldn’t get the overall mean independently from the sample mean. All we had was the sample mean, and that was our best estimate of the population mean too. Adding 1 more group allows us to calculate 1 more mean. Why would it let us calculate 2 more means? That would mean adding a second group (with 1 mean) somehow contributed twice as much information as the first group did. Instead, adding a second mean changes our best guess for the population mean: it is now between the two groups. However, this information is in no way independent from the two group means in our design.</p></li>
</ol>
<div id="treatment-coding" class="section level3" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Treatment coding</h3>
<p>The coding scheme you use determines how your model represents the differences it encodes. In the model above we used ‘treatment’ coding (the default in R). In treatment coding, a ‘reference’ level is chosen to be the intercept, and all group effects reflect the difference between the group mean and the mean for the reference level.</p>
<p>By default, R chooses the alphabetically-lowest level to be the reference level. That is why the Intercept in our model is equal to the mean of the ‘adult’ group, the average for adult females. The effect for ‘child’ (<code>adultchild</code>) represents the difference between the child mean and the adult mean. This means that our credible intervals also represent the <em>difference</em> in the means and not the means themselves. So, we expect the <em>difference</em> between girls and women in this sample to be about 17 Hz, and we think there is a 95% chance that the <em>difference</em> between the means is between 7.3 and 27.9 Hz in magnitude.</p>
<p>We can see how the effects estimates in our model resemble the means, or differences between means, in our sample.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="comparing-two-groups-of-observations.html#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate group means</span></span>
<span id="cb136-2"><a href="comparing-two-groups-of-observations.html#cb136-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span> (females<span class="sc">$</span>f0, females<span class="sc">$</span>adult, mean)</span></code></pre></div>
<pre><code>##    adult    child 
## 220.4010 238.3509</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="comparing-two-groups-of-observations.html#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find the difference between them</span></span>
<span id="cb138-2"><a href="comparing-two-groups-of-observations.html#cb138-2" aria-hidden="true" tabindex="-1"></a><span class="fu">diff</span> (<span class="fu">tapply</span> (females<span class="sc">$</span>f0, females<span class="sc">$</span>adult, mean))</span></code></pre></div>
<pre><code>##    child 
## 17.94984</code></pre>
<p>To interpret treatment coded coefficients remember:</p>
<ul>
<li><p>The reference category mean is the ‘Intercept’ in the model.</p></li>
<li><p>The value of the coefficients of any other group mean will be equal to <code>group mean - reference group mean</code>.</p></li>
<li><p>To recover the mean estimate for any other group, we add <code>group mean + reference group mean</code>.</p></li>
</ul>
</div>
<div id="sum-coding" class="section level3" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Sum coding</h3>
<p>There are multiple options for coding schemes, and the best one for you depends on what you want to get out of the model. The only other alternative to treatment coding that we will talk about is what is called ‘sum coding’. It is a very useful coding scheme for many of the designs most commonly-used by linguists, and it is the coding shceme we will be using going forward.</p>
<p>In sum coding, there is no reference level. Instead, the model Intercept represents the overall mean of all your groups, and group differences are represented with respect to the mean of your data. Just like for treatment coding, you can’t estimate all of your group means. For treatment coding, R selects the <em>alphabetically last</em> level of your factor, and does not estimate it. Under sum coding, the missing factor level will always be equal to the <strong>negative sum</strong> of the other factors. This means you add up the values of the levels that <em>are</em> present, and flip the sign. The outcome is the value of your missing level.</p>
<p>As discussed earlier, with only two groups if you know the overall mean and the distance of one group to the mean, you also know the distance of the other group to the mean. This can be seen quite clearly below where the difference of each group to the overall mean is exactly -8.97. So, if our model tells us that the mean is 229.4 and the adult group is -8.97 Hz below this, then the child group must be the negative sum of the other coefficients. In this case there is only one so we just flip the sign on it (i.e., - (-8.97)).</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="comparing-two-groups-of-observations.html#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate group means</span></span>
<span id="cb140-2"><a href="comparing-two-groups-of-observations.html#cb140-2" aria-hidden="true" tabindex="-1"></a>means <span class="ot">=</span> <span class="fu">tapply</span> (females<span class="sc">$</span>f0, females<span class="sc">$</span>adult, mean)</span>
<span id="cb140-3"><a href="comparing-two-groups-of-observations.html#cb140-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span> (means)</span></code></pre></div>
<pre><code>## [1] 229.376</code></pre>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="comparing-two-groups-of-observations.html#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find the distances to the overall mean</span></span>
<span id="cb142-2"><a href="comparing-two-groups-of-observations.html#cb142-2" aria-hidden="true" tabindex="-1"></a>means <span class="sc">-</span> <span class="fu">mean</span> (means)</span></code></pre></div>
<pre><code>##     adult     child 
## -8.974918  8.974918</code></pre>
<p>To interpret treatment coded coefficients remember:</p>
<ul>
<li><p>The overall mean of all your groups is the ‘Intercept’ in the model.</p></li>
<li><p>The value of the coefficients of any other group mean will be equal to <code>group mean - overall mean</code>.</p></li>
<li><p>To recover the mean estimate for any other group, we add <code>group mean + overall mean</code>.</p></li>
</ul>
</div>
<div id="comparison-of-sum-and-treatment-coding" class="section level3" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Comparison of sum and treatment coding</h3>
<p>The image below shows a comparison of the way the two coding schemes treat our data. In each case they estimate 1 intercept and one effect, letting you recreate 1 other mean (i.e., they each omit one parameter). In treatment coding this is the overall mean, which in the 2-group case will always be <code>Intercept + Effect/2</code>. In the case of sum coding this is the effect for the second group, which will always be the same magnitude but have the opposite sign as the effect for the first group.</p>
<p><img src="images/coding.png" width="100%" /></p>
</div>
</div>
<div id="refitting-the-model-with-sum-coding" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> Refitting the model with sum coding</h2>
<p>We are going to re-fit the model we fit above using sum coding, and see how the coefficients change.</p>
<div id="fitting-the-model-2" class="section level3" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Fitting the model</h3>
<p>To fit a model with sum coding, we change the global contrast options in R. These options will be in effect until we restart R or change the contrasts to something else.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="comparing-two-groups-of-observations.html#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="do">## to change to sum coding</span></span>
<span id="cb144-2"><a href="comparing-two-groups-of-observations.html#cb144-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span> (<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">&#39;contr.sum&#39;</span>,<span class="st">&#39;contr.sum&#39;</span>))</span>
<span id="cb144-3"><a href="comparing-two-groups-of-observations.html#cb144-3" aria-hidden="true" tabindex="-1"></a><span class="do">## to change back to treatment coding</span></span>
<span id="cb144-4"><a href="comparing-two-groups-of-observations.html#cb144-4" aria-hidden="true" tabindex="-1"></a><span class="co">#options (contrasts = c(&#39;contr.treatment&#39;,&#39;contr.treatment&#39;))</span></span></code></pre></div>
<p>We can fit the model with sum coding using the exact same code since the options have changed. Please keep in mind you will need to set this every time you start R, as it will reset to treatment coding each time it restarts.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="comparing-two-groups-of-observations.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span> (<span class="dv">1</span>)</span>
<span id="cb145-2"><a href="comparing-two-groups-of-observations.html#cb145-2" aria-hidden="true" tabindex="-1"></a>model_sum_coding <span class="ot">=</span>  </span>
<span id="cb145-3"><a href="comparing-two-groups-of-observations.html#cb145-3" aria-hidden="true" tabindex="-1"></a>  brms<span class="sc">::</span><span class="fu">brm</span> (f0 <span class="sc">~</span> adult <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>speaker), <span class="at">data =</span> females, <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">cores =</span> <span class="dv">4</span>,</span>
<span id="cb145-4"><a href="comparing-two-groups-of-observations.html#cb145-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">iter =</span> <span class="dv">11000</span>, <span class="at">thin =</span> <span class="dv">10</span>,</span>
<span id="cb145-5"><a href="comparing-two-groups-of-observations.html#cb145-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 225.5, 48)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;Intercept&quot;</span>),</span>
<span id="cb145-6"><a href="comparing-two-groups-of-observations.html#cb145-6" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 0, 48)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;b&quot;</span>),</span>
<span id="cb145-7"><a href="comparing-two-groups-of-observations.html#cb145-7" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 0, 48)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;sd&quot;</span>)))</span></code></pre></div>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="comparing-two-groups-of-observations.html#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="do">## load and inspect pre-fit model</span></span>
<span id="cb146-2"><a href="comparing-two-groups-of-observations.html#cb146-2" aria-hidden="true" tabindex="-1"></a>model_sum_coding <span class="ot">=</span> <span class="fu">readRDS</span> (<span class="st">&#39;3_model_sum_coding.RDS&#39;</span>)</span>
<span id="cb146-3"><a href="comparing-two-groups-of-observations.html#cb146-3" aria-hidden="true" tabindex="-1"></a>model_sum_coding</span></code></pre></div>
<pre><code>##  Family: gaussian 
##   Links: mu = identity; sigma = identity 
## Formula: f0 ~ adult + (1 | uspeaker) 
##    Data: females (Number of observations: 804) 
## Samples: 4 chains, each with iter = 11000; warmup = 1000; thin = 10;
##          total post-warmup samples = 4000
## 
## Group-Level Effects: 
## ~uspeaker (Number of levels: 67) 
##               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sd(Intercept)    19.13      1.80    16.01    22.96 1.00     2892     3144
## 
## Population-Level Effects: 
##           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept   229.33      2.71   224.07   234.81 1.00     2169     2758
## adult1       -8.89      2.65   -14.19    -3.55 1.00     2085     2825
## 
## Family Specific Parameters: 
##       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sigma    12.95      0.34    12.30    13.62 1.00     3922     3710
## 
## Samples were drawn using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
<p>A comparison of these results to that of our first model shows that the main difference is that, as expected, the Intercept now reflects the overall mean and the single parameter reflects the distance of the adult mean to the overall mean.</p>
<p>Note that the parameter is now called <code>adult1</code>. This is just how <code>brm</code> handles factors. Predictors representing factors will be named <code>factornameN</code>, where <code>factorname</code> is the predictor name and <code>N</code> is the level number. Levels are ordered alphabetically starting at one, and the alphabetically-last level will not be estimated.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="comparing-two-groups-of-observations.html#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span> ( <span class="fu">unique</span> (females<span class="sc">$</span>adult))</span></code></pre></div>
<pre><code>## [1] &quot;adult&quot; &quot;child&quot;</code></pre>
<p>So, <code>adult1</code> in our model corresponds to the “adult” level of our predictor, and <code>adult2</code> <em>would</em> be “child”, but it is not separately estimated by our model (since <code>adult2 = -adult12</code>).</p>
</div>
<div id="the-model-2" class="section level3" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> The model</h3>
<p>Regression models try to break up values into their components. This is why effects are expressed in terms of differences to some reference value. For example, if we say that that a person’s average f0 is usually 220 Hz and under some condition their average f0 is also 220 Hz, then we could say that this condition has no <em>effect</em> on their f0. To say that this condition has no effect on mean f0 is to say that it causes no difference in mean f0.</p>
<p>On the other hand something that <em>does</em> cause a difference in mean f0 <em>does</em> have an effect on mean f0. We can express the effect of something in terms of the difference it causes, for example, saying that under so and so conditions a person will tend to raise their f0 by 20 Hz, relative to some reference value (the intercept).</p>
<p>More generally, we can think of any variable as the sum of a bunch of independent <em>effects</em>. This is just a way to think about variables, to break up observed values into their component parts. It should not be confused with the <em>reality</em> of these values and the processes that underlie them (whatever that is!).</p>
<p>So far we have covered the fact that after picking a value to use as a reference point (the model intercept), our models:</p>
<ul>
<li><p>represent group means as deviations from the intercept.</p></li>
<li><p>represent the speaker-specific deviations from the intercept (<span class="math inline">\(\gamma_{speaker}\)</span>) as being centered at 0, with a standard deviation of <span class="math inline">\(\sigma_{speaker}\)</span>.</p></li>
<li><p>represent the random error (<span class="math inline">\(\varepsilon\)</span>) as having a mean of 0 and a standard deviation of <span class="math inline">\(\sigma_{error}\)</span>.</p></li>
</ul>
<p>In each case, these reflect <em>deviations</em> from some reference point. As a result, when the parameters associated with different effects equal 0, this means that no effect is present.</p>
<ul>
<li><p>when group coefficients are 0 the group lies exactly at the intercept. In sum coding this is the overall mean.</p></li>
<li><p>when a speaker-effect is 0 this speaker is exactly average with respect to their group.</p></li>
<li><p>when an error is 0 this production is exactly as expected for a given speaker.</p></li>
</ul>
<p>Based on thinking of our predictors as representing deviations from some reference value, We can ‘break up’ any observed value into its component parts. For example, suppose that the the overall mean is 229 Hz, the adult female mean is 220 Hz, and that a particuar speaker has a mean f0 of 240 Hz. If we observe a value of 256 Hz for this speaker, that suggests the following decomposition:</p>
<p>256 = 229 (Intercept) - 9 (adult female mean) + 20 (speaker effect) + 16 (error)</p>
<p>This reflects the following considerations:</p>
<ul>
<li>the average f0 across the groups is 229 Hz.</li>
<li>the average for adult females is 9 Hz below the overall mean.</li>
<li>this speaker’s average f0 is 20 Hz above the average for adult females.</li>
<li>this particular production is 16 Hz higher than expected for this particular speaker.</li>
</ul>
<p>Another observation from this talker might be:</p>
<p>237 = 229 (Intercept) - 9 (adult female mean) + 20 (speaker effect) - 3 (error)</p>
<p>In this case, the error is -3 since the production is now 3 Hz <em>below</em> the speaker average. Regressions models basically carry out these decompositions for us, and present information regarding these decompositions in the model summaries.</p>
<p>The full model specification, including prior probabilities is below. I used the same ordering format for the t-distributions that <code>brm</code> uses (nu, mean, sd).</p>
<p><span class="math display">\[\begin{equation}
\begin{split}
\textrm{Likelihood:} \\
y_{[i]} \sim \mathcal{N}(\mu_{[i]},\sigma_{error}) \\
\mu_{[i]} = Intercept + adult1 + \alpha_{speaker_{[i]}} \\\\
\textrm{Priors:} \\
\alpha_{speaker} \sim \mathcal{N}(0,\sigma_{speaker}) \\ \\ 
Intercept \sim t(3, 225.5, 48) \\ 
adult1 \sim t(3, 0, 48) \\ 
\sigma_{error} \sim t(3, 0, 48) \\
\sigma_{speaker} \sim t(3, 0, 48) \\ 
\end{split}
\end{equation}\]</span></p>
<p>The top chunk is labeled ‘likelihood’ because this chunk specifies the relationships between our parameters and our data. As a result, the relationships specified in this section determine the likelihood of the model parameters. For example, in the first line we say that our data is normally distributed around some mean parameter. In turn, this specifies the shape of the likelihood function for that parameter given the data (as discussed in Figure <a href="inspecting-a-single-group-of-observations.html#fig:likelihood1">1.8</a>). What I mean by this is that the shape of the likelihood functions for different model coefficients will be based on the relationships laid out in the section of the model description labeled ‘likelihood’.</p>
</div>
<div id="interpreting-the-two-group-model" class="section level3" number="3.4.3">
<h3><span class="header-section-number">3.4.3</span> Interpreting the two-group model</h3>
<p>The <code>brms</code> package has several functions that make getting information from these models simple. The <code>fixef</code> function gets you means and 95% credible intervals for all your ‘population level’ parameters (sometimes called ‘fixed’ effects).</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="comparing-two-groups-of-observations.html#cb150-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">fixef</span> (model_sum_coding)</span></code></pre></div>
<pre><code>##             Estimate Est.Error      Q2.5      Q97.5
## Intercept 229.327715  2.711261 224.07166 234.810010
## adult1     -8.888301  2.651641 -14.18979  -3.550734</code></pre>
<p>To recover the group means for women and girls, we need to combine the Intercept and the group parameters. We’re not actually allowed to just add the values you see above (for good, but technical reasons).</p>
<p>What you actually need to do is add <em>the individual samples for parameters</em>, and then inspect the output. You can see the individual samples by calling the <code>fixef</code> function and setting <code>summary</code> to <code>FALSE</code>. Below I plot the individual samples and histograms for the <code>Intercept</code> (the overall mean), the <code>adult1</code> (the effect for adults) parameter, and the negative of the <code>adult</code> parameter (the effect for girls). I also present the combination of <code>Intercept+adult1</code>, which yields an estimate of the adult female mean.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="comparing-two-groups-of-observations.html#cb152-1" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">=</span> brms<span class="sc">::</span><span class="fu">fixef</span> (model_sum_coding, <span class="at">summary =</span> <span class="cn">FALSE</span>)</span>
<span id="cb152-2"><a href="comparing-two-groups-of-observations.html#cb152-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(samples, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##           parameters
## iterations Intercept     adult1
##       [1,]  226.1704  -8.121943
##       [2,]  234.4365 -10.380060
##       [3,]  228.6168  -7.901476
##       [4,]  226.2287  -8.130842
##       [5,]  225.0607 -10.228533
##       [6,]  227.6880  -6.691685
##       [7,]  227.8307  -8.078614
##       [8,]  230.0513 -10.569158
##       [9,]  228.3428  -8.612124
##      [10,]  228.9045  -5.617644</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="comparing-two-groups-of-observations.html#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span> (<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">1</span>))</span>
<span id="cb154-2"><a href="comparing-two-groups-of-observations.html#cb154-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span> (samples[,<span class="st">&#39;Intercept&#39;</span>],<span class="at">freq=</span><span class="cn">FALSE</span>, <span class="at">col =</span> skyblue,<span class="at">main=</span><span class="st">&#39;Intercept&#39;</span>)  </span>
<span id="cb154-3"><a href="comparing-two-groups-of-observations.html#cb154-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span> (samples[,<span class="st">&#39;adult1&#39;</span>], <span class="at">freq=</span><span class="cn">FALSE</span>, <span class="at">col =</span> deeppurple,<span class="at">main=</span><span class="st">&#39;adult1&#39;</span>)</span>
<span id="cb154-4"><a href="comparing-two-groups-of-observations.html#cb154-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span> (<span class="sc">-</span>samples[,<span class="st">&#39;adult1&#39;</span>], <span class="at">freq=</span><span class="cn">FALSE</span>, <span class="at">col =</span> teal,<span class="at">main=</span><span class="st">&#39;-adult1&#39;</span>)</span>
<span id="cb154-5"><a href="comparing-two-groups-of-observations.html#cb154-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span> (samples[,<span class="st">&#39;Intercept&#39;</span>]<span class="sc">+</span>samples[,<span class="st">&#39;adult1&#39;</span>], <span class="at">freq=</span><span class="cn">FALSE</span>, </span>
<span id="cb154-6"><a href="comparing-two-groups-of-observations.html#cb154-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> yellow,<span class="at">main=</span><span class="st">&#39;Intercept+adult1&#39;</span>)</span>
<span id="cb154-7"><a href="comparing-two-groups-of-observations.html#cb154-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> (samples[,<span class="st">&#39;Intercept&#39;</span>], <span class="at">col =</span> skyblue,<span class="at">pch=</span><span class="dv">16</span>)  </span>
<span id="cb154-8"><a href="comparing-two-groups-of-observations.html#cb154-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> (samples[,<span class="st">&#39;adult1&#39;</span>], <span class="at">col =</span> deeppurple, <span class="at">pch=</span><span class="dv">16</span>)  </span>
<span id="cb154-9"><a href="comparing-two-groups-of-observations.html#cb154-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> (<span class="sc">-</span>samples[,<span class="st">&#39;adult1&#39;</span>], <span class="at">col =</span> teal, <span class="at">pch=</span><span class="dv">16</span>)  </span>
<span id="cb154-10"><a href="comparing-two-groups-of-observations.html#cb154-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> (samples[,<span class="st">&#39;Intercept&#39;</span>]<span class="sc">+</span>samples[,<span class="st">&#39;adult1&#39;</span>], <span class="at">col =</span> yellow,<span class="at">pch=</span><span class="dv">16</span>)  </span></code></pre></div>
<p><img src="week-3_files/figure-html/unnamed-chunk-17-1.png" width="768" /></p>
<p>We can then summarize the sum of the parameters using the <code>posterior_summary</code> function, resulting in a mean, standard deviation, and credible interval for the new parameter:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="comparing-two-groups-of-observations.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="do">## calculate child mean</span></span>
<span id="cb155-2"><a href="comparing-two-groups-of-observations.html#cb155-2" aria-hidden="true" tabindex="-1"></a>adult_mean <span class="ot">=</span> samples[,<span class="st">&#39;Intercept&#39;</span>] <span class="sc">+</span> samples[,<span class="st">&#39;adult1&#39;</span>]</span>
<span id="cb155-3"><a href="comparing-two-groups-of-observations.html#cb155-3" aria-hidden="true" tabindex="-1"></a><span class="do">## report mean and spread of samples</span></span>
<span id="cb155-4"><a href="comparing-two-groups-of-observations.html#cb155-4" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">posterior_summary</span> (adult_mean)</span></code></pre></div>
<pre><code>##      Estimate Est.Error     Q2.5    Q97.5
## [1,] 220.4394  2.871496 214.8694 226.2171</code></pre>
<p>Luckily, there is a function in <code>brms</code> called <code>hypothesis</code> that helps us add terms very easily, without having to do any of the above steps. You can ask the <code>hypothesis</code> function to add terms in your model (spelled just as they are in the print statement), and to compare the result to some number. If you compare the result to 0, it just tells you about the result of the terms you added.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="comparing-two-groups-of-observations.html#cb157-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">hypothesis</span>(model_sum_coding, <span class="st">&quot;Intercept + adult1 = 0&quot;</span>)</span></code></pre></div>
<pre><code>## Hypothesis Tests for class b:
##               Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio
## 1 (Intercept+adult1) = 0   220.44      2.87   214.87   226.22         NA
##   Post.Prob Star
## 1        NA    *
## ---
## &#39;CI&#39;: 90%-CI for one-sided and 95%-CI for two-sided hypotheses.
## &#39;*&#39;: For one-sided hypotheses, the posterior probability exceeds 95%;
## for two-sided hypotheses, the value tested against lies outside the 95%-CI.
## Posterior probabilities of point hypotheses assume equal prior probabilities.</code></pre>
<p>The output above tells us what our estimate is for <code>Intercept + adult1</code>, which we know to be the expected mean f0 for adult females. Whereas the credible interval for the original effect reflected uncertainty in difference between means, the credible interval provided is now for the actual girl’s mean, not for the difference between the means.</p>
<p>We can use the hypothesis function to confirm similar results for the model fit using treatment coding. In that model, the reference category was the adult mean. So, if we call the <code>hypothesis</code> function on the intercept of the treatment-coding model, we can see that it will present similar values to those seen above.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="comparing-two-groups-of-observations.html#cb159-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">hypothesis</span>(model, <span class="st">&quot;Intercept = 0&quot;</span>)</span></code></pre></div>
<pre><code>## Hypothesis Tests for class b:
##        Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio Post.Prob
## 1 (Intercept) = 0   220.47       2.8    215.1   226.16         NA        NA
##   Star
## 1    *
## ---
## &#39;CI&#39;: 90%-CI for one-sided and 95%-CI for two-sided hypotheses.
## &#39;*&#39;: For one-sided hypotheses, the posterior probability exceeds 95%;
## for two-sided hypotheses, the value tested against lies outside the 95%-CI.
## Posterior probabilities of point hypotheses assume equal prior probabilities.</code></pre>
<p>We can check several parameter combinations simultaneously. Below I recreate all our mean estimates of interest, first for the sum coding model, and then for the treatment coding model. Notice that these models contain the same information, just represented in different ways.</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="comparing-two-groups-of-observations.html#cb161-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">hypothesis</span>(model_sum_coding, </span>
<span id="cb161-2"><a href="comparing-two-groups-of-observations.html#cb161-2" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">c</span>(<span class="st">&quot;Intercept = 0&quot;</span>,   <span class="co"># overall mean</span></span>
<span id="cb161-3"><a href="comparing-two-groups-of-observations.html#cb161-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;Intercept + adult1 = 0&quot;</span>,  <span class="co"># adult mean</span></span>
<span id="cb161-4"><a href="comparing-two-groups-of-observations.html#cb161-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;Intercept - adult1 = 0&quot;</span>)) <span class="co"># child mean</span></span></code></pre></div>
<pre><code>## Hypothesis Tests for class b:
##               Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio
## 1        (Intercept) = 0   229.33      2.71   224.07   234.81         NA
## 2 (Intercept+adult1) = 0   220.44      2.87   214.87   226.22         NA
## 3 (Intercept-adult1) = 0   238.22      4.53   229.34   247.13         NA
##   Post.Prob Star
## 1        NA    *
## 2        NA    *
## 3        NA    *
## ---
## &#39;CI&#39;: 90%-CI for one-sided and 95%-CI for two-sided hypotheses.
## &#39;*&#39;: For one-sided hypotheses, the posterior probability exceeds 95%;
## for two-sided hypotheses, the value tested against lies outside the 95%-CI.
## Posterior probabilities of point hypotheses assume equal prior probabilities.</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="comparing-two-groups-of-observations.html#cb163-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">hypothesis</span>(model, </span>
<span id="cb163-2"><a href="comparing-two-groups-of-observations.html#cb163-2" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">c</span>(<span class="st">&quot;Intercept + adultchild/2 = 0&quot;</span>,   <span class="co"># overall mean</span></span>
<span id="cb163-3"><a href="comparing-two-groups-of-observations.html#cb163-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;Intercept = 0&quot;</span>,  <span class="co"># adult mean</span></span>
<span id="cb163-4"><a href="comparing-two-groups-of-observations.html#cb163-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;Intercept + adultchild = 0&quot;</span>)) <span class="co"># child mean</span></span></code></pre></div>
<pre><code>## Hypothesis Tests for class b:
##                 Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio
## 1 (Intercept+adultc... = 0   229.28      2.69   224.19   234.74         NA
## 2          (Intercept) = 0   220.47      2.80   215.10   226.16         NA
## 3 (Intercept+adultc... = 0   238.10      4.51   229.41   247.26         NA
##   Post.Prob Star
## 1        NA    *
## 2        NA    *
## 3        NA    *
## ---
## &#39;CI&#39;: 90%-CI for one-sided and 95%-CI for two-sided hypotheses.
## &#39;*&#39;: For one-sided hypotheses, the posterior probability exceeds 95%;
## for two-sided hypotheses, the value tested against lies outside the 95%-CI.
## Posterior probabilities of point hypotheses assume equal prior probabilities.</code></pre>
<p>If I were writing this is in a paper, at this point I could present this information in a paragraph. Based on the sum coded model, I would say something like:</p>
<p>“The overall mean f0 across all speakers was 229 Hz (sd = 2.7, 95% CI = 224, 234). Adult female mean f0 was 220 Hz (sd = 2.9, 95% CI = [215, 226]), while the mean f0 for girls was 228 Hz (sd = 4.28, 95% CI = [230, 246]). The difference between the group means was 18 Hz on average (sd = 5.3, 95% CI = [7, 28]), suggesting a small but noisy difference between groups, on average.”</p>
</div>
</div>
<div id="random-effects" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> ‘Random’ Effects</h2>
<p>Below I present the speaker boxplot, with different colors for each group. So far we have discussed the speaker-dependent deviations from averages, but we haven’t actually done anything with them. One of the nice things about multilevel models is that we can actually estimate these parameters, and use them to answer our research questions.</p>
<p><img src="week-3_files/figure-html/unnamed-chunk-22-1.png" width="768" /></p>
<p>Multilevel models are sometimes also called ‘random effects’ or ‘mixed effects’ models. What is ‘mixed’ about them? Researchers often talk about whether effects are ‘fixed’ or ‘random’. The general idea is that ‘fixed’ effects are specifically chosen from a small set of possibilities, and we are not necessarily interested in the ‘other’ levels.</p>
<p>For example, in this experiment we include children 10-12 and adults. Speaker age-groups don’t really come from an infinite set of independent age-groups, not ones that will meaningfully affect our research questions anyways. Instead, categories like ‘adult’ and ‘child’ are chosen from a finite set of meaningful categories, and we are <em>specifically</em> interested in the categories we’ve chosen. In this case, I really do care about mean f0 for adults and not some other category I didn’t sample.</p>
<p>In contrast, ‘random’ effects are not chosen arbitrarily but at random. The speakers in our sample <em>do</em> form part of a practically infinite sample. I am actually <em>not</em> interested in the speakers I have but in what this says about the categories I did not include. In fact, most researchers would gladly trade perfect knowledge about any one speaker for even a small amount knowledge about a large set of speakers from the population.</p>
<p>Despite this primarily philosophical definition, in practice the terms ‘fixed’ and ‘random’ effects have <a href="https://statmodeling.stat.columbia.edu/2005/01/25/why_i_dont_use/">several inconsistent and sometimes contradictory definitions</a>.</p>
<p>Luckily, when thinking about these concepts in terms of multilevel models we can be very specific: ‘random’ effects are those for which we estimate a standard deviation term. So, we treat differences in speaker average f0 (<span class="math inline">\(\gamma_{speaker}\)</span>) as a variable, and estimate <span class="math inline">\(\sigma_{speaker}\)</span> for the distribution of variable.</p>
<div id="random-effects-priors-and-pooling" class="section level3" number="3.5.1">
<h3><span class="header-section-number">3.5.1</span> Random effects, priors and pooling</h3>
<p>Look at the list of priors in our latest model definition. If you look at our latest <code>brm</code> model fit, you will see where most of these are specifically defined in the function call. However, you will notice that the standard deviation of the prior (<span class="math inline">\(\sigma_{speakers}\)</span>) for the speaker-specific intercept deviations (<span class="math inline">\(\alpha_{speaker}\)</span>) is actually not specifically defined in the model.</p>
<p><span class="math display">\[\begin{equation}
\begin{split}
\textrm{Priors:} \\
\alpha_{speaker} \sim \mathcal{N}(0,\sigma_{speaker}) \\ \\ 
Intercept \sim t(3, 225.5, 48) \\ 
adult1 \sim t(3, 225.5, 48) \\ 
\sigma_{error} \sim t(3, 0, 48) \\
\sigma_{speaker} \sim t(3, 0, 48) \\ 
\end{split}
\end{equation}\]</span></p>
<p>It turns out that the <span class="math inline">\(\sigma_{speaker}\)</span> parameter is estimated from the data! For this reason, the prior you set on <span class="math inline">\(\sigma_{speaker}\)</span> is sometimes called a ‘hyperprior’, because it is the prior for your prior!</p>
<p>By definition, the speaker effects are centered around 0 (the average). The only question is, how widely are they distributed? Well, what better way to answer this question than using the distribution evident in the data itself? This means that the amount of variation you expect between speakers is based on the amount of between-speaker variation you observe. The idea is basically: is it believable that this one person be this far away from the ‘average’? Well, it depends on what everyone else looks like!</p>
<p>By estimating the prior for some parameters from the data itself, multilevel models can help <a href="http://www.stat.columbia.edu/~gelman/research/published/multiple2f.pdf">protect against problems that naturally arise when researchers compare many things</a>. This is because in a Bayesian analysis, the prior influences the estimates of your individual parameters. As a result, the variation in the <em>other</em> parameters in your sample can influence any given parameter.</p>
<p>This process is sometimes referred to as ‘partial pooling’, since it refers to the partial pooling of information across subjects. Using partial pooling means the subject estimates are neither completely independent nor totally merged. They actually end up influencing each other in a logical manner. Broadly speaking, individual observations that deviate from ‘typical’ values of the population are maintained when there is good enough evidence for them. When there is wak evidence for them relative to the other observations in the sample, estimates may be brought closer to the group averages. As a result, partial pooling results in what is sometimes called ‘shrinkage’, because extreme values get ‘shrunk’ towards the overall mean.</p>
<p>In the context of a Bayesian multilevel model ‘random effects’ are those you estimate with partial pooling, where the prior is estimated from the data (e.g., <span class="math inline">\(\sigma_{speaker}\)</span>). In contrast, ‘fixed effects’ are those predictors for which you set arbitrary priors before fitting the model.</p>
<p>Although the terms terms ‘fixed’ and ‘random’ effects are useful (and I continue to use them to describe my models), it is important to keep in mind that the philosophical distinction between ‘fixed’ and ‘random’ variables is not relevant for the models we are discussing here. The real distinction is: do I want to fit every level totally independently as if there were all unrelated? Or do I want to use partial pooling in my estimates, thereby using all of the information present in my sample to protect against spurious findings?</p>
<p>In general, when you have many levels of a factor, it may be a good idea to include these as ‘random’ effects. There is not much downside to it, you get more information from the model (e.g., information about <span class="math inline">\(\sigma_{predictor}\)</span>), and you can always fit multiple models to see what, if any differences, result form the different approaches.</p>
<p>Some useful things to consider are also: Do you believe that treating a predictor as a ‘random’ effect offers a modeling advantage? Does it better reflect the process/relationships you are trying to understand? Does it provide you with information you find useful? Is it realistic to fit this kind of model given the amount of data you have, and the nature of the relationships in the data? Right now the last point is not something we have talked about very much, but it is something we will need to worry about more as our models become more complicated.</p>
</div>
<div id="inspecting-the-random-effects" class="section level3" number="3.5.2">
<h3><span class="header-section-number">3.5.2</span> Inspecting the random effects</h3>
<p>The <code>brms</code> package has several functions to help understand our ‘random’ effects. There is a function called <code>ranef</code> which returns random effects estimates in the same way that <code>fixef</code> provides fixed effects estimates. The leftmost column of the output below represents the estimated effects associated with each speaker average value.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="comparing-two-groups-of-observations.html#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="do">## I am telling it to give me the &#39;speaker&#39; Intercepts, but only the first </span></span>
<span id="cb165-2"><a href="comparing-two-groups-of-observations.html#cb165-2" aria-hidden="true" tabindex="-1"></a><span class="do">## 10 rows. This is just so it doesn&#39;t take up the whole page.</span></span>
<span id="cb165-3"><a href="comparing-two-groups-of-observations.html#cb165-3" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">ranef</span> (model_sum_coding)<span class="sc">$</span>speaker[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,,<span class="st">&quot;Intercept&quot;</span>]</span></code></pre></div>
<pre><code>## NULL</code></pre>
<p>Notice that the speaker averages vary around 0, and some are even negative. That is because the speaker effects (and all random effects) are coded using sum-coding. So, what the speaker-specific mean terms tell us is: what is the average value for this speaker, relative to the overall average, and the group specific adjustment? Keep in mind, since our model encodes both the overall average <em>and</em> the group means, the speaker-effects encode differences to the group means and not to the overall means.</p>
<p>For example, we see that the mean for the second speaker above is -19.8 Hz. This means that they have a lower f0 than ‘expected’, and their mean f0 is 19.8 Hz lower than their group mean f0. In contrast, the first speaker has a speaker mean effect that is nearly zero (1.1). That tells you that this speaker’s mean f0 was nearly the same as that of the average for their group</p>
<p>We can use a simple plotting function I wrote to look at the distribution of speaker effects terms. The function takes in the summaries made by brms and plots a point for each parameter mean, and lines indicating the credible intervals calculated by <code>brm</code> (usually 95% credible intervals).</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="comparing-two-groups-of-observations.html#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span> (<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb167-2"><a href="comparing-two-groups-of-observations.html#cb167-2" aria-hidden="true" tabindex="-1"></a><span class="fu">brmplot</span>( brms<span class="sc">::</span><span class="fu">ranef</span> (model_sum_coding)[[<span class="st">&quot;uspeaker&quot;</span>]][,,<span class="st">&quot;Intercept&quot;</span>], <span class="at">col =</span> colors)</span>
<span id="cb167-3"><a href="comparing-two-groups-of-observations.html#cb167-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span> (<span class="at">h=</span><span class="dv">0</span>)</span></code></pre></div>
<p><img src="week-3_files/figure-html/unnamed-chunk-24-1.png" width="768" /></p>
<p>We can compare the estimates of by-speaker intercepts to the distribution of actual data arranged by subject. There is clearly a close correspondence!</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="comparing-two-groups-of-observations.html#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="do">## plot comparison of estimates of speaker means to actual data</span></span>
<span id="cb168-2"><a href="comparing-two-groups-of-observations.html#cb168-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span> (<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb168-3"><a href="comparing-two-groups-of-observations.html#cb168-3" aria-hidden="true" tabindex="-1"></a><span class="fu">brmplot</span>( brms<span class="sc">::</span><span class="fu">ranef</span> (model_sum_coding)[[<span class="st">&quot;uspeaker&quot;</span>]][,,<span class="st">&quot;Intercept&quot;</span>], </span>
<span id="cb168-4"><a href="comparing-two-groups-of-observations.html#cb168-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> colors)</span>
<span id="cb168-5"><a href="comparing-two-groups-of-observations.html#cb168-5" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span> (f0 <span class="sc">~</span> speaker, <span class="at">data=</span>females, <span class="at">col =</span> colors, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">150</span>,<span class="dv">310</span>))</span></code></pre></div>
<p><img src="week-3_files/figure-html/unnamed-chunk-25-1.png" width="768" /></p>
</div>
</div>
<div id="but-what-does-it-all-mean" class="section level2" number="3.6">
<h2><span class="header-section-number">3.6</span> But what does it all mean?</h2>
<p>Ok, so are the f0s produced by women and girls different? Consider the distribution of productions between and within speakers and groups, as shown in the figure below (lines represent the group means). An unbiased look at our results (and figures) so far suggests that:</p>
<p><img src="week-3_files/figure-html/unnamed-chunk-26-1.png" width="768" /></p>
<ul>
<li><p>the magnitude of between speaker variation is <strong>larger</strong> than the difference between girls and women (19 Hz vs 18/17 Hz). This means that random people drawn from the two groups largely overlap.</p></li>
<li><p>the magnitude of within-speaker variation (12 Hz) is almost as large as the group difference and the between-speaker difference! This means that two random productions from two different people might be the same, even when the speakers average f0s are quite different.</p></li>
</ul>
<p>And yet:</p>
<ul>
<li><p>the mean f0 <strong>is</strong> reliably different between women and girls, and there are well-known anatomical reasons for this that are expected a priori (i.e., adult females are larger than younger women, larger speakers often produce lower f0s).</p></li>
<li><p>the between-speaker differences are ‘random’ from person to person, but systematic for a given person.</p></li>
<li><p>even the within-speaker variation may be systematic given a more-complicated model.</p></li>
</ul>
<p>So are they different yes or no? Statistics aside, a fair assessment of our data suggests that neither binary conclusion is fully supported: they are distinguishable but overlap substantially. If you want to use this model to highlight the differences between girls and women, I think it is valid. I also think it would be valid to use this data to talk about between and within-speaker variation, highlighting the overlap that exists between speakers. Both are true! To a large extent, the meaning is as much in our heads as it is in the model, and we are free to interpret the results as we see fit, as long as reviewers (and readers in general) will believe us. The model is simply a reflection of the relationships in our data, and the interpretation is up to us.</p>
<p>Keep in mind that the “as long as reviewers (and readers in general) will believe us” component is crucial. The results of the model will need to be interpreted in the larger context of the work it is presented in, and in terms of scientific and general knowledge that readers have. The results of any model will need to ‘make sense’ given this, and a statistical result on its own will not be enough to make people (including us) believe outlandish, or even weakly supported claims.</p>
<p>The model is not reality and should not be confused with reality. This is a very important point! A statistical finding does not <em>prove</em> that something is <em>true</em>. This kind of thinking has <a href="https://slate.com/health-and-science/2017/06/daryl-bem-proved-esp-is-real-showed-science-is-broken.html">caused many problems for researchers in the social sciences recently</a>. In general, we can imagine that 10 people might approach any given research question in 10 different ways, a concept known as <a href="https://en.wikipedia.org/wiki/Researcher_degrees_of_freedom">researcher degrees of freedom</a>. This would cause slight differences in their results, resulting in a sort of ‘distribution’ for any given result. How can a fixed underlying reality result in a distribution or results? When they are all slightly wrong!</p>
<p>For example, we know for a fact that f0 varies, weakly but systematically, across vowel categories, a concept known as <a href="https://www.sciencedirect.com/science/article/abs/pii/S0095447095801650">intrinsic f0</a>. A model that included vowel category as a within-speaker predictor would reduce the apparent error in our model (making <span class="math inline">\(sigma_{error}\)</span> smaller), and might affect the precision of our other estimates. Would this new model invalidate our current model? Answering yes to this question is generally problematic because there is <em>always</em> a better model out there, and so every model is automatically invalid.</p>
<p>The solution is to think of your model not as a mathematical implementation of <em>reality</em> but instead as a mathematical implementation of your research questions. Your model should include the information and structure that you think are necessary to represent and investigate your questions.</p>
<p>Using a different model can result in different results given the same data, but asking a different question can also lead to different results given then same data! One of my favorite phrases to use is “given our data and model structure”. This phrase is helpful because it highlights the fact that your results are contingent on:</p>
<ol style="list-style-type: decimal">
<li><p>the data you collected. Given other data you may have come to other conclusions.</p></li>
<li><p>the model you chose. Given another model you may have come to other conclusions.</p></li>
</ol>

</div>
</div>
<!-- Default Statcounter code for statsbook
https://santiagobarreda.github.io/stats-class/ -->
<script type="text/javascript">
var sc_project=12454226; 
var sc_invisible=1; 
var sc_security="a1959418"; 
</script>
<script type="text/javascript"
src="https://www.statcounter.com/counter/counter.js"
async></script>
<noscript><div class="statcounter"><a title="Web Analytics"
href="https://statcounter.com/" target="_blank"><img
class="statcounter"
src="https://c.statcounter.com/12454226/0/a1959418/1/"
alt="Web Analytics"></a></div></noscript>
<!-- End of Statcounter Code -->
            </section>

          </div>
        </div>
      </div>
<a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="comparing-many-groups.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
