<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Comparing many groups: ANOVA and interactions | Bayesian multilevel models in R: A conceptual and practical introduction for linguists</title>
  <meta name="description" content="Bayesian Models for Linguists" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Comparing many groups: ANOVA and interactions | Bayesian multilevel models in R: A conceptual and practical introduction for linguists" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://santiagobarreda.com" />
  
  <meta property="og:description" content="Bayesian Models for Linguists" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Comparing many groups: ANOVA and interactions | Bayesian multilevel models in R: A conceptual and practical introduction for linguists" />
  
  <meta name="twitter:description" content="Bayesian Models for Linguists" />
  

<meta name="author" content="Santiago Bareda" />


<meta name="date" content="2021-07-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="comparing-two-groups-of-observations-factors-and-contrasts.html"/>
<link rel="next" href="continuous-predictors-and-their-interactions-with-factors.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bayesian Models for Linguists</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><i class="fa fa-check"></i><b>1</b> Inspecting a single group of observations: Introduction to regression models</a>
<ul>
<li class="chapter" data-level="1.1" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#data-and-research-questions"><i class="fa fa-check"></i><b>1.1</b> Data and research questions</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#inspecting-the-central-location-and-spread-of-values"><i class="fa fa-check"></i><b>1.1.1</b> Inspecting the central location and spread of values</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#probability-distributions"><i class="fa fa-check"></i><b>1.2</b> Probability Distributions</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#the-normal-distribution"><i class="fa fa-check"></i><b>1.2.1</b> The normal distribution</a></li>
<li class="chapter" data-level="1.2.2" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#referring-to-the-normal-distribution-to-make-inferences"><i class="fa fa-check"></i><b>1.2.2</b> Referring to the normal distribution to make inferences</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#probabilities-of-events-and-likelihoods-of-parameters"><i class="fa fa-check"></i><b>1.3</b> Probabilities of events and likelihoods of parameters</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#calculating-likelihood-functions"><i class="fa fa-check"></i><b>1.3.1</b> Calculating likelihood functions</a></li>
<li class="chapter" data-level="1.3.2" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#making-inferences-using-likelihoods"><i class="fa fa-check"></i><b>1.3.2</b> Making inferences using likelihoods</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#bayesian-models"><i class="fa fa-check"></i><b>1.4</b> Bayesian models</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#what-are-regression-models"><i class="fa fa-check"></i><b>1.4.1</b> What are regression models?</a></li>
<li class="chapter" data-level="1.4.2" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#whats-bayesian-about-these-models"><i class="fa fa-check"></i><b>1.4.2</b> What’s ‘Bayesian’ about these models?</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#posterior-distributions"><i class="fa fa-check"></i><b>1.5</b> Posterior distributions</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#sampling-from-the-posterior"><i class="fa fa-check"></i><b>1.5.1</b> Sampling from the posterior</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="inspecting-a-single-group-of-observations-introduction-to-regression-models.html"><a href="inspecting-a-single-group-of-observations-introduction-to-regression-models.html#exercises"><i class="fa fa-check"></i><b>1.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><i class="fa fa-check"></i><b>2</b> Inspecting a ‘single group’ of observations using a Bayesian multilevel model</a>
<ul>
<li class="chapter" data-level="2.1" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#data-and-research-questions-1"><i class="fa fa-check"></i><b>2.1</b> Data and research questions</a></li>
<li class="chapter" data-level="2.2" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#estimating-a-single-mean-with-the-brms-package"><i class="fa fa-check"></i><b>2.2</b> Estimating a single mean with the <code>brms</code> package</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#description-of-the-model"><i class="fa fa-check"></i><b>2.2.1</b> Description of the model</a></li>
<li class="chapter" data-level="2.2.2" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#the-model-formula"><i class="fa fa-check"></i><b>2.2.2</b> The model formula</a></li>
<li class="chapter" data-level="2.2.3" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#fitting-the-model-calling-the-brm-function"><i class="fa fa-check"></i><b>2.2.3</b> Fitting the model: Calling the <code>brm</code> function</a></li>
<li class="chapter" data-level="2.2.4" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#interpreting-the-model-the-print-statement"><i class="fa fa-check"></i><b>2.2.4</b> Interpreting the model: the print statement</a></li>
<li class="chapter" data-level="2.2.5" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#seeing-the-samples"><i class="fa fa-check"></i><b>2.2.5</b> Seeing the samples</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#repeated-measures-data"><i class="fa fa-check"></i><b>2.3</b> Repeated measures data</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#multilevel-models"><i class="fa fa-check"></i><b>2.3.1</b> Multilevel models</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#estimating-a-multilevel-model-with-brms"><i class="fa fa-check"></i><b>2.4</b> Estimating a multilevel model with <code>brms</code></a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#description-of-the-model-1"><i class="fa fa-check"></i><b>2.4.1</b> Description of the model</a></li>
<li class="chapter" data-level="2.4.2" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#fitting-the-model"><i class="fa fa-check"></i><b>2.4.2</b> Fitting the model</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#checking-model-convergence"><i class="fa fa-check"></i><b>2.5</b> Checking model convergence</a></li>
<li class="chapter" data-level="2.6" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#specifying-prior-probabilities"><i class="fa fa-check"></i><b>2.6</b> Specifying prior probabilities</a></li>
<li class="chapter" data-level="2.7" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#answering-our-research-questions"><i class="fa fa-check"></i><b>2.7</b> Answering our research questions</a></li>
<li class="chapter" data-level="2.8" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#simulating-data-using-our-model-parameters"><i class="fa fa-check"></i><b>2.8</b> Simulating data using our model parameters</a></li>
<li class="chapter" data-level="2.9" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#frequentist-corner"><i class="fa fa-check"></i><b>2.9</b> Frequentist corner</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#bayesian-multilevel-modesl-vs.-lmer"><i class="fa fa-check"></i><b>2.9.1</b> Bayesian multilevel modesl vs. lmer</a></li>
<li class="chapter" data-level="2.9.2" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#bayesian-multilevel-modesl-vs.-the-one-sample-t-test"><i class="fa fa-check"></i><b>2.9.2</b> Bayesian multilevel modesl vs. the one-sample t-test</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html"><a href="inspecting-a-single-group-of-observations-using-a-bayesian-multilevel-model.html#exercises-1"><i class="fa fa-check"></i><b>2.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html"><i class="fa fa-check"></i><b>3</b> Comparing two groups of observations: Factors and contrasts</a>
<ul>
<li class="chapter" data-level="3.1" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#data-and-research-questions-2"><i class="fa fa-check"></i><b>3.1</b> Data and research questions</a></li>
<li class="chapter" data-level="3.2" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#estimating-the-difference-between-two-means-with-brms"><i class="fa fa-check"></i><b>3.2</b> Estimating the difference between two means with ‘brms’</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#fitting-the-model-1"><i class="fa fa-check"></i><b>3.2.1</b> Fitting the model</a></li>
<li class="chapter" data-level="3.2.2" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#interpreting-the-model"><i class="fa fa-check"></i><b>3.2.2</b> Interpreting the model</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#contrasts"><i class="fa fa-check"></i><b>3.3</b> Contrasts</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#treatment-coding"><i class="fa fa-check"></i><b>3.3.1</b> Treatment coding</a></li>
<li class="chapter" data-level="3.3.2" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#sum-coding"><i class="fa fa-check"></i><b>3.3.2</b> Sum coding</a></li>
<li class="chapter" data-level="3.3.3" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#comparison-of-sum-and-treatment-coding"><i class="fa fa-check"></i><b>3.3.3</b> Comparison of sum and treatment coding</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#refitting-the-model-with-sum-coding"><i class="fa fa-check"></i><b>3.4</b> Refitting the model with sum coding</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#fitting-the-model-2"><i class="fa fa-check"></i><b>3.4.1</b> Fitting the model</a></li>
<li class="chapter" data-level="3.4.2" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#description-of-the-model-2"><i class="fa fa-check"></i><b>3.4.2</b> Description of the model</a></li>
<li class="chapter" data-level="3.4.3" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#interpreting-the-model-1"><i class="fa fa-check"></i><b>3.4.3</b> Interpreting the model</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#random-effects"><i class="fa fa-check"></i><b>3.5</b> ‘Random’ Effects</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#random-effects-priors-and-pooling"><i class="fa fa-check"></i><b>3.5.1</b> Random effects, priors and pooling</a></li>
<li class="chapter" data-level="3.5.2" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#inspecting-the-random-effects"><i class="fa fa-check"></i><b>3.5.2</b> Inspecting the random effects</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#but-what-does-it-all-mean"><i class="fa fa-check"></i><b>3.6</b> But what does it all mean?</a></li>
<li class="chapter" data-level="3.7" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#simulating-the-two-group-model"><i class="fa fa-check"></i><b>3.7</b> Simulating the two-group model</a></li>
<li class="chapter" data-level="3.8" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#frequentist-corner-1"><i class="fa fa-check"></i><b>3.8</b> Frequentist corner</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#bayesian-multilevel-modesl-vs.-lmer-1"><i class="fa fa-check"></i><b>3.8.1</b> Bayesian multilevel modesl vs. lmer</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="comparing-two-groups-of-observations-factors-and-contrasts.html"><a href="comparing-two-groups-of-observations-factors-and-contrasts.html#exercises-2"><i class="fa fa-check"></i><b>3.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html"><i class="fa fa-check"></i><b>4</b> Comparing many groups: ANOVA and interactions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#data-and-research-questions-3"><i class="fa fa-check"></i><b>4.1</b> Data and research questions</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#factors-as-batches-effects"><i class="fa fa-check"></i><b>4.1.1</b> Factors as ‘batches’ effects</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#comparing-four-or-any-number-of-groups"><i class="fa fa-check"></i><b>4.2</b> Comparing four (or any number of) groups</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#the-model"><i class="fa fa-check"></i><b>4.2.1</b> The model</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#investigating-many-factors-simultaneously-analysis-of-variance"><i class="fa fa-check"></i><b>4.3</b> Investigating many factors simultaneously: Analysis of Variance</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#description-of-the-model-3"><i class="fa fa-check"></i><b>4.3.1</b> Description of the model</a></li>
<li class="chapter" data-level="4.3.2" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#fitting-the-model-and-interpreting-the-results"><i class="fa fa-check"></i><b>4.3.2</b> Fitting the model and interpreting the results</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#investigating-model-fit"><i class="fa fa-check"></i><b>4.4</b> Investigating model fit</a></li>
<li class="chapter" data-level="4.5" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#interactions-and-interaction-plots"><i class="fa fa-check"></i><b>4.5</b> Interactions and interaction plots</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#interactions-in-our-f0-data"><i class="fa fa-check"></i><b>4.5.1</b> Interactions in our f0 data</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#investigating-interactions-with-a-model"><i class="fa fa-check"></i><b>4.6</b> Investigating interactions with a model</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#fitting-the-model-and-interpreting-the-results-1"><i class="fa fa-check"></i><b>4.6.1</b> Fitting the model and interpreting the results</a></li>
<li class="chapter" data-level="4.6.2" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#assessing-model-fit"><i class="fa fa-check"></i><b>4.6.2</b> Assessing model fit</a></li>
<li class="chapter" data-level="4.6.3" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#making-plots"><i class="fa fa-check"></i><b>4.6.3</b> Making plots</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#frequentist-corner-2"><i class="fa fa-check"></i><b>4.7</b> Frequentist corner</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#bayesian-multilevel-modesl-vs.-lmer-2"><i class="fa fa-check"></i><b>4.7.1</b> Bayesian multilevel modesl vs. lmer</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="comparing-many-groups-anova-and-interactions.html"><a href="comparing-many-groups-anova-and-interactions.html#exercises-3"><i class="fa fa-check"></i><b>4.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html"><i class="fa fa-check"></i><b>5</b> Continuous predictors and their interactions with factors</a>
<ul>
<li class="chapter" data-level="5.1" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#data-and-research-questions-4"><i class="fa fa-check"></i><b>5.1</b> Data and research questions</a></li>
<li class="chapter" data-level="5.2" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#continuous-predictors-modeling-variation-along-lines"><i class="fa fa-check"></i><b>5.2</b> Continuous predictors: modeling variation along lines</a></li>
<li class="chapter" data-level="5.3" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#models-with-a-single-slope-and-intercept"><i class="fa fa-check"></i><b>5.3</b> Models with a single slope and intercept</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#description-of-the-model-4"><i class="fa fa-check"></i><b>5.3.1</b> Description of the model</a></li>
<li class="chapter" data-level="5.3.2" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#fitting-the-model-3"><i class="fa fa-check"></i><b>5.3.2</b> Fitting the model</a></li>
<li class="chapter" data-level="5.3.3" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#interpreting-the-model-2"><i class="fa fa-check"></i><b>5.3.3</b> Interpreting the model</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#centering-predictors"><i class="fa fa-check"></i><b>5.4</b> Centering predictors</a></li>
<li class="chapter" data-level="5.5" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#interactions-in-our-line-parameters"><i class="fa fa-check"></i><b>5.5</b> Interactions in our line parameters</a></li>
<li class="chapter" data-level="5.6" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#models-with-group-dependent-intercepts-but-shared-slopes"><i class="fa fa-check"></i><b>5.6</b> Models with group-dependent intercepts, but shared slopes</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#description-of-the-model-5"><i class="fa fa-check"></i><b>5.6.1</b> Description of the model</a></li>
<li class="chapter" data-level="5.6.2" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#fitting-the-model-4"><i class="fa fa-check"></i><b>5.6.2</b> Fitting the model</a></li>
<li class="chapter" data-level="5.6.3" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#the-effect-of-including-a-slope"><i class="fa fa-check"></i><b>5.6.3</b> The effect of including a slope</a></li>
<li class="chapter" data-level="5.6.4" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#interpreting-group-effects-in-the-presence-of-a-continuous-predictor"><i class="fa fa-check"></i><b>5.6.4</b> Interpreting group effects in the presence of a continuous predictor</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#models-with-group-dependent-slopes-and-intercepts"><i class="fa fa-check"></i><b>5.7</b> Models with group-dependent slopes and intercepts</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#description-of-the-model-6"><i class="fa fa-check"></i><b>5.7.1</b> Description of the model</a></li>
<li class="chapter" data-level="5.7.2" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#fitting-the-model-5"><i class="fa fa-check"></i><b>5.7.2</b> Fitting the model</a></li>
<li class="chapter" data-level="5.7.3" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#interpreting-the-model-3"><i class="fa fa-check"></i><b>5.7.3</b> Interpreting the model</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="continuous-predictors-and-their-interactions-with-factors.html"><a href="continuous-predictors-and-their-interactions-with-factors.html#exercises-4"><i class="fa fa-check"></i><b>5.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html"><i class="fa fa-check"></i><b>6</b> Random slopes and multiple random effects</a>
<ul>
<li class="chapter" data-level="6.1" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#data-and-research-questions-5"><i class="fa fa-check"></i><b>6.1</b> Data and research questions</a></li>
<li class="chapter" data-level="6.2" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#repeated-measures-and-speaker-dependent-parameter-values"><i class="fa fa-check"></i><b>6.2</b> Repeated measures and speaker-dependent parameter values</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#description-of-the-model-7"><i class="fa fa-check"></i><b>6.2.1</b> Description of the model</a></li>
<li class="chapter" data-level="6.2.2" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#fitting-the-model-6"><i class="fa fa-check"></i><b>6.2.2</b> Fitting the model</a></li>
<li class="chapter" data-level="6.2.3" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#interpreting-the-model-4"><i class="fa fa-check"></i><b>6.2.3</b> Interpreting the model</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#random-effects-and-the-multivariate-normal-distribution"><i class="fa fa-check"></i><b>6.3</b> Random effects and the multivariate normal distribution</a></li>
<li class="chapter" data-level="6.4" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#random-slopes"><i class="fa fa-check"></i><b>6.4</b> Random slopes</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#description-of-the-model-8"><i class="fa fa-check"></i><b>6.4.1</b> Description of the model</a></li>
<li class="chapter" data-level="6.4.2" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#fitting-the-model-7"><i class="fa fa-check"></i><b>6.4.2</b> Fitting the model</a></li>
<li class="chapter" data-level="6.4.3" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#interpreting-the-model-5"><i class="fa fa-check"></i><b>6.4.3</b> Interpreting the model</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#more-predictors-and-more-random-slopes"><i class="fa fa-check"></i><b>6.5</b> More predictors and more random slopes</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#adding-another-random-slope"><i class="fa fa-check"></i><b>6.5.1</b> Adding another random slope</a></li>
<li class="chapter" data-level="6.5.2" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#adding-random-factors"><i class="fa fa-check"></i><b>6.5.2</b> Adding random factors</a></li>
<li class="chapter" data-level="6.5.3" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#the-independence-of-continuous-predictors"><i class="fa fa-check"></i><b>6.5.3</b> The independence of continuous predictors</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#answering-our-research-questions-1"><i class="fa fa-check"></i><b>6.6</b> Answering our research questions</a></li>
<li class="chapter" data-level="6.7" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#frequentist-corner-3"><i class="fa fa-check"></i><b>6.7</b> Frequentist corner</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#bayesian-multilevel-modesl-vs.-lmer-3"><i class="fa fa-check"></i><b>6.7.1</b> Bayesian multilevel modesl vs. lmer</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="random-slopes-and-multiple-random-effects.html"><a href="random-slopes-and-multiple-random-effects.html#exercises-5"><i class="fa fa-check"></i><b>6.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="plot-code.html"><a href="plot-code.html"><i class="fa fa-check"></i><b>7</b> Plot Code</a></li>
<li class="divider"></li>
<li><a href="http://www.santiagobarreda.com" target="blank">Written by Santiago Barreda</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Bayesian multilevel models in R: A conceptual and practical introduction for linguists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="comparing-many-groups-anova-and-interactions" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Comparing many groups: ANOVA and interactions</h1>
<p>Last chapter we talked about comparing two groups. Although the comparison of two groups is very simple, it also comes up often. In addition, more complicated problems are often broken down into several two-group questions. However, most real-world research designs don’t usually <em>begin</em> as two-group questions. In this chapter, we’re going to talk about the comparison of multiple groups of observations/speakers.</p>
<p>In terms of model design concepts, last chapter introduced the notion of <em>factors</em> and <em>coding</em>. In this chapter, we’re going to discuss how to build models with multiple factors, and how to allow these factors to <em>interact</em> in our models.</p>
<div id="data-and-research-questions-3" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Data and research questions</h2>
<p>First, we’re going to discuss models that compare observations across any number of groups (levels) for a single factor. These designs have just one predictor factor but it can have any number of levels. Although it is not very common to have a design that <em>only</em> consists of a multi-group comparison, the inclusion of multi-group comparisons is ubiquitous in linguistics. Examples of predictors with multiple levels are vowel phonemes, language, word classes, and ages. In addition, the manipulations linguists carry out in their experiments can vary across more than two groups.</p>
<p>For example, consider the example of the experiment investigating coffee in reading speed. We can continue discussing the hypothetical example of the reading experiment presented in Chapter 3. Subjects are asked to drink either a cup of water or a cup of coffee. After a 15-minute wait they are asked to read a passage aloud and the duration of the reading is measured. We might have 3 coffee groups rather than one, and vary the ‘dosage’ of coffee between groups. Although the dose of coffee can be measured numerically, we could still treat this as a factor called “drink” with levels “water”, “coffee100ml”, “coffee200ml”, and “coffee300ml”.</p>
<p>Let’s imagine that subjects were also divided into groups of male and female speakers. This design results in four different groups (2x2). These groups have an internal structure that our model does not recognize. What I mean by this is that half your groups are caffeine groups, but your model does not know this, and as a result it does not directly estimate any effects related to this. However, we will ignore this issue for now.</p>
<p>In the first example we see the <em>within-subjects</em> version of this design where each subject is tested at each level of <span class="math inline">\(A\)</span>. Next, we see the <em>between-subjects</em> version of the design. Clearly, this is just a simple extrapolation of the sorts of designs presented in Chapter 2.</p>
<div class="figure" style="text-align: center"><span id="fig:F4-designfig"></span>
<img src="images/design_ch4_1.png" alt="Data from a single group of subjects (S) divided according to a single grouping factor A." width="80%" />
<p class="caption">
Figure 4.1: Data from a single group of subjects (S) divided according to a single grouping factor A.
</p>
</div>
<p>To analyze data like this, you should have it in a dataframe with one row for each observation. Then, one column should contain the dependent variable, the variable whose variation you’re trying to predict. Another column should contain information about which group each observation belongs to (the factor).</p>
<p>We’re going to keep working with the Hillenbrand et al. data, that we have been discussing in every chapter to this point. This time we’re going to work with all four groups of speakers: <code>b</code> (boys), <code>g</code> (girls), <code>m</code> (men), and <code>w</code> (women).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="comparing-many-groups-anova-and-interactions.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load brms</span></span>
<span id="cb1-2"><a href="comparing-many-groups-anova-and-interactions.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span> (brms)</span>
<span id="cb1-3"><a href="comparing-many-groups-anova-and-interactions.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># load data from course website</span></span>
<span id="cb1-4"><a href="comparing-many-groups-anova-and-interactions.html#cb1-4" aria-hidden="true" tabindex="-1"></a>url1 <span class="ot">=</span> <span class="st">&quot;https://raw.githubusercontent.com/santiagobarreda/stats-class/master/data/&quot;</span></span>
<span id="cb1-5"><a href="comparing-many-groups-anova-and-interactions.html#cb1-5" aria-hidden="true" tabindex="-1"></a>h95 <span class="ot">=</span> <span class="fu">read.csv</span> (<span class="fu">url</span>(<span class="fu">paste0</span> (url1, <span class="st">&quot;03_h95_vowel_data.csv&quot;</span>)))</span></code></pre></div>
<p>Our potential research questions are substantially more complicated than in the two-group case. First, there are four groups now, meaning we could potentially make 6 2-group comparisons. Second, the groups differ along multiple dimensions, making it more difficult to make two-group comparisons that ask one single question. For example, the ‘man’ and ‘girl’ groups differ according to ‘adultness’ <em>and</em> ‘gender.’ How could we know what part of their f0 difference we should attribute to adultness and what part we should attribute to maleness?</p>
<div class="figure"><span id="fig:F4-datacomparison"></span>
<img src="04_files/figure-html/F4-datacomparison-1.png" alt="(left) Comparison of the four groups (middle) Comparison of productions based on whether the speaker is an adult (right) Comparison of all productions based on whether the speaker is male." width="768" />
<p class="caption">
Figure 4.2: (left) Comparison of the four groups (middle) Comparison of productions based on whether the speaker is an adult (right) Comparison of all productions based on whether the speaker is male.
</p>
</div>
<p>We can consider our data in several ways: as four independent groups, or as two 2-groups comparisons (adult vs child, female vs male). We’re going to focus on the 4-way comparison first, and later talk about models that make multiple comparisons simultaneously.</p>
<div class="figure"><span id="fig:F4-speakerboxplots"></span>
<img src="04_files/figure-html/F4-speakerboxplots-1.png" alt="(left) Boxplots presenting each speaker's production of f0 for boys (red), girls (yellow), men (green), and women (teal). (right) Densities of the overall distributions for each group." width="768" />
<p class="caption">
Figure 4.3: (left) Boxplots presenting each speaker’s production of f0 for boys (red), girls (yellow), men (green), and women (teal). (right) Densities of the overall distributions for each group.
</p>
</div>
<div id="factors-as-batches-effects" class="section level3" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Factors as ‘batches’ effects</h3>
<p>R treats nominal, categorical predictors as <em>factors</em> and assumes that each different label is a different group. Each group of a factor is called a <em>level</em>. Actually, we’ve been using factors all along because our <code>speaker</code> predictor is a factor and the individual participants are levels! As far as our models are concerned, participant/speaker/subject has no special status as a predictor and it is just a factor with many levels.</p>
<p>When you have groups in your model that are ‘thematically’ related, you can ‘batch’ them together in a factor. For example you may have 4 groups of speakers based on native language. You can treat these four groups as levels of a factor. Implicitly, this tells your model that these four groups are related somehow. You know that they are related by being first language groups. However, keep in mind your model ‘knows’ next to nothing. Actually, the way you tell your model that these groups are related is precisely by treating them as levels of the same factor rather than as unrelated groups.</p>
<p>For example, the same speakers might be divided into women and men. This would introduce two new levels into our design. However, should we just through men and women into the language factor: Italians, Germans, English, Russians, Men and Women? We could definitely do this, no one ill stop us. But this doesn’t make much <em>sense</em>. Instead, it makes sense to split these groups into two batches of levels: one factor with four language levels, and one factor with two gender levels.</p>
<p>A <code>factor</code> is actually a data type in R. It’s basically the same as a vector of words (or numbers!), but it has some additional properties that are useful. For example, consider our <code>group</code> predictor, which tells us which group each speaker falls into. Initially it is a character vector. We see that the first few tokens are produced by men (<code>m</code>), and that there is no numerical value associated with these letter labels. The <code>unique</code> function returns all unique labels in the vector, in the order that they appear in the vector.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="comparing-many-groups-anova-and-interactions.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># see the first 6 observations</span></span>
<span id="cb2-2"><a href="comparing-many-groups-anova-and-interactions.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> (h95<span class="sc">$</span>group)   </span>
<span id="cb2-3"><a href="comparing-many-groups-anova-and-interactions.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] &quot;b&quot; &quot;b&quot; &quot;b&quot; &quot;b&quot; &quot;b&quot; &quot;b&quot;</span></span>
<span id="cb2-4"><a href="comparing-many-groups-anova-and-interactions.html#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="comparing-many-groups-anova-and-interactions.html#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># class starts as a character vector</span></span>
<span id="cb2-6"><a href="comparing-many-groups-anova-and-interactions.html#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span> (h95<span class="sc">$</span>group)   </span>
<span id="cb2-7"><a href="comparing-many-groups-anova-and-interactions.html#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] &quot;character&quot;</span></span>
<span id="cb2-8"><a href="comparing-many-groups-anova-and-interactions.html#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="comparing-many-groups-anova-and-interactions.html#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># no numerical values</span></span>
<span id="cb2-10"><a href="comparing-many-groups-anova-and-interactions.html#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> (<span class="fu">as.numeric</span> (h95<span class="sc">$</span>group))  </span>
<span id="cb2-11"><a href="comparing-many-groups-anova-and-interactions.html#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Warning in head(as.numeric(h95$group)): NAs introduced by coercion</span></span>
<span id="cb2-12"><a href="comparing-many-groups-anova-and-interactions.html#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] NA NA NA NA NA NA</span></span>
<span id="cb2-13"><a href="comparing-many-groups-anova-and-interactions.html#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="comparing-many-groups-anova-and-interactions.html#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># we can see the number of unique groups</span></span>
<span id="cb2-15"><a href="comparing-many-groups-anova-and-interactions.html#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span> (h95<span class="sc">$</span>group)  </span>
<span id="cb2-16"><a href="comparing-many-groups-anova-and-interactions.html#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] &quot;b&quot; &quot;g&quot; &quot;m&quot; &quot;w&quot;</span></span></code></pre></div>
<p>We can turn the character vector <code>group</code> into a factor vector <code>group_f</code>. The benefit of this is that these nominal labels now have an inherent ordering, and associated numerical values. R functions such as <code>brm</code> turn your nominal (non-numeric) predictors into factors in the process of fitting the model. Doing this yourself gives you control over how they will be handled.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="comparing-many-groups-anova-and-interactions.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we can turn it into a factor in R</span></span>
<span id="cb3-2"><a href="comparing-many-groups-anova-and-interactions.html#cb3-2" aria-hidden="true" tabindex="-1"></a>h95<span class="sc">$</span>group_f <span class="ot">=</span> <span class="fu">factor</span>(h95<span class="sc">$</span>group) </span>
<span id="cb3-3"><a href="comparing-many-groups-anova-and-interactions.html#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="comparing-many-groups-anova-and-interactions.html#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># now it has official levels</span></span>
<span id="cb3-5"><a href="comparing-many-groups-anova-and-interactions.html#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(h95<span class="sc">$</span>group_f)  </span>
<span id="cb3-6"><a href="comparing-many-groups-anova-and-interactions.html#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] &quot;b&quot; &quot;g&quot; &quot;m&quot; &quot;w&quot;</span></span>
<span id="cb3-7"><a href="comparing-many-groups-anova-and-interactions.html#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="comparing-many-groups-anova-and-interactions.html#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># now it has nuerical values</span></span>
<span id="cb3-9"><a href="comparing-many-groups-anova-and-interactions.html#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> (<span class="fu">as.numeric</span> (h95<span class="sc">$</span>group_f))  </span>
<span id="cb3-10"><a href="comparing-many-groups-anova-and-interactions.html#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 1 1 1 1 1 1</span></span></code></pre></div>
<p>By default factor levels are ordered alphabetically. This means that if we are using sum coding we omit the <code>w</code> parameter (the ‘last group’) and if we are using treatment coding, the intercept will be equal to <code>m</code> (the ‘first’ group). You can control this behavior by re-ordering the factor levels as below:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="comparing-many-groups-anova-and-interactions.html#cb4-1" aria-hidden="true" tabindex="-1"></a>h95<span class="sc">$</span>group_f2 <span class="ot">=</span> <span class="fu">factor</span> (h95<span class="sc">$</span>group_f, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&#39;w&#39;</span>,<span class="st">&#39;m&#39;</span>,<span class="st">&#39;g&#39;</span>,<span class="st">&#39;b&#39;</span>))</span>
<span id="cb4-2"><a href="comparing-many-groups-anova-and-interactions.html#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="comparing-many-groups-anova-and-interactions.html#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span> (h95<span class="sc">$</span>group_f2)</span>
<span id="cb4-4"><a href="comparing-many-groups-anova-and-interactions.html#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] &quot;w&quot; &quot;m&quot; &quot;g&quot; &quot;b&quot;</span></span>
<span id="cb4-5"><a href="comparing-many-groups-anova-and-interactions.html#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="comparing-many-groups-anova-and-interactions.html#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># note that &#39;m&#39; is now the second category</span></span>
<span id="cb4-7"><a href="comparing-many-groups-anova-and-interactions.html#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> (<span class="fu">as.numeric</span> (h95<span class="sc">$</span>group_f2))  </span>
<span id="cb4-8"><a href="comparing-many-groups-anova-and-interactions.html#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 4 4 4 4 4 4</span></span></code></pre></div>
<p>After this reordering, we would omit the (last) <code>b</code> parameter under sum coding, and under treatment coding the first group (<code>w</code>) would be equal to the intercept.</p>
<p>In general, representing all groups requires about one variable per group. Our single predictor, <code>group</code>, has four levels: <code>b</code>,<code>g</code>,<code>m</code>, and <code>w</code>. For models where the predictor is a factor with more than two levels, we can represent the predictor in a vector like this, <span class="math inline">\(group_{[i]}\)</span>, where <span class="math inline">\(i\)</span> is a counter variable that goes from 1 to the number of groups.</p>
<p>So the group effects can be represented in a vector as below, representing the effects (deviations from the intercept) for boys, girls, men and women:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="comparing-many-groups-anova-and-interactions.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">32</span>, <span class="sc">-</span><span class="dv">75</span>, <span class="dv">13</span>)</span>
<span id="cb5-2"><a href="comparing-many-groups-anova-and-interactions.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="do">## [1]  30  32 -75  13</span></span></code></pre></div>
<p>We can then make a short factor vector with the same labels used in this experiment. Below we can see the sequence of letter labels I specified, and their corresponding numeric values (based on alphabetical ordering).</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="comparing-many-groups-anova-and-interactions.html#cb6-1" aria-hidden="true" tabindex="-1"></a>group_index <span class="ot">=</span> <span class="fu">factor</span> (<span class="fu">c</span>(<span class="st">&#39;b&#39;</span>,<span class="st">&#39;w&#39;</span>,<span class="st">&#39;m&#39;</span>,<span class="st">&#39;w&#39;</span>,<span class="st">&#39;g&#39;</span>))</span>
<span id="cb6-2"><a href="comparing-many-groups-anova-and-interactions.html#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="comparing-many-groups-anova-and-interactions.html#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span> (group_index, <span class="at">group_index_number =</span> <span class="fu">as.numeric</span> (group_index))</span>
<span id="cb6-4"><a href="comparing-many-groups-anova-and-interactions.html#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="do">##   group_index group_index_number</span></span>
<span id="cb6-5"><a href="comparing-many-groups-anova-and-interactions.html#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="do">## 1           b                  1</span></span>
<span id="cb6-6"><a href="comparing-many-groups-anova-and-interactions.html#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="do">## 2           w                  4</span></span>
<span id="cb6-7"><a href="comparing-many-groups-anova-and-interactions.html#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="do">## 3           m                  3</span></span>
<span id="cb6-8"><a href="comparing-many-groups-anova-and-interactions.html#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="do">## 4           w                  4</span></span>
<span id="cb6-9"><a href="comparing-many-groups-anova-and-interactions.html#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="do">## 5           g                  2</span></span></code></pre></div>
<p>We can then take this vector of factor levels and use it to generate a sequence of effects:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="comparing-many-groups-anova-and-interactions.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span> (group_index)</span>
<span id="cb7-2"><a href="comparing-many-groups-anova-and-interactions.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 1 4 3 4 2</span></span>
<span id="cb7-3"><a href="comparing-many-groups-anova-and-interactions.html#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="comparing-many-groups-anova-and-interactions.html#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">32</span>, <span class="sc">-</span><span class="dv">75</span>, <span class="dv">13</span>)[group_index]</span>
<span id="cb7-5"><a href="comparing-many-groups-anova-and-interactions.html#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="do">## [1]  30  13 -75  13  32</span></span></code></pre></div>
<p>Notice that the sequence of effects match the sequence of group levels, based on their numerical value.</p>
<p>If every single group were to get an independent parameter represented in our regression equation, these would become very long and difficult to interpret. Instead, by treating the effects for the level of a factor as a vector, our models can represent a very large number of parameters in a concise way. For example, compare the following two possible implementations of our 4 group model (where <span class="math inline">\(j\)</span> is an index for our group effects):</p>
<p><span class="math display" id="eq:40">\[\begin{equation}
\begin{split}
\mu_{[i]} = Intercept + group_{[1]} + group_{[2]} + group_{[3]} + group_{[4]} \\
\mu_{[i]} = Intercept + group_{[j]} \\
\end{split}
\tag{4.1}
\end{equation}\]</span></p>
<p>It may seem like too much of a difference now, but later we have have many factors, some with dozens or hundreds of levels. In those cases, representing factor effects using vectors becomes essential.</p>
</div>
</div>
<div id="comparing-four-or-any-number-of-groups" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Comparing four (or any number of) groups</h2>
<p>We’re first going to treat the four groups as if they had no internal structure. In this case it may not be the best approach for this data, since we know there are logical ways to subdivide men, women, boys and girls. However, this is a good starting point since many cases you will have several groups with no logical internal divisions.</p>
<div id="the-model" class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> The model</h3>
<p>Our updated model is now:</p>
<p><span class="math display" id="eq:41">\[\begin{equation}
\begin{split}
\textrm{Likelihood:} \\
y_{[i]} \sim \mathcal{N}(\mu_{[i]},\sigma_{error}) \\
\mu_{[i]} = Intercept + group_{[\mathrm{group}_{[i]}]} + \alpha_{[speaker_{[i]}]} \\\\
\textrm{Priors:} \\
\alpha_{[speaker]} \sim \mathcal{N}(0,\sigma_{[speaker]}) \\ \\ 
Intercept \sim t(3, 220, 100) \\ 
group_{[\mathrm{group}]} \sim t(3, 0, 100) \\ 
\sigma_{error} \sim t(3, 0, 100) \\
\sigma_{speaker} \sim t(3, 0, 100) \\ 
\end{split}
\tag{4.2}
\end{equation}\]</span></p>
<p>Notice that for each trial number <span class="math inline">\(i\)</span> the group predictor is indexed by a variable called <code>group</code>. This is a bit confusing, but I am just trying to be consistent with how R does things.</p>
<p>As noted above, a factor predictor like <code>group</code> is really just a bunch of numbers that represent group effects in a vector. So R really treats your <code>group</code> as a sequence of numbers representing group numbers. But it also calls the predictor in the model by that name! So, though it may look strange <span class="math inline">\(group_{[\mathrm{group}_{[i]}]}\)</span> just says that you have a predictor in your model called <span class="math inline">\(group\)</span> and it has a few possible values (four in this case). Also, you have a variable in your data with the same name (<code>group</code>) that tells you which value of your <span class="math inline">\(group\)</span> predictor to use for each observation!</p>
<p>This may sound convoluted, but it is simply what I demonstrated in the end of the last subsection regarding the behavior of vectors and factors. Our model will estimate three <span class="math inline">\(group\)</span> effects (it must omit one). It estimates these from a the prior distribution specified in the model above (<span class="math inline">\(group \sim t(3, 0, 100)\)</span>). Our <em>data</em> includes a predictor called <code>group</code> that simply tells us which value of our group effect to use in each trial (<code>group[i]</code> = <span class="math inline">\(\mathrm{group}_{[i]}\)</span>).</p>
<p>For example, above we saw that the first value of the <code>group</code> vector is 3. This means this speaker is a member of the <code>m</code> group. So, in our model above the equation determining <span class="math inline">\(\mu_{[i]}\)</span> will include the value <span class="math inline">\(group_{[3]}\)</span> in it because, for the third observation this predictor will be <span class="math inline">\(group_{[\mathrm{group}_{[1]}=3]}\)</span>.</p>
<p>As in the previous chapters, we fit the models using weakly-informative priors. We’re going to use sum coding, which means that the intercept will be the mean of all the groups, and group effects will be represented as differences from this mean. Remember that the missing group effect will be equal to the negative sum of the coefficients that <em>are</em> present. By default, R drops the <em>last</em> level from your factor, which in our case will be the <code>w</code> level. We can set R to use sum coding with the line below:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="comparing-many-groups-anova-and-interactions.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span> (<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">&quot;contr.sum&quot;</span>,<span class="st">&quot;cont.sum&quot;</span>))</span></code></pre></div>
<p>And fit the model below:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="comparing-many-groups-anova-and-interactions.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span> (<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">&quot;contr.sum&quot;</span>,<span class="st">&quot;cont.sum&quot;</span>))</span>
<span id="cb9-2"><a href="comparing-many-groups-anova-and-interactions.html#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model yourself, or download pre-fit model from: </span></span>
<span id="cb9-3"><a href="comparing-many-groups-anova-and-interactions.html#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># github.com/santiagobarreda/stats-class/tree/master/models</span></span>
<span id="cb9-4"><a href="comparing-many-groups-anova-and-interactions.html#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># and load after placing in working directory</span></span>
<span id="cb9-5"><a href="comparing-many-groups-anova-and-interactions.html#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">#  model_four_groups = readRDS (&#39;4_model_four_groups.RDS&#39;)set.seed (1)</span></span>
<span id="cb9-6"><a href="comparing-many-groups-anova-and-interactions.html#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="comparing-many-groups-anova-and-interactions.html#cb9-7" aria-hidden="true" tabindex="-1"></a>model_four_groups <span class="ot">=</span>  </span>
<span id="cb9-8"><a href="comparing-many-groups-anova-and-interactions.html#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">brm</span> (f0 <span class="sc">~</span> group <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>speaker), <span class="at">data =</span> h95, <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">cores =</span> <span class="dv">4</span>, </span>
<span id="cb9-9"><a href="comparing-many-groups-anova-and-interactions.html#cb9-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">iter =</span> <span class="dv">11000</span>, <span class="at">thin =</span> <span class="dv">10</span>, </span>
<span id="cb9-10"><a href="comparing-many-groups-anova-and-interactions.html#cb9-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 200, 100)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;Intercept&quot;</span>),</span>
<span id="cb9-11"><a href="comparing-many-groups-anova-and-interactions.html#cb9-11" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 0, 100)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;b&quot;</span>),</span>
<span id="cb9-12"><a href="comparing-many-groups-anova-and-interactions.html#cb9-12" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 0, 100)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;sd&quot;</span>)))</span>
<span id="cb9-13"><a href="comparing-many-groups-anova-and-interactions.html#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="comparing-many-groups-anova-and-interactions.html#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co">#  saveRDS (model_four_groups, &#39;model_four_groups.RDS&#39;)</span></span></code></pre></div>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="comparing-many-groups-anova-and-interactions.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect model</span></span>
<span id="cb10-2"><a href="comparing-many-groups-anova-and-interactions.html#cb10-2" aria-hidden="true" tabindex="-1"></a>model_four_groups</span>
<span id="cb10-3"><a href="comparing-many-groups-anova-and-interactions.html#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="do">##  Family: gaussian </span></span>
<span id="cb10-4"><a href="comparing-many-groups-anova-and-interactions.html#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="do">##   Links: mu = identity; sigma = identity </span></span>
<span id="cb10-5"><a href="comparing-many-groups-anova-and-interactions.html#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Formula: f0 ~ group + (1 | speaker) </span></span>
<span id="cb10-6"><a href="comparing-many-groups-anova-and-interactions.html#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="do">##    Data: h95 (Number of observations: 1668) </span></span>
<span id="cb10-7"><a href="comparing-many-groups-anova-and-interactions.html#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Samples: 4 chains, each with iter = 11000; warmup = 1000; thin = 10;</span></span>
<span id="cb10-8"><a href="comparing-many-groups-anova-and-interactions.html#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="do">##          total post-warmup samples = 4000</span></span>
<span id="cb10-9"><a href="comparing-many-groups-anova-and-interactions.html#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb10-10"><a href="comparing-many-groups-anova-and-interactions.html#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="do">## Group-Level Effects: </span></span>
<span id="cb10-11"><a href="comparing-many-groups-anova-and-interactions.html#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="do">## ~speaker (Number of levels: 139) </span></span>
<span id="cb10-12"><a href="comparing-many-groups-anova-and-interactions.html#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="do">##               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS</span></span>
<span id="cb10-13"><a href="comparing-many-groups-anova-and-interactions.html#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="do">## sd(Intercept)    20.95      1.34    18.51    23.82 1.00     2080     2564</span></span>
<span id="cb10-14"><a href="comparing-many-groups-anova-and-interactions.html#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb10-15"><a href="comparing-many-groups-anova-and-interactions.html#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="do">## Population-Level Effects: </span></span>
<span id="cb10-16"><a href="comparing-many-groups-anova-and-interactions.html#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="do">##           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS</span></span>
<span id="cb10-17"><a href="comparing-many-groups-anova-and-interactions.html#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="do">## Intercept   206.49      1.93   202.67   210.21 1.00     1474     2270</span></span>
<span id="cb10-18"><a href="comparing-many-groups-anova-and-interactions.html#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="do">## group1       29.53      3.52    22.78    36.65 1.00     1253     2236</span></span>
<span id="cb10-19"><a href="comparing-many-groups-anova-and-interactions.html#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="do">## group2       31.88      3.98    24.35    39.68 1.00     1565     2392</span></span>
<span id="cb10-20"><a href="comparing-many-groups-anova-and-interactions.html#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="do">## group3      -75.18      2.90   -80.89   -69.62 1.00     1246     2383</span></span>
<span id="cb10-21"><a href="comparing-many-groups-anova-and-interactions.html#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb10-22"><a href="comparing-many-groups-anova-and-interactions.html#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="do">## Family Specific Parameters: </span></span>
<span id="cb10-23"><a href="comparing-many-groups-anova-and-interactions.html#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="do">##       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS</span></span>
<span id="cb10-24"><a href="comparing-many-groups-anova-and-interactions.html#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="do">## sigma    11.86      0.22    11.46    12.31 1.00     3882     3814</span></span>
<span id="cb10-25"><a href="comparing-many-groups-anova-and-interactions.html#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb10-26"><a href="comparing-many-groups-anova-and-interactions.html#cb10-26" aria-hidden="true" tabindex="-1"></a><span class="do">## Samples were drawn using sampling(NUTS). For each parameter, Bulk_ESS</span></span>
<span id="cb10-27"><a href="comparing-many-groups-anova-and-interactions.html#cb10-27" aria-hidden="true" tabindex="-1"></a><span class="do">## and Tail_ESS are effective sample size measures, and Rhat is the potential</span></span>
<span id="cb10-28"><a href="comparing-many-groups-anova-and-interactions.html#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="do">## scale reduction factor on split chains (at convergence, Rhat = 1).</span></span></code></pre></div>
<p>We can see that the intercept is the average of the group means, and our coefficients are equal to the centered group means. Notice that we use the hypothesis function to recover the final group coefficient using the negative sum of the coefficients that were estimated.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="comparing-many-groups-anova-and-interactions.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># group means</span></span>
<span id="cb11-2"><a href="comparing-many-groups-anova-and-interactions.html#cb11-2" aria-hidden="true" tabindex="-1"></a>means <span class="ot">=</span> <span class="fu">tapply</span> (h95<span class="sc">$</span>f0, h95<span class="sc">$</span>group, mean)</span>
<span id="cb11-3"><a href="comparing-many-groups-anova-and-interactions.html#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="comparing-many-groups-anova-and-interactions.html#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># overall mean</span></span>
<span id="cb11-5"><a href="comparing-many-groups-anova-and-interactions.html#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span> (means)</span>
<span id="cb11-6"><a href="comparing-many-groups-anova-and-interactions.html#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 206.51</span></span>
<span id="cb11-7"><a href="comparing-many-groups-anova-and-interactions.html#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="comparing-many-groups-anova-and-interactions.html#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># group means</span></span>
<span id="cb11-9"><a href="comparing-many-groups-anova-and-interactions.html#cb11-9" aria-hidden="true" tabindex="-1"></a>means</span>
<span id="cb11-10"><a href="comparing-many-groups-anova-and-interactions.html#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="do">##      b      g      m      w </span></span>
<span id="cb11-11"><a href="comparing-many-groups-anova-and-interactions.html#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="do">## 236.07 238.35 131.22 220.40</span></span>
<span id="cb11-12"><a href="comparing-many-groups-anova-and-interactions.html#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="comparing-many-groups-anova-and-interactions.html#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co"># centered means</span></span>
<span id="cb11-14"><a href="comparing-many-groups-anova-and-interactions.html#cb11-14" aria-hidden="true" tabindex="-1"></a>means <span class="sc">-</span> <span class="fu">mean</span> (means)</span>
<span id="cb11-15"><a href="comparing-many-groups-anova-and-interactions.html#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="do">##       b       g       m       w </span></span>
<span id="cb11-16"><a href="comparing-many-groups-anova-and-interactions.html#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="do">##  29.563  31.840 -75.293  13.890</span></span>
<span id="cb11-17"><a href="comparing-many-groups-anova-and-interactions.html#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="comparing-many-groups-anova-and-interactions.html#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="co"># parameters = centered means</span></span>
<span id="cb11-19"><a href="comparing-many-groups-anova-and-interactions.html#cb11-19" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">hypothesis</span> (model_four_groups, </span>
<span id="cb11-20"><a href="comparing-many-groups-anova-and-interactions.html#cb11-20" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">c</span>(<span class="st">&quot;Intercept = 0&quot;</span>,</span>
<span id="cb11-21"><a href="comparing-many-groups-anova-and-interactions.html#cb11-21" aria-hidden="true" tabindex="-1"></a>                    <span class="st">&quot;group1 = 0&quot;</span>,</span>
<span id="cb11-22"><a href="comparing-many-groups-anova-and-interactions.html#cb11-22" aria-hidden="true" tabindex="-1"></a>                    <span class="st">&quot;group2 = 0&quot;</span>,</span>
<span id="cb11-23"><a href="comparing-many-groups-anova-and-interactions.html#cb11-23" aria-hidden="true" tabindex="-1"></a>                    <span class="st">&quot;group3 = 0&quot;</span>, </span>
<span id="cb11-24"><a href="comparing-many-groups-anova-and-interactions.html#cb11-24" aria-hidden="true" tabindex="-1"></a>                    <span class="st">&quot;-(group1+group2+group3) = 0&quot;</span>))[[<span class="dv">1</span>]][,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb11-25"><a href="comparing-many-groups-anova-and-interactions.html#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="do">##                      Hypothesis Estimate Est.Error CI.Lower CI.Upper</span></span>
<span id="cb11-26"><a href="comparing-many-groups-anova-and-interactions.html#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="do">## 1               (Intercept) = 0  206.486    1.9287 202.6697  210.213</span></span>
<span id="cb11-27"><a href="comparing-many-groups-anova-and-interactions.html#cb11-27" aria-hidden="true" tabindex="-1"></a><span class="do">## 2                  (group1) = 0   29.532    3.5239  22.7831   36.645</span></span>
<span id="cb11-28"><a href="comparing-many-groups-anova-and-interactions.html#cb11-28" aria-hidden="true" tabindex="-1"></a><span class="do">## 3                  (group2) = 0   31.878    3.9764  24.3510   39.684</span></span>
<span id="cb11-29"><a href="comparing-many-groups-anova-and-interactions.html#cb11-29" aria-hidden="true" tabindex="-1"></a><span class="do">## 4                  (group3) = 0  -75.176    2.9037 -80.8886  -69.620</span></span>
<span id="cb11-30"><a href="comparing-many-groups-anova-and-interactions.html#cb11-30" aria-hidden="true" tabindex="-1"></a><span class="do">## 5 (-(group1+group2+group3)) = 0   13.766    2.9346   7.9231   19.379</span></span></code></pre></div>
<p>Whn you fit a more traditional model, you can’t just compare any groups you want. However, with these Bayesian models we can compare any groups we want by using comparisons of the posterior samples (as shown in chapter 3). For example, the difference between girls and boys can be found by asking if one minus the other equals 0 (which would be true if these were identical):</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="comparing-many-groups-anova-and-interactions.html#cb12-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">hypothesis</span> (model_four_groups, <span class="st">&quot;group1 - group2 = 0&quot;</span>)[[<span class="dv">1</span>]][,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb12-2"><a href="comparing-many-groups-anova-and-interactions.html#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="do">##            Hypothesis Estimate Est.Error CI.Lower CI.Upper</span></span>
<span id="cb12-3"><a href="comparing-many-groups-anova-and-interactions.html#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="do">## 1 (group1-group2) = 0  -2.3459    6.4375  -15.038   10.282</span></span></code></pre></div>
<p>The result above suggests that the difference is very small (-2 Hz) and the 95% credible intervals spans a huge range (from -15 to +10)). As a result, the measured difference between these groups is not reliable, and may be very small or close to zero. Notice that in this summary I am focused on minimizing <a href="https://statmodeling.stat.columbia.edu/2004/12/29/type_1_type_2_t/">type S and type M errors</a>. This means I am worried about whether the effect is likely to be small or large, and negative or positive, rather than whether it is ‘true’ or ‘false’.</p>
</div>
</div>
<div id="investigating-many-factors-simultaneously-analysis-of-variance" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Investigating many factors simultaneously: Analysis of Variance</h2>
<p>Above, our model had a single ‘batch’ of groups. Another way to look at it is that the model predicted variation along a single <em>dimension</em>. However, we can categorize people (or observations) along multiple dimensions simultaneously. So, a speaker may be an adult <em>and</em> a woman, and not just and adult <em>or</em> a women. This is because adultness and gender are independent dimensions and the value of one does not affect the value of the other.</p>
<p>We can return to the example of the reading experiment presented above. Recall that we had four groups varying along two ‘dimensions’: whether they drank coffee or water, and whether they were male or female. The figure below represents designs of this structure and shows three ways that these can be organized.</p>
<p>The characteristics of <em>within-subjects</em> and <em>between-subjects</em> designs should be familiar by now. What is new is the ‘mixed’ design. In a mixed design, one or more factors are between-subjects, and the others are within-subjects. In the example below, <span class="math inline">\(A\)</span> is between-subjects but <span class="math inline">\(B\)</span> is within-subjects. Actually, the caffeine experiment we have been discussing would have to be a mixed design: subjects can be tested at both levels of “drink” (water and coffee) but not at both levels of gender.</p>
<div class="figure" style="text-align: center"><span id="fig:F4-designfig2"></span>
<img src="images/design_ch4_2.png" alt="Data from a single group of subjects (S) divided according to a single grouping factor A." width="100%" />
<p class="caption">
Figure 4.4: Data from a single group of subjects (S) divided according to a single grouping factor A.
</p>
</div>
<p>Our models can include any number of factors, and these can be <em>crossed</em> or <em>nested</em>. When two factors are crossed, this means that all levels of a factor appear at all levels of another factor. This is easiest to conceive of for participants (remember ‘participant’ is just factor!). Participants are ‘crossed’ with a factor when these are tested at all levels of a factor. So, a factor that varies within-subject is crossed with subjects.</p>
<p>When one or more levels of a factor cannot be observed at all levels of another factor, then these are no longer crossed. When levels of one factor appear exclusively at specific levels of the other factor they are said to be <em>nested</em>. So, when different subsets of participants appear at different levels of a factor, the factor is crossed with subjects.</p>
<p>In the images above, all of the examples cross <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>. What would it look like for these factors to not be crossed? Well, one of the ’cells (boxes) would be completely missing observations. If this were to happen, we would lose the ability to make comparisons across groups involving the values in that cell.</p>
<p>Designs where all the factors are crossed are sometimes called ‘factorial’ or ‘orthogonal’ designs. The name ‘orthogonal’ is particularly telling. It means ‘at right angles, perpendicular’ (from the greek stems “ortho-”, meaning straight, right, and “-gon-”, meaning side or angle). When you have orthogonal designs, that means that your ‘dimensions’ (i.e., factors) can be estimated independently.</p>
<p>Consider what would have happened if you ran the coffee and reading time experiment and gave coffee only to women and water only to men. How would you know if the coffee is responsible for the difference or if it should be attributed to gender. What if you gave water and coffee to women but only water to men. This would allow you to test the “drink” effect with accuracy for women but not for men. Is it <em>necessary</em> that the results for women equal those of men? If so, why did we include gender as a predictor?</p>
<p>The above example shows that if you want to be able to untangle the independent effects of gender and drink on reading time, you need to test all levels of gender at all levels of drink. In other words, estimating the independent effects of each factor, and the relationships between the factors, requires that factors be crossed so that the design is orthogonal.</p>
<p>In addition, orthogonal designs allow us to ‘decompose’ the variation in our data into individual components. If orthogonality lets us estimate the individual effects of different factors, we can divide the variation in our observations into that which can be attributed to the different factors in our design. This simple but extremely powerful idea is called the analysis of variance, discussed in more detail in the following section.</p>
<div id="description-of-the-model-3" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Description of the model</h3>
<p>In the previous section, we acted like we just had four different groups with no internal structure. Of course, we know that our groups differ systematically from each other in meaningful ways. For example, we might have chosen to fit two separate models that looked like this:</p>
<p><code>brm (f0 ~ gender + (1|speaker)</code></p>
<p><code>brm (f0 ~ adult + (1|speaker)</code></p>
<p>For several reasons (some of which we’ll see very soon), it’s preferable to fit a single model with both predictors at once, rather than fitting two separate models for each one. Our R model formula will now look like this, reflecting the influence of both predictors simultaneously:</p>
<p><code>f0 ~ adult + gender + (1|speaker)</code></p>
<p>This can be read like “f0 is distributed according to effects for speaker adultness and gender, with random intercepts for each speaker”. You may have noticed that our model no longer includes the <code>group</code> predictor. This is because the <code>group</code> label is perfectly predictable on the basis of <code>adult</code> and <code>gender</code> (i.e., a member of the <code>g</code> group must have values of <code>female</code> and <code>child</code>). Basically, we have decomposed the groups into two components to help us understand the effect of each. This is simply and extension of what we have been doing from the start. For example our model was previously:</p>
<p><span class="math inline">\(\mu_{[i]} = Intercept + (group_{\mathrm{group}_{[i]}}) + \alpha_{\mathrm{speaker}_{[i]}}\)</span></p>
<p>However, since group can be exactly represented by combinations of gender and adult, our model sort of always contained this more-complicated model inside of it. We can expand the term in parenthesis as below:</p>
<p><span class="math inline">\(\mu_{[i]} = Intercept + (adult_{\mathrm{adult}_{[i]}} + gender_{\mathrm{gender}_{[i]}}) + \alpha_{\mathrm{speaker}_{[i]}}\)</span></p>
<p>This is what can be referred to as an ‘ANOVA-like’ decomposition. ANOVA, the <em>AN</em>alysis <em>O</em>f <em>VA</em>riance, is general approach for understanding data by focusing on the sources of variance contained in it. We have actually been chipping away at the error variance little by little by making more complicated models.</p>
<p>Recall that our very first approach to understanding f0 looked like this:</p>
<p><span class="math display">\[
\sigma_{total} = \sigma_{error}
\]</span></p>
<p>In other words, all variation was error. After this we added between-speaker variation to the model, and removed that from the error.</p>
<p><span class="math display">\[
\sigma_{total} = \sigma_{speaker} + \sigma_{error}
\]</span></p>
<p>Now, our model can individually estimate the variation in observed f0 due adultness, gender, to between-speaker variation and to production error.</p>
<p><span class="math display">\[
\sigma_{total} = \sigma_{adult} + \sigma_{gender}+\sigma_{speaker} + \sigma_{error}
\]</span></p>
<p>Our complete model is now:</p>
<p><span class="math display" id="eq:42">\[\begin{equation}
\begin{split}
\textrm{Likelihood:} \\
f0_{[i]} \sim \mathcal{N}(\mu_{[i]},\sigma_{error}) \\
\mu_{[i]} = Intercept + adult_{\mathrm{adult}_{[i]}}+gender_{\mathrm{gender}_{[i]}} + \alpha_{\mathrm{speaker}_{[i]}} \\\\
\textrm{Priors:} \\
\alpha_{speaker} \sim \mathcal{N}(0,\sigma_{speaker}) \\ \\ 
Intercept \sim t(3, 200, 100) \\ 
adult_{\mathrm{adult}} \sim t(3, 0, 100) \\ 
gender_{\mathrm{gender}} \sim t(3, 0, 100) \\ 
\sigma_{error} \sim t(3, 0, 100) \\
\sigma_{speaker} \sim t(3, 0, 100) \\ 
\end{split}
\tag{4.3}
\end{equation}\]</span></p>
<p>In plain English this says:</p>
<blockquote>
<p>“We expect the mean f0 produced by speakers from Michigan to vary according to a normal distribution with a trial-specific mean parameter. That mean varies based on whether the speaker is an adult/child and female/male, and some random speaker-dependent variation. Speaker-dependent variation in the means were modelled as coming from a normal distribution with a mean of zero and a standard deviation estimated from the data”.</p>
</blockquote>
</div>
<div id="fitting-the-model-and-interpreting-the-results" class="section level3" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Fitting the model and interpreting the results</h3>
<p>Below we fit the model using the model structure outlined above.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="comparing-many-groups-anova-and-interactions.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model yourself, or download pre-fit model from: </span></span>
<span id="cb13-2"><a href="comparing-many-groups-anova-and-interactions.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># github.com/santiagobarreda/stats-class/tree/master/models</span></span>
<span id="cb13-3"><a href="comparing-many-groups-anova-and-interactions.html#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># and load after placing in working directory</span></span>
<span id="cb13-4"><a href="comparing-many-groups-anova-and-interactions.html#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  model_both = readRDS (&#39;4_model_both.RDS&#39;)</span></span>
<span id="cb13-5"><a href="comparing-many-groups-anova-and-interactions.html#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="comparing-many-groups-anova-and-interactions.html#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span> (<span class="dv">1</span>)</span>
<span id="cb13-7"><a href="comparing-many-groups-anova-and-interactions.html#cb13-7" aria-hidden="true" tabindex="-1"></a>model_both <span class="ot">=</span>  </span>
<span id="cb13-8"><a href="comparing-many-groups-anova-and-interactions.html#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">brm</span> (f0 <span class="sc">~</span> adult <span class="sc">+</span> gender <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>speaker), <span class="at">data =</span> h95, <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">cores =</span> <span class="dv">4</span>, </span>
<span id="cb13-9"><a href="comparing-many-groups-anova-and-interactions.html#cb13-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">iter =</span> <span class="dv">11000</span>, <span class="at">thin =</span> <span class="dv">10</span>, </span>
<span id="cb13-10"><a href="comparing-many-groups-anova-and-interactions.html#cb13-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 200, 100)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;Intercept&quot;</span>),</span>
<span id="cb13-11"><a href="comparing-many-groups-anova-and-interactions.html#cb13-11" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 0, 100)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;b&quot;</span>),</span>
<span id="cb13-12"><a href="comparing-many-groups-anova-and-interactions.html#cb13-12" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 0, 100)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;sd&quot;</span>))) </span>
<span id="cb13-13"><a href="comparing-many-groups-anova-and-interactions.html#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co">#  saveRDS (model_both, &#39;4_model_both.RDS&#39;)</span></span></code></pre></div>
<p>And we can inspect the model fixed effects:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="comparing-many-groups-anova-and-interactions.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect the fixed effects</span></span>
<span id="cb14-2"><a href="comparing-many-groups-anova-and-interactions.html#cb14-2" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">fixef</span> (model_both)</span>
<span id="cb14-3"><a href="comparing-many-groups-anova-and-interactions.html#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="do">##           Estimate Est.Error    Q2.5   Q97.5</span></span>
<span id="cb14-4"><a href="comparing-many-groups-anova-and-interactions.html#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Intercept  209.134    2.6607 203.948 214.379</span></span>
<span id="cb14-5"><a href="comparing-many-groups-anova-and-interactions.html#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="do">## adult1     -32.948    2.7316 -38.377 -27.657</span></span>
<span id="cb14-6"><a href="comparing-many-groups-anova-and-interactions.html#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="do">## gender1     30.492    2.4980  25.494  35.394</span></span></code></pre></div>
<p>We now have two non-Intercept ‘Population-Level’ effects: <code>adult1</code> and <code>gender1</code>, representing the categories ‘adult’ and ‘female’ respectively. Remember that since we used sum coding, the effects for the groups that are not represented (‘child’, ‘male’) are just the opposite sign of the groups that are represented.</p>
<p>Below we calculate the mean f0 of the four groups, and find the average difference between two different arrangements of the group. First, we calculate the difference between the child groups and the adult groups. This tell us what the average differences is according to ‘adultness’. Then, we do the same thing for the female and male groups to find the average difference according to ‘gender’.</p>
<p>Below, we can see that the Intercept (209 Hz) is reasonably close to the mean of the group means (206 Hz), and that the adult effect (-33 Hz) is about the same magnitude as the difference between the mean of the adult and child groups (30 Hz). However, the model seems to overestimate the average differences between male and female groups (30 Hz in model, 23 Hz in the data).</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="comparing-many-groups-anova-and-interactions.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># grop means</span></span>
<span id="cb15-2"><a href="comparing-many-groups-anova-and-interactions.html#cb15-2" aria-hidden="true" tabindex="-1"></a>means <span class="ot">=</span> <span class="fu">tapply</span> (h95<span class="sc">$</span>f0, h95<span class="sc">$</span>group, mean)</span>
<span id="cb15-3"><a href="comparing-many-groups-anova-and-interactions.html#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># overall mean in data </span></span>
<span id="cb15-4"><a href="comparing-many-groups-anova-and-interactions.html#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span> (means)</span>
<span id="cb15-5"><a href="comparing-many-groups-anova-and-interactions.html#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 206.51</span></span>
<span id="cb15-6"><a href="comparing-many-groups-anova-and-interactions.html#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># group means</span></span>
<span id="cb15-7"><a href="comparing-many-groups-anova-and-interactions.html#cb15-7" aria-hidden="true" tabindex="-1"></a>means</span>
<span id="cb15-8"><a href="comparing-many-groups-anova-and-interactions.html#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="do">##      b      g      m      w </span></span>
<span id="cb15-9"><a href="comparing-many-groups-anova-and-interactions.html#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="do">## 236.07 238.35 131.22 220.40</span></span>
<span id="cb15-10"><a href="comparing-many-groups-anova-and-interactions.html#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># half the average adultness difference in data</span></span>
<span id="cb15-11"><a href="comparing-many-groups-anova-and-interactions.html#cb15-11" aria-hidden="true" tabindex="-1"></a>((means[<span class="st">&#39;b&#39;</span>]<span class="sc">+</span>means[<span class="st">&#39;g&#39;</span>])<span class="sc">/</span><span class="dv">2</span> <span class="sc">-</span> (means[<span class="st">&#39;m&#39;</span>]<span class="sc">+</span>means[<span class="st">&#39;w&#39;</span>])<span class="sc">/</span><span class="dv">2</span>) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb15-12"><a href="comparing-many-groups-anova-and-interactions.html#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="do">##      b </span></span>
<span id="cb15-13"><a href="comparing-many-groups-anova-and-interactions.html#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="do">## 30.701</span></span>
<span id="cb15-14"><a href="comparing-many-groups-anova-and-interactions.html#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co"># half the average gender difference in data</span></span>
<span id="cb15-15"><a href="comparing-many-groups-anova-and-interactions.html#cb15-15" aria-hidden="true" tabindex="-1"></a>((means[<span class="st">&#39;g&#39;</span>]<span class="sc">+</span>means[<span class="st">&#39;w&#39;</span>])<span class="sc">/</span><span class="dv">2</span> <span class="sc">-</span> (means[<span class="st">&#39;m&#39;</span>]<span class="sc">+</span>means[<span class="st">&#39;b&#39;</span>])<span class="sc">/</span><span class="dv">2</span>) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb15-16"><a href="comparing-many-groups-anova-and-interactions.html#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="do">##      g </span></span>
<span id="cb15-17"><a href="comparing-many-groups-anova-and-interactions.html#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="do">## 22.865</span></span></code></pre></div>
<p>We can recover the group means by adding up the individual coefficients. This can be tedious and requires you to be careful and methodical, but isn’t actually difficult. Remember that each of the four groups is uniquely identified by a combination of gender and adultness. To recover the group means we need to add the right combination of coefficients to the intercept.</p>
<p>For example, the second hypothesis we are testing below says <code>Intercept + -adult1 + -gender1 = 0</code>. This hypothesis takes the overall mean and adds the effect for ‘child’ (<code>adult2</code>). Why did we use <code>-adult1</code> in the formula and not <code>adult2</code>? This is because our model <em>does not contain</em> a parameter called <code>adult2</code>. This parameter is not estimated in our model because <code>-adult1=adult2</code>. So, if we want the value of <code>adult2</code> we use <code>-adult1</code>, because <code>adult2</code> does not exist. Similarly, we add the effect for ‘male’ (<code>gender2</code>) using <code>-gender1</code>. Since we started with the overall mean f0 and add the effects for a ‘male’ and a ‘child’, this hypothesis estimates the group mean for ‘boys’.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="comparing-many-groups-anova-and-interactions.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span> (h95<span class="sc">$</span>f0, h95<span class="sc">$</span>group, mean)</span>
<span id="cb16-2"><a href="comparing-many-groups-anova-and-interactions.html#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="do">##      b      g      m      w </span></span>
<span id="cb16-3"><a href="comparing-many-groups-anova-and-interactions.html#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="do">## 236.07 238.35 131.22 220.40</span></span>
<span id="cb16-4"><a href="comparing-many-groups-anova-and-interactions.html#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="comparing-many-groups-anova-and-interactions.html#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># this hypothesis calculates the intercept, and </span></span>
<span id="cb16-6"><a href="comparing-many-groups-anova-and-interactions.html#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># the group means for boys, girls, men, women</span></span>
<span id="cb16-7"><a href="comparing-many-groups-anova-and-interactions.html#cb16-7" aria-hidden="true" tabindex="-1"></a>means_pred <span class="ot">=</span> brms<span class="sc">::</span><span class="fu">hypothesis</span> (model_both, </span>
<span id="cb16-8"><a href="comparing-many-groups-anova-and-interactions.html#cb16-8" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">c</span>(<span class="st">&quot;Intercept = 0&quot;</span>,</span>
<span id="cb16-9"><a href="comparing-many-groups-anova-and-interactions.html#cb16-9" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">&quot;Intercept + -adult1 + -gender1 = 0&quot;</span>,</span>
<span id="cb16-10"><a href="comparing-many-groups-anova-and-interactions.html#cb16-10" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">&quot;Intercept + -adult1 +  gender1 = 0&quot;</span>,</span>
<span id="cb16-11"><a href="comparing-many-groups-anova-and-interactions.html#cb16-11" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">&quot;Intercept +  adult1 + -gender1 = 0&quot;</span>,</span>
<span id="cb16-12"><a href="comparing-many-groups-anova-and-interactions.html#cb16-12" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">&quot;Intercept +  adult1 +  gender1 = 0&quot;</span>))[[<span class="dv">1</span>]][,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb16-13"><a href="comparing-many-groups-anova-and-interactions.html#cb16-13" aria-hidden="true" tabindex="-1"></a>means_pred</span>
<span id="cb16-14"><a href="comparing-many-groups-anova-and-interactions.html#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="do">##                         Hypothesis Estimate Est.Error CI.Lower CI.Upper</span></span>
<span id="cb16-15"><a href="comparing-many-groups-anova-and-interactions.html#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="do">## 1                  (Intercept) = 0   209.13    2.6607   203.95   214.38</span></span>
<span id="cb16-16"><a href="comparing-many-groups-anova-and-interactions.html#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="do">## 2 (Intercept+-adult1+-gender1) = 0   211.59    4.8403   202.16   221.42</span></span>
<span id="cb16-17"><a href="comparing-many-groups-anova-and-interactions.html#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="do">## 3  (Intercept+-adult1+gender1) = 0   272.57    5.3907   262.09   283.07</span></span>
<span id="cb16-18"><a href="comparing-many-groups-anova-and-interactions.html#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="do">## 4  (Intercept+adult1+-gender1) = 0   145.69    4.0108   137.79   153.42</span></span>
<span id="cb16-19"><a href="comparing-many-groups-anova-and-interactions.html#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="do">## 5   (Intercept+adult1+gender1) = 0   206.68    3.8145   199.20   214.21</span></span></code></pre></div>
<p>The predictions above are actually not a good match for our group means, suggesting that maybe our model is not capturing something important about our data.</p>
</div>
</div>
<div id="investigating-model-fit" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Investigating model fit</h2>
<p>So far we’ve been working with very simple models and not worrying much about how well they ‘fit’, meaning how well they represent our data. Our reconstruction of the group means above suggests our current model may have some issues, and that we should be concerned about its fit.</p>
<p>We can investigate model fit with a ‘posterior predictive check’. The ‘posterior predictions’ made by your model are the values predicted by your model for each data point, for each set of posterior samples. Effectively, these are the <span class="math inline">\(\mu_{[i]}\)</span> predicted by your model for each trial. For example, our current model looks like this:</p>
<p><span class="math inline">\(\mu_{[i]} = Intercept + adult_{[\mathrm{adult}_{[i]}]} + gender_{[\mathrm{gender}_{[i]}]} + \alpha_{[\mathrm{speaker}_{[i]}]}\)</span></p>
<p>This model equation predicts a different <span class="math inline">\(\mu\)</span> for each trial by combining the intercept and appropriate coefficients for the trial. These predicted values can then be used with the error estimated by the model (<span class="math inline">\(\sigma_{error})\)</span>) to generate simulated data using a normal distribution, like this <span class="math inline">\(\mathcal{N}(\mu_{[i]},\sigma_{error})\)</span>.</p>
<p>This technique is called ‘posterior prediction’, and it can be used to assess how well your model fits your data. If your model really ‘gets’ your data, the fake data it makes will be exactly like your real data. If the fake data your model generates looks substantially different from your real data, that suggests a fundamental misalignment between your model and your data.</p>
<p>The <code>brms</code> package has a <code>predict</code> function which can help you make these predictions easily.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="comparing-many-groups-anova-and-interactions.html#cb17-1" aria-hidden="true" tabindex="-1"></a>y_pred <span class="ot">=</span> <span class="fu">predict</span> (model_both)</span>
<span id="cb17-2"><a href="comparing-many-groups-anova-and-interactions.html#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="comparing-many-groups-anova-and-interactions.html#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> (y_pred)</span>
<span id="cb17-4"><a href="comparing-many-groups-anova-and-interactions.html#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="do">##      Estimate Est.Error     Q2.5    Q97.5</span></span>
<span id="cb17-5"><a href="comparing-many-groups-anova-and-interactions.html#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="do">## [1,] 243.7989  12.55577 219.4143 268.7087</span></span>
<span id="cb17-6"><a href="comparing-many-groups-anova-and-interactions.html#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="do">## [2,] 278.3190  12.55514 253.8997 303.1478</span></span>
<span id="cb17-7"><a href="comparing-many-groups-anova-and-interactions.html#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="do">## [3,] 207.7220  12.36896 183.2782 231.7484</span></span>
<span id="cb17-8"><a href="comparing-many-groups-anova-and-interactions.html#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="do">## [4,] 247.0643  12.28252 223.5102 270.6152</span></span>
<span id="cb17-9"><a href="comparing-many-groups-anova-and-interactions.html#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="do">## [5,] 218.6251  12.50744 193.1472 243.4518</span></span>
<span id="cb17-10"><a href="comparing-many-groups-anova-and-interactions.html#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="do">## [6,] 300.9915  12.43985 276.3581 325.2514</span></span></code></pre></div>
<p>The output of prediction, <code>y_pred</code>, has four columns and as many rows as you had observations. These contain a predicted value for each datapoint, but also information about credible intervals around the predictions. The reason we can get intervals around our predictions is because our model produces a different prediction for each set of posterior samples! This means that if we have 4000 samples we actually have 4000 slightly different models and 4000 slightly different predictions. So, in addition to information about the most probable estimates, we get information about expected variation around these estimates.</p>
<p>Below, I make predictions without random effects (<code>re_formula = NA</code>).</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="comparing-many-groups-anova-and-interactions.html#cb18-1" aria-hidden="true" tabindex="-1"></a>y_pred_no_re <span class="ot">=</span> <span class="fu">predict</span> (model_both, <span class="at">re_formula =</span> <span class="cn">NA</span>)</span></code></pre></div>
<p>This corresponds to a model like below, <em>without</em> speaker adjustments:</p>
<p><span class="math inline">\(\mu_{[i]} = Intercept + adult_{adult_{[i]}} + gender_{gender_{[i]}}\)</span></p>
<p>The posterior predictions made by this model will help us understand how well our model represents average f0 based only on group averages, without the speaker-dependent adjustments.</p>
<p>Below we can see that the model with speaker adjustments does a very good job of predicting f0, with most credible intervals for most predictions overlapping with the diagonal (diagonal = perfect prediction). On the other hand, without speaker adjustments the predictions for many high-f0 speakers lie left of the diagonal, meaning our predictions are higher than they should be.</p>
<div class="figure"><span id="fig:F4-postpred1"></span>
<img src="04_files/figure-html/F4-postpred1-1.png" alt="(left) Posterior predicted f0 for the model with speaker random effects. (right) Posterior predicted f0 for the model without speaker random effects" width="768" />
<p class="caption">
Figure 4.5: (left) Posterior predicted f0 for the model with speaker random effects. (right) Posterior predicted f0 for the model without speaker random effects
</p>
</div>
<p>The above plots are good for basic analysis, but it’s hard to get a good idea of the source of our problems using these plots. We can get a much better idea of how our model is performing by using an ‘interaction plot’.</p>
</div>
<div id="interactions-and-interaction-plots" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Interactions and interaction plots</h2>
<p><a href="http://glimo.vub.ac.be/downloads/interaction.htm">Interactions</a> and understanding their graphical representations is extremely important. In many if not most models with multiple predictors, researchers will need to at least consider the effects of interactions in their models.</p>
<p>We can think of a single effect representing a difference between groups as a slope. For example, in the left panel below I plotted the mean f0 produced by males and female speakers from the Hillenbrand et al. data at x-axis locations 0 and 1. The difference in the group means is -55 Hz (females 225 Hz, males 170 Hz). As a result, the line formed by joining these groups has a slope of -55 (i.e., it drops 55 Hz from 0 to 1). We can use any arbitrary x axis distance to calculate slopes, as long as we are consistent. However, there are obvious practical advantages to choosing to calculate these slopes over the arbitrary ‘distance’ of 1. In the middle panel we see the effect for adultness, which shows a positive slope for the difference from adult to child: the f0 increases by about 60 Hz.</p>
<p>The plots highlighting the effects for adultness and gender are ‘main effects’ plots. You may have heard things like “the analysis showed a significant main effect for so and so…”. Main effects are the average effects for one predictor averaged across everything else. Saying ‘averaged across everything else’ basically means we are ignoring everything else. A person looking only at the left plot would not realize our data also investigates the effect of adultness. We have ‘erased’ the differences in adultness by averaging across all levels of that factor.</p>
<p>Another way to think of main effects are that they are ‘marginal’ effects. They are the overall average difference. Someone might ask you, “whats the average difference between the f0 produced by male and female speakers in Michigan?” and you can respond “55 Hz”. However, sometimes the answer is not so simple, and it starts more like: “well… it depends”. Interactions represent situations like these, where the effect of one variable depends on, or is <em>conditional</em> on, the value of some other variable.</p>
<div class="figure"><span id="fig:F4-interactionplot"></span>
<img src="04_files/figure-html/F4-interactionplot-1.png" alt="Plots showing different ways to consider our f0 data." width="768" />
<p class="caption">
Figure 4.6: Plots showing different ways to consider our f0 data.
</p>
</div>
<p>In the right panel above we see a two-way interaction plot. Interaction plots show you what are called the <a href="http://glimo.vub.ac.be/downloads/simpleeffect.htm">simple effects</a> of your predictors (sometimes also called the <em>simple main effects</em>). The simple effects are the ‘conditional probabilities’: the effects of your factor, conditional on the level of another factor. For example, the left plot shows the overall (marginal) effect for gender. The right plot also shows the effect for gender. However, it uses a blue line to show the effect for gender in adults (gender given adultness) and a green line to show the effect for children for children (gender given childness). As a result, we can consider the effects of gender <em>conditioned</em> on adultness, and see how these might differ.</p>
<p>So, main effects show you the effect for a factor, and simple effects show you the effects of the factor <em>depending</em> on the value of other things.</p>
<p>If adultness in no way affected f0, the right panel should look identical to the left panel. If adultness affected f0 in the same way across genders, we would see parallel lines in the right plot. This is because if you are adding a <em>single value</em> to each end of the adult line, the line indicating the gender effect for adults (broken green line) would just slide up and down the f0 axis but would not change in slope. There is no way to make the green and blue lines above to match by adding a single value to either. This indicates we have an interaction in our data.</p>
<p>In general, when we see lines that are not parallel, that means there may be an interaction in our data. In the absence of an interaction, we could just answer the question “whats the average difference between males and females in your sample?” with a number like 55 Hz. In the presence of an interaction we need to consider the <em>conditional effects</em> of each predictor, at the levels of the other predictor.</p>
<p>The idea of conditional effects <em>feels</em> complicated, but it is something we all understand intuitively. How much progress will a person learning a second language make in a year? What if I told you that one group of speakers is 3 and the other is 65. You <em>know</em> that makes a difference, which is to say, that you <em>know</em> there is an interaction between the effect time spent learning a language, and the age at which the learner begins.</p>
<p>Furthermore, we all intuitively understand interactions whenever we correctly interpret the information presented in an interaction plot as above. There is a large negative slope for gender for adults. This tells us that gender has a large effect on f0 for adults. However, the slope for gender is basically zero for children. So, we might say “there is a large f0 difference for adult males and females in our sample, but basically no gender based difference for children”. Alternatively, we might look at the changing effect for gender across adultness levels. If we did this, we might say “there is a small effect for adultness in the average f0 produced by females, but a very large effect for adultness for males”. Anyone who is able to make such a statement based on the information in the plot above <em>understands</em> interactions, whether or not they know how to relate this concept to the mathematical formalisms used to implement this concepts in regression models.</p>
<p>In summary, if the answer to “what is the effect of X on Y” is “well, it depends on the values of Z”, you have an interaction in your data. When you have substantial interactions present in your data and you do not include these in your model, this can cause a problem for your model fit.</p>
<p>Before moving on from interactions, we need to discuss the relationshpi between interactions and the crossing of factors. The only thing you definitely need to be aware of is that you cannot estimate interactions of factors are not crossed. This is kind of obvious if you think about it. Interactions are conditional effects, and crossing means you observed all combinations. If you did not observe all combinations, you are not in a position to tell me about how effects vary for specific combinations.</p>
<div id="interactions-in-our-f0-data" class="section level3" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Interactions in our f0 data</h3>
<p>Above we made posterior predictions of our data using our model, with and without the inclusion of the speaker random effects. We can see that when random effects are included, prediction is quite good. This is not surprising since the speaker-specific intercept adjustments allow for each speaker’s mean f0 to be modeled effectively. However, we see that the predictions made by our model are substantially and systematically wrong in the absence of the speaker random intercepts.</p>
<p>It’s clear that the problem with our predictions in the right panel is that the lines are parallel. As we’ve just discussed, in the absence of interactions, interaction plots contain only parallel lines. Well, since our model (<code>model_both</code>) does not include interaction terms it cannot represent interactions, and so is only capable of producing predictions that result in parallel lines. This means it is not capable of representing the pattern in our data!</p>
<p>This is an important point worth considering. Your model is a little universe you made up, and it only includes the information you included in it. This ‘universe’ only contains parallel lines because we only included that capability. So, the fact that your model generates parallel lines does not in any way ‘prove’ that the lines are parallel, because they were bound to be so. In order to properly model the group differences, and to really understand whether interactions are present in the data, the model must be <em>built</em> in a way that allows it to represent the interactions in our data.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="comparing-many-groups-anova-and-interactions.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span> (<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">2</span>))</span>
<span id="cb19-2"><a href="comparing-many-groups-anova-and-interactions.html#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="comparing-many-groups-anova-and-interactions.html#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.interaction</span> (h95<span class="sc">$</span>gender, h95<span class="sc">$</span>adult, h95<span class="sc">$</span>f0, <span class="at">col=</span><span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">130</span>,<span class="dv">280</span>),<span class="at">lwd=</span><span class="dv">3</span>,</span>
<span id="cb19-4"><a href="comparing-many-groups-anova-and-interactions.html#cb19-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">type=</span><span class="st">&#39;b&#39;</span>,<span class="at">pch=</span><span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">17</span>),<span class="at">cex=</span><span class="fl">1.5</span>,<span class="at">main=</span><span class="st">&quot;Data&quot;</span>,<span class="at">legend =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-5"><a href="comparing-many-groups-anova-and-interactions.html#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="comparing-many-groups-anova-and-interactions.html#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.interaction</span> (h95<span class="sc">$</span>gender, h95<span class="sc">$</span>adult, y_pred[,<span class="dv">1</span>], <span class="at">col =</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>,<span class="at">lwd=</span><span class="dv">3</span>, <span class="at">type=</span><span class="st">&#39;b&#39;</span>,</span>
<span id="cb19-7"><a href="comparing-many-groups-anova-and-interactions.html#cb19-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">17</span>), <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">130</span>,<span class="dv">280</span>),</span>
<span id="cb19-8"><a href="comparing-many-groups-anova-and-interactions.html#cb19-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">main=</span><span class="st">&quot;Pred. with RE&quot;</span>,<span class="at">legend=</span><span class="cn">FALSE</span>)</span>
<span id="cb19-9"><a href="comparing-many-groups-anova-and-interactions.html#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="comparing-many-groups-anova-and-interactions.html#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.interaction</span> (h95<span class="sc">$</span>gender, h95<span class="sc">$</span>adult, y_pred_no_re[,<span class="dv">1</span>],<span class="at">col=</span><span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">lwd=</span><span class="dv">3</span>,</span>
<span id="cb19-11"><a href="comparing-many-groups-anova-and-interactions.html#cb19-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">type =</span> <span class="st">&#39;b&#39;</span>, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">17</span>), <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">130</span>,<span class="dv">280</span>),</span>
<span id="cb19-12"><a href="comparing-many-groups-anova-and-interactions.html#cb19-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">main=</span><span class="st">&quot;Pred. without RE&quot;</span>, <span class="at">leg.x=</span><span class="fl">1.8</span>,<span class="at">leg.y=</span><span class="dv">270</span>, <span class="at">xlim=</span><span class="fu">c</span>(.<span class="dv">95</span>,<span class="fl">2.3</span>))</span></code></pre></div>
<div class="figure"><span id="fig:interactionplot3"></span>
<img src="04_files/figure-html/interactionplot3-1.png" alt="Interaction plots showing comparing our f0 data to different posterior predictions, with and without RE (random effects)." width="768" />
<p class="caption">
Figure 4.7: Interaction plots showing comparing our f0 data to different posterior predictions, with and without RE (random effects).
</p>
</div>
</div>
</div>
<div id="investigating-interactions-with-a-model" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Investigating interactions with a model</h2>
<p>The model presented above (<code>model_both</code>) requires only a slight tweak to include a term representing the interaction in our data. There are two ways to include interactions in R model formulas, as shown below:</p>
<p><code>f0 ~ adult + gender + adult:gender + (1|speaker)</code>
 </p>
<p><code>f0 ~ adult * gender + (1|speaker)</code></p>
<p>The first way includes an explicit interaction term, <code>adult:gender</code>. The syntax for these is <code>X:Z</code> for an interaction between effects <code>X</code> and <code>Z</code>, <code>W:X:Z</code> for a three-way interaction, and so on. The second way uses <code>*</code> between our two predictors. This tells R to include those predictors, and the interactions between them. This can be much faster then specifying all interactions, but you lose control over which ones you include. For example the first formula implies the second, but cannot represent the third (since it omits the <code>X:W</code> interaction):</p>
<p><code>y ~ Z * X * W</code>
 </p>
<p><code>y ~ Z + X + W + Z:X + Z:W + X:W + Z:X:W</code>
 </p>
<p><code>y ~ Z + X + W + Z:X + X:W + Z:X:W</code></p>
<p>Our full model specification now includes an <em>interaction</em> term that can help explain variation that cannot be explained by the independent effects of adultness and gender. This interaction term helps us model the <em>conditional</em> effect of one predictor given the other.</p>
<p><span class="math display" id="eq:43">\[\begin{equation}
\begin{split}
\textrm{Likelihood:} \\
y_{[i]} \sim \mathcal{N}(\mu_{[i]},\sigma_{error}) \\
\mu_{[i]} = Intercept + adult_{\textrm{adult}_{[i]}} + gender_{\textrm{gender}_{[i]}}+ adult:gender + \alpha_{speaker_{[i]}} \\\\
\textrm{Priors:} \\
\alpha_{speaker} \sim \mathcal{N}(0,\sigma_{speaker}) \\ \\ 
Intercept \sim t(3, 200, 100) \\ 
adult_{[i]} \sim t(3, 0, 100) \\ 
gender_{[i]} \sim t(3, 0, 100) \\ 
adult:gender \sim t(3, 0, 100) \\ 
\sigma_{error} \sim t(3, 0, 100) \\
\sigma_{speaker} \sim t(3, 0, 100) \\ 
\end{split}
\tag{4.4}
\end{equation}\]</span></p>
<p>In plain English this says:</p>
<blockquote>
<p>“We expect the mean f0 produced by speakers from Michigan to vary according to a normal distribution with a trial-specific mean parameter. That mean varies based on whether the speaker is an adult/child and female/male, including the interaction of these two predictors. Random speaker-dependent variation in means was modelled as coming from a normal distribution with a mean of zero and a standard deviation estimated from the data”.</p>
</blockquote>
<div id="fitting-the-model-and-interpreting-the-results-1" class="section level3" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> Fitting the model and interpreting the results</h3>
<p>Below we fit the model which now includes an interaction term representing the changing effect of gender and adultness on average f0.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="comparing-many-groups-anova-and-interactions.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model yourself, or download pre-fit model from: </span></span>
<span id="cb20-2"><a href="comparing-many-groups-anova-and-interactions.html#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># github.com/santiagobarreda/stats-class/tree/master/models</span></span>
<span id="cb20-3"><a href="comparing-many-groups-anova-and-interactions.html#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># and load after placing in working directory</span></span>
<span id="cb20-4"><a href="comparing-many-groups-anova-and-interactions.html#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  model_interaction = readRDS (&#39;4_model_interaction.RDS&#39;)</span></span>
<span id="cb20-5"><a href="comparing-many-groups-anova-and-interactions.html#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="comparing-many-groups-anova-and-interactions.html#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span> (<span class="dv">1</span>)</span>
<span id="cb20-7"><a href="comparing-many-groups-anova-and-interactions.html#cb20-7" aria-hidden="true" tabindex="-1"></a>model_interaction <span class="ot">=</span>  </span>
<span id="cb20-8"><a href="comparing-many-groups-anova-and-interactions.html#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">brm</span> (f0 <span class="sc">~</span> adult <span class="sc">+</span> gender <span class="sc">+</span> adult<span class="sc">:</span>gender <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>speaker), <span class="at">data =</span> h95, </span>
<span id="cb20-9"><a href="comparing-many-groups-anova-and-interactions.html#cb20-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">cores =</span> <span class="dv">4</span>, <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">iter =</span> <span class="dv">11000</span>, <span class="at">thin =</span> <span class="dv">10</span>, </span>
<span id="cb20-10"><a href="comparing-many-groups-anova-and-interactions.html#cb20-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 200, 100)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;Intercept&quot;</span>),</span>
<span id="cb20-11"><a href="comparing-many-groups-anova-and-interactions.html#cb20-11" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 0, 100)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;b&quot;</span>),</span>
<span id="cb20-12"><a href="comparing-many-groups-anova-and-interactions.html#cb20-12" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">set_prior</span>(<span class="st">&quot;student_t(3, 0, 100)&quot;</span>, <span class="at">class =</span> <span class="st">&quot;sd&quot;</span>))) </span>
<span id="cb20-13"><a href="comparing-many-groups-anova-and-interactions.html#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="comparing-many-groups-anova-and-interactions.html#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="co">#  saveRDS (model_interaction, &#39;4_model_interaction.RDS&#39;)</span></span></code></pre></div>
<p>Remember that this line <code>set_prior("student_t(3, 0, 100)", class = "b")</code> sets the prior for all non-intercept ‘Population-Level’ predictors. This allows you to efficiently set priors for the adult, gender, and adult:gender predictors in your model in a single line, and becomes more and more useful as our models grow more complex.</p>
<p>A look at the model output above indicates that we have a large interaction term. In fact, our interaction is as large as the ‘main’ effect for gender! Our interaction basically says that sometimes being a male <em>and</em> being an adult results in a different f0 than can be predicted by maleness and adultness independently. In cases with large interactions we have to be very careful about interpreting the main effects. In other words, when the answer to a question is “it really depends”, you should be wary of making blanket statements. For example: how good can a speaker get at a second language in one year? The interaction between age and language learning is so large that it doesn’t even really make sense to answer this in a single way for all learners.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="comparing-many-groups-anova-and-interactions.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect fixed effects</span></span>
<span id="cb21-2"><a href="comparing-many-groups-anova-and-interactions.html#cb21-2" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">fixef</span> (model_interaction)</span></code></pre></div>
<pre><code>##                Estimate Est.Error    Q2.5   Q97.5
## Intercept       206.561    1.9131 202.783 210.275
## adult1          -30.669    1.9366 -34.465 -26.876
## gender1          22.892    1.9742  18.938  26.761
## adult1:gender1   21.719    1.9188  17.867  25.461</code></pre>
<p>We need to talk about why there is only a single interaction term. The reason for this is related to the same reason we can’t get estimates for all our group effects (i.e., linear dependence). The number of terms you can estimate is generally one fewer than the number of levels. For interaction terms, the number of parameters is equal to (number of levels of factor A - 1)x(number of levels of factor B - 1). Since each of our factors have two levels, we can only estimate one parameter, (2-1)x(2-1)=1.</p>
<p>The interaction term is just another element of your prediction equation (i.e., <span class="math inline">\(\mu + x_1+x_2...\)</span>) intended to help explain variation that can’t be predicted by the independent effects of the other predictors in the model. If there is no interaction in your data, then the value of the interaction terms will be zero and your model will look just as if you had not even included the interaction at all.</p>
<p>Recovering the predicted group means based on the coefficient values is straightforward, but a bit tedious: we must now either add or subtract the value of the interaction term (<code>adult1:gender1</code>) from each group. We can easily determine which to do for this model because the sign on the interaction term is the product of the signs on the relevant ‘main effects’ terms.</p>
<p>Before doing this however, we need to talk about what <code>adult1:gender1</code> means. This can be read aloud as “the effect of <code>adult1</code> given (conditional on) <code>gender1</code>”. If we wanted to find the simple effect for being an adult (<code>adult1</code>) given femaleness (<code>gender1</code>) we should add the main effect for <code>adult1</code> to the conditional effect for <code>adult1</code> given <code>gender1</code> as in <code>adult1 + adult1:gender1</code>. In other words, the expected pitch for adults that are female considers the effects for adultness, butl also the unique effect that adultness has for female speakers.</p>
<p>Importantly, <code>adult1:gender1</code> has the same value as <code>gender1:adult1</code> <em>would have if it existed</em>, but remember that is does not. This means that to find the simple effect of <code>gender1</code> given <code>adult1</code>, we also have to carry out an operation like <code>gender1 + adult1:gender1</code>. This is because, mathematically, this is equivalent to combining <code>gender1 + gender1:adult1</code> since <code>adult1:gender1</code> must equal <code>gender1:adult1</code>.</p>
<p>Figure <a href="comparing-many-groups-anova-and-interactions.html#fig:F4-interactionfig">4.8</a> presents an example of how our interaction plot can be built up from the components in our fixed effects above, and is very useful for understanding the geometry of main effects and interactions. In (a) we see that the intercept lifts up a line from 0 to the level of the overall mean f0 of 206 Hz. Then the effect for <code>adult1</code> (adult, -30 Hz) and <code>-adult1</code> (children, -(-30 Hz)) are added to this value, causing the separation between the lines indicating a ‘main effect’ for adultness. Notice that the lines are parallel, and also parallel to the x-axis. This is because we have not added either an effect for gender (indicated along the x axis), or an interaction between gender an adultness.</p>
<p>In (b) we see the addition of the gender effect: <code>gender1</code> (female, 22 Hz), and <code>-gender1</code> (male, -22 Hz). Notice that the effect is added to one point on the x axis and subtracted to the other point in the x axis. The result is a slope, and the same slope for both lines (i.e. no interaction yet). Panel (c) shows the addition of all of the effects shown in the top row, and the results of a model that includes both main effects both no interaction.</p>
<p>In (e) we add the gender interaction <code>adult1:gender1</code>, which was 21 Hz. Notice that the interaction effect has different when added to the same line, and also given a certain x axis position across lines. There is an obvious reason for why this <em>must</em> be the case, and why we only get one interaction term. Focus on the blue line in (e) and its average value, which represents the mean f0 produced by children in our sample. Whatever this average value, it is fixed for this data and <em>cannot</em> change. So, when we add <code>adult1:gender1</code> to the left end of the blue line, we must therefore subtract the same amount to the right end. Failure to do this would cause the blue line to <em>move up along the y axis</em>. This would mean the average f0 of children went up, which is not possible for this fixed set of data. Instead, the interactions can only make the blue line spin like a propeller around its fixed average value.</p>
<p>Although it is a little harder to visualize with the way the interaction plots below are set up, the same sort of constraints mean that the interaction terms in the same x-axis location must also equal but have opposite signs. As a result, we can get only a single independent interaction term when we combine two factors with two levels each!</p>
<div class="figure"><span id="fig:F4-interactionfig"></span>
<img src="images/interactionplot.png" alt="An interaction plot built up from its individual components." width="100%" />
<p class="caption">
Figure 4.8: An interaction plot built up from its individual components.
</p>
</div>
<p>Below, we use the <code>hypothesis</code> function provided in <code>brms</code> to reconstruct expected group means given the fixed effects above. The fifth hypothesis we are testing below is the simplest to understand, so we will start there. This hypothesis asks whether the sum of the <code>Intercept</code>, <code>adult1</code> (the effect for adults), <code>gender1</code> (the effect for femaleness), and <code>adult1:gender1</code> (the effect for adults given femaleness). Because of the specific combination of parameters values we combined, this results in the comparison of the ‘girl’ mean f0 to zero.</p>
<p>The second hypothesis we are testing below says <code>Intercept + -adult1 + -gender1 + adult1:gender1 = 0</code>. Since we have flipped the sign on <code>adult1</code> and <code>gender1</code>, these now correspond to the effects of the groups the were <em>not</em> estimated, ‘child’ and ‘male’. These coefficients <em>would</em> be called <code>adult2</code> and <code>gender2</code>. However, since we cannot estimate these and these do not exist in our model, we flip the sign on the coefficients that <em>are</em>present in our model. Since we combined the effects for male children, the second hypothesis below compares the mean f0 for ‘boys’ to 0.</p>
<p>If you look at the hypotheses below, you will see that these generate the predicted group means for our four speaker groups, and that the sign on the interaction terms always depends on the signs of the corresponding main effects terms. Furthermore, we can see that the inclusion of an interaction term allows our model to capture group averages more accurately than the model without intercepts.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="comparing-many-groups-anova-and-interactions.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># actual data means</span></span>
<span id="cb23-2"><a href="comparing-many-groups-anova-and-interactions.html#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span> (h95<span class="sc">$</span>f0, h95<span class="sc">$</span>group, mean)</span>
<span id="cb23-3"><a href="comparing-many-groups-anova-and-interactions.html#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="do">##      b      g      m      w </span></span>
<span id="cb23-4"><a href="comparing-many-groups-anova-and-interactions.html#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="do">## 236.07 238.35 131.22 220.40</span></span>
<span id="cb23-5"><a href="comparing-many-groups-anova-and-interactions.html#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># intercept, boys, girls, men, women</span></span>
<span id="cb23-6"><a href="comparing-many-groups-anova-and-interactions.html#cb23-6" aria-hidden="true" tabindex="-1"></a>means_pred_interaction <span class="ot">=</span> brms<span class="sc">::</span><span class="fu">hypothesis</span> (model_interaction, </span>
<span id="cb23-7"><a href="comparing-many-groups-anova-and-interactions.html#cb23-7" aria-hidden="true" tabindex="-1"></a>              <span class="fu">c</span>(<span class="st">&quot;Intercept = 0&quot;</span>,</span>
<span id="cb23-8"><a href="comparing-many-groups-anova-and-interactions.html#cb23-8" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;Intercept + -adult1 + -gender1 +  adult1:gender1 = 0&quot;</span>,</span>
<span id="cb23-9"><a href="comparing-many-groups-anova-and-interactions.html#cb23-9" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;Intercept + -adult1 +  gender1 + -adult1:gender1 = 0&quot;</span>,</span>
<span id="cb23-10"><a href="comparing-many-groups-anova-and-interactions.html#cb23-10" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;Intercept +  adult1 + -gender1 + -adult1:gender1 = 0&quot;</span>,</span>
<span id="cb23-11"><a href="comparing-many-groups-anova-and-interactions.html#cb23-11" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;Intercept +  adult1 +  gender1 +  adult1:gender1 = 0&quot;</span>))[[<span class="dv">1</span>]][,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb23-12"><a href="comparing-many-groups-anova-and-interactions.html#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co"># predictions with no interaction term</span></span>
<span id="cb23-13"><a href="comparing-many-groups-anova-and-interactions.html#cb23-13" aria-hidden="true" tabindex="-1"></a>means_pred</span>
<span id="cb23-14"><a href="comparing-many-groups-anova-and-interactions.html#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="do">##                         Hypothesis Estimate Est.Error CI.Lower CI.Upper</span></span>
<span id="cb23-15"><a href="comparing-many-groups-anova-and-interactions.html#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="do">## 1                  (Intercept) = 0   209.13    2.6607   203.95   214.38</span></span>
<span id="cb23-16"><a href="comparing-many-groups-anova-and-interactions.html#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="do">## 2 (Intercept+-adult1+-gender1) = 0   211.59    4.8403   202.16   221.42</span></span>
<span id="cb23-17"><a href="comparing-many-groups-anova-and-interactions.html#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="do">## 3  (Intercept+-adult1+gender1) = 0   272.57    5.3907   262.09   283.07</span></span>
<span id="cb23-18"><a href="comparing-many-groups-anova-and-interactions.html#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="do">## 4  (Intercept+adult1+-gender1) = 0   145.69    4.0108   137.79   153.42</span></span>
<span id="cb23-19"><a href="comparing-many-groups-anova-and-interactions.html#cb23-19" aria-hidden="true" tabindex="-1"></a><span class="do">## 5   (Intercept+adult1+gender1) = 0   206.68    3.8145   199.20   214.21</span></span>
<span id="cb23-20"><a href="comparing-many-groups-anova-and-interactions.html#cb23-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-21"><a href="comparing-many-groups-anova-and-interactions.html#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="co"># predictions with interaction term</span></span>
<span id="cb23-22"><a href="comparing-many-groups-anova-and-interactions.html#cb23-22" aria-hidden="true" tabindex="-1"></a>means_pred_interaction</span>
<span id="cb23-23"><a href="comparing-many-groups-anova-and-interactions.html#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="do">##                                        Hypothesis Estimate Est.Error CI.Lower</span></span>
<span id="cb23-24"><a href="comparing-many-groups-anova-and-interactions.html#cb23-24" aria-hidden="true" tabindex="-1"></a><span class="do">## 1                                 (Intercept) = 0   206.56    1.9131   202.78</span></span>
<span id="cb23-25"><a href="comparing-many-groups-anova-and-interactions.html#cb23-25" aria-hidden="true" tabindex="-1"></a><span class="do">## 2 (Intercept+-adult1+-gender1+adult1:gender1) = 0   236.06    4.1908   227.91</span></span>
<span id="cb23-26"><a href="comparing-many-groups-anova-and-interactions.html#cb23-26" aria-hidden="true" tabindex="-1"></a><span class="do">## 3 (Intercept+-adult1+gender1+-adult1:gender1) = 0   238.40    4.8091   229.01</span></span>
<span id="cb23-27"><a href="comparing-many-groups-anova-and-interactions.html#cb23-27" aria-hidden="true" tabindex="-1"></a><span class="do">## 4 (Intercept+adult1+-gender1+-adult1:gender1) = 0   131.28    3.1841   124.90</span></span>
<span id="cb23-28"><a href="comparing-many-groups-anova-and-interactions.html#cb23-28" aria-hidden="true" tabindex="-1"></a><span class="do">## 5   (Intercept+adult1+gender1+adult1:gender1) = 0   220.50    3.0216   214.48</span></span>
<span id="cb23-29"><a href="comparing-many-groups-anova-and-interactions.html#cb23-29" aria-hidden="true" tabindex="-1"></a><span class="do">##   CI.Upper</span></span>
<span id="cb23-30"><a href="comparing-many-groups-anova-and-interactions.html#cb23-30" aria-hidden="true" tabindex="-1"></a><span class="do">## 1   210.27</span></span>
<span id="cb23-31"><a href="comparing-many-groups-anova-and-interactions.html#cb23-31" aria-hidden="true" tabindex="-1"></a><span class="do">## 2   244.45</span></span>
<span id="cb23-32"><a href="comparing-many-groups-anova-and-interactions.html#cb23-32" aria-hidden="true" tabindex="-1"></a><span class="do">## 3   247.64</span></span>
<span id="cb23-33"><a href="comparing-many-groups-anova-and-interactions.html#cb23-33" aria-hidden="true" tabindex="-1"></a><span class="do">## 4   137.39</span></span>
<span id="cb23-34"><a href="comparing-many-groups-anova-and-interactions.html#cb23-34" aria-hidden="true" tabindex="-1"></a><span class="do">## 5   226.44</span></span></code></pre></div>
<p>Below I print the estimates of the ‘fixed’ effects in the model so we can focus on those. If you fit a model like this and are having trouble interpreting it, I would really encourage you to write down an interpretation using pen and paper, focusing on the decomposition of values provided by the regression model.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="comparing-many-groups-anova-and-interactions.html#cb24-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">fixef</span> (model_interaction)</span>
<span id="cb24-2"><a href="comparing-many-groups-anova-and-interactions.html#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="do">##                Estimate Est.Error    Q2.5   Q97.5</span></span>
<span id="cb24-3"><a href="comparing-many-groups-anova-and-interactions.html#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Intercept       206.561    1.9131 202.783 210.275</span></span>
<span id="cb24-4"><a href="comparing-many-groups-anova-and-interactions.html#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="do">## adult1          -30.669    1.9366 -34.465 -26.876</span></span>
<span id="cb24-5"><a href="comparing-many-groups-anova-and-interactions.html#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="do">## gender1          22.892    1.9742  18.938  26.761</span></span>
<span id="cb24-6"><a href="comparing-many-groups-anova-and-interactions.html#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="do">## adult1:gender1   21.719    1.9188  17.867  25.461</span></span></code></pre></div>
<p>For example, the average f0 is 206. The gender difference is 46 Hz (23 * 2) between groups, and there is a gender-based 23 Hz deviation from the mean between groups. This means that, overall, the male and female averages are about 183 and 229 Hz (206 ± 23).</p>
<p>However, the <code>adult1:gender1</code> interaction is 22 Hz. This means that when the speaker was an adult (<code>adult1</code>), the gender difference was nearly doubled. We know this because the effect for <code>gender1</code> is 22.8, and the effect for <code>gender1</code> <strong>given</strong> <code>adult1</code> (<code>adult1:gender1</code>, which is the same thing as <code>gender1:adult1</code>) is 21.7 Hz higher than that. So, the total effect for f0 across adults is about 22.8 + 21.7 = 44.5, suggesting a difference in f0 between the groups of 89 Hz (44.5 * 2).</p>
<p>I am going to basically restate what I just said because it is very important. The effect for <code>gender</code> is 22.8, and the effect for <code>gender1:adult1</code> is further 21.7 Hz. As a result, the cumulative effect for gender1 (female) given adult1 (adult) is <code>gender1 + gender1:adult1 = 44.5</code>.</p>
<p>In contrast, the fact that <code>adult1:gender1 = 21.7</code> indicates that <code>adult2:gender1 = -21.7</code>. This is because since <code>adult1:gender1</code> represents the effect of <code>gender1</code> <em>given</em> <code>adult1</code>, the effect given <code>adult2</code> must be opposite in sign (because of sum coding). So, we can say that although the effect for gender is 22.9 overall, given that the speaker is a child (<code>adult2</code>), this effect is 21.7 Hz lower than the ‘main effect’ estimate. So, for children we expect an f0 effect of 22.9 - 21.7 = 1.2, suggesting a group difference of 2.2 Hz. In other words, the effect of gender is basically zero given that the speakers are children.</p>
<p>We can consider the effects the other way. The marginal effect for <code>adult1</code> is -30, meaning that when speakers are adults, their f0 is 30 Hz lower than the overall average. However, <code>adult1:gender1 = 21.7</code>, meaning that <em>if</em> the speaker is female (<code>gender1</code>), then the expected effect of adultness is reduced (-30 + 21.7 = -8.3) so that the expected group difference is only 17 Hz. On the other hand, when the speaker is a male (<code>gender2</code>) then the interaction term should be flipped in sign (<code>adult1:gender2 =  -21.7</code>). This means that the effect of adultness, conditional on the speaker being male is nearly doubled (-30 + -21.7 = -51.7).</p>
<p>When considered in this way all these coefficients are just telling us what we already knew from looking at the interaction plot: f0 varies substantially based on gender for adults but not for children. Or: f0 varies substantially as a function of adultness for males but much less for females.</p>
</div>
<div id="assessing-model-fit" class="section level3" number="4.6.2">
<h3><span class="header-section-number">4.6.2</span> Assessing model fit</h3>
<p>We can asses model fit for the model including interaction terms by making more posterior predictions with our new model.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="comparing-many-groups-anova-and-interactions.html#cb25-1" aria-hidden="true" tabindex="-1"></a>y_pred_int <span class="ot">=</span> <span class="fu">predict</span> (model_interaction)</span>
<span id="cb25-2"><a href="comparing-many-groups-anova-and-interactions.html#cb25-2" aria-hidden="true" tabindex="-1"></a>y_pred_no_re_int <span class="ot">=</span> <span class="fu">predict</span> (model_interaction, <span class="at">re_formula =</span> <span class="cn">NA</span>)</span></code></pre></div>
<p>We can make more interaction plots using our data and our posterior predictions. Below I compare our data, the predictions of our original model, and the predictions of our model that includes interactions (both models with no random effects). Whereas the model with no interactions enforced parallelism on the effects, our new model is able to capture the conditional nature of gender given adultness in our data.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="comparing-many-groups-anova-and-interactions.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span> (<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">2</span>))</span>
<span id="cb26-2"><a href="comparing-many-groups-anova-and-interactions.html#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="comparing-many-groups-anova-and-interactions.html#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.interaction</span> (h95<span class="sc">$</span>gender, h95<span class="sc">$</span>adult, h95<span class="sc">$</span>f0, <span class="at">col=</span><span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">130</span>,<span class="dv">280</span>),<span class="at">lwd=</span><span class="dv">3</span>,</span>
<span id="cb26-4"><a href="comparing-many-groups-anova-and-interactions.html#cb26-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">type=</span><span class="st">&#39;b&#39;</span>,<span class="at">pch=</span><span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">17</span>),<span class="at">cex=</span><span class="fl">1.5</span>,<span class="at">main=</span><span class="st">&quot;Data&quot;</span>,<span class="at">legend =</span> <span class="cn">FALSE</span>, <span class="at">ylab =</span> <span class="st">&#39;f0 (Hz)&#39;</span>)</span>
<span id="cb26-5"><a href="comparing-many-groups-anova-and-interactions.html#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="comparing-many-groups-anova-and-interactions.html#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.interaction</span> (h95<span class="sc">$</span>gender, h95<span class="sc">$</span>adult, y_pred_no_re[,<span class="dv">1</span>],<span class="at">col=</span><span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">lwd=</span><span class="dv">3</span>,</span>
<span id="cb26-7"><a href="comparing-many-groups-anova-and-interactions.html#cb26-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">type =</span> <span class="st">&#39;b&#39;</span>, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">17</span>), <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">130</span>,<span class="dv">280</span>),</span>
<span id="cb26-8"><a href="comparing-many-groups-anova-and-interactions.html#cb26-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">main=</span><span class="st">&quot;No Int. no RE&quot;</span>, <span class="at">legend =</span> <span class="cn">FALSE</span>, <span class="at">ylab =</span> <span class="st">&#39;f0 (Hz)&#39;</span>)</span>
<span id="cb26-9"><a href="comparing-many-groups-anova-and-interactions.html#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="comparing-many-groups-anova-and-interactions.html#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.interaction</span> (h95<span class="sc">$</span>gender, h95<span class="sc">$</span>adult, y_pred_no_re_int[,<span class="dv">1</span>],<span class="at">col=</span><span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">lwd=</span><span class="dv">3</span>,</span>
<span id="cb26-11"><a href="comparing-many-groups-anova-and-interactions.html#cb26-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">type =</span> <span class="st">&#39;b&#39;</span>, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">17</span>), <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">130</span>,<span class="dv">280</span>),</span>
<span id="cb26-12"><a href="comparing-many-groups-anova-and-interactions.html#cb26-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">main=</span><span class="st">&quot;With Int. no RE&quot;</span>, <span class="at">leg.x=</span><span class="fl">1.8</span>,<span class="at">leg.y=</span><span class="dv">270</span>, <span class="at">xlim=</span><span class="fu">c</span>(.<span class="dv">95</span>,<span class="fl">2.3</span>), <span class="at">ylab =</span> <span class="st">&#39;f0 (Hz)&#39;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:interactionplot2"></span>
<img src="04_files/figure-html/interactionplot2-1.png" alt="Interaction plots showing comparing our f0 data to posterior predictions, with and without interaction terms (neither contains Random Effects)." width="768" />
<p class="caption">
Figure 4.9: Interaction plots showing comparing our f0 data to posterior predictions, with and without interaction terms (neither contains Random Effects).
</p>
</div>
<p>For the first time, we have a model that really does a reasonably-good job of representing the information in our data. The model can capture the gender-dependent nature of age-based f0 differences, and separately estimates between group variation and between group variation.</p>
</div>
<div id="making-plots" class="section level3" number="4.6.3">
<h3><span class="header-section-number">4.6.3</span> Making plots</h3>
<p>There are many ways to make ‘nice’ graphics using brms models. There are many excellent resources for how to make slick graphics using packages like <code>ggplot2</code> and <code>bayesplot</code>. In general these packages make figures that are nice but sometimes too ‘fancy’ for many purposes where simple black and white graphics are needed. As a result, I’m going to focus on making simple line plots (like those common in journal articles) using base R graphics.<br />
The standard information provided in the output of <code>brm</code> model summaries can be used to make plots. These summaries always contain (among other things) these four columns in the same order: the mean estimate, the standard deviation, and the lower and upper credible intervals. I wrote a small function called <code>brmplot</code> that will help draw effects plots easily using these summaries. The <code>brmplot</code> function takes in a matrix containing these columns and makes plots showing the means and credible intervals of different effects, assuming that each row is an effect.</p>
<p>Below I get a summary of the fixed effects. I make plots of these effects in two orientations. In each one I omit the Intercept estimate as the magnitude of this is so different that it cannot easily be included on the plot. There is nothing special about these plots, but they are extremely effective at quickly communicating model information.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="comparing-many-groups-anova-and-interactions.html#cb27-1" aria-hidden="true" tabindex="-1"></a>fixef_interaction <span class="ot">=</span> brms<span class="sc">::</span><span class="fu">fixef</span> (model_interaction)</span>
<span id="cb27-2"><a href="comparing-many-groups-anova-and-interactions.html#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="comparing-many-groups-anova-and-interactions.html#cb27-3" aria-hidden="true" tabindex="-1"></a>fixef_interaction</span>
<span id="cb27-4"><a href="comparing-many-groups-anova-and-interactions.html#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="do">##                 Estimate Est.Error      Q2.5     Q97.5</span></span>
<span id="cb27-5"><a href="comparing-many-groups-anova-and-interactions.html#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Intercept      206.56112  1.913081 202.78344 210.27475</span></span>
<span id="cb27-6"><a href="comparing-many-groups-anova-and-interactions.html#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="do">## adult1         -30.66934  1.936608 -34.46529 -26.87641</span></span>
<span id="cb27-7"><a href="comparing-many-groups-anova-and-interactions.html#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="do">## gender1         22.89211  1.974245  18.93775  26.76101</span></span>
<span id="cb27-8"><a href="comparing-many-groups-anova-and-interactions.html#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="do">## adult1:gender1  21.71878  1.918765  17.86664  25.46130</span></span></code></pre></div>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="comparing-many-groups-anova-and-interactions.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span> (<span class="at">mfrow =</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">8</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb28-2"><a href="comparing-many-groups-anova-and-interactions.html#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">brmplot</span> (fixef_interaction[<span class="sc">-</span><span class="dv">1</span>,]) ; <span class="fu">abline</span> (<span class="at">h =</span> <span class="dv">0</span>,<span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb28-3"><a href="comparing-many-groups-anova-and-interactions.html#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span> (<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">8</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb28-4"><a href="comparing-many-groups-anova-and-interactions.html#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">brmplot</span> (fixef_interaction[<span class="sc">-</span><span class="dv">1</span>,], <span class="at">horizontal =</span> <span class="cn">FALSE</span>) ; <span class="fu">abline</span> (<span class="at">v=</span><span class="dv">0</span>,<span class="at">lty=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="figure"><span id="fig:brmsplot"></span>
<img src="04_files/figure-html/brmsplot-1.png" alt="Horizontal and vertical plots of our fixed effects. Points indicate posterior means and lines indicate span of 95% credible intervals of the posterior distribution of the parameter." width="768" />
<p class="caption">
Figure 4.10: Horizontal and vertical plots of our fixed effects. Points indicate posterior means and lines indicate span of 95% credible intervals of the posterior distribution of the parameter.
</p>
</div>
<p>Although these plots help to effectively communicate information about your model parameters, representations of the data such as the interaction plots above are also crucial to help the reader understand the patterns in your data.</p>
</div>
</div>
<div id="frequentist-corner-2" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Frequentist corner</h2>
<div id="bayesian-multilevel-modesl-vs.-lmer-2" class="section level3" number="4.7.1">
<h3><span class="header-section-number">4.7.1</span> Bayesian multilevel modesl vs. lmer</h3>
<p>This is going to be a short one! The main shortcoming when it comes to <code>lmer</code> and fitting ANOVA-type models, is that there is no easy way to compare group effects within the model. For example, we can fit the model below which encodes the difference between each group mean and the overall mean.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="comparing-many-groups-anova-and-interactions.html#cb29-1" aria-hidden="true" tabindex="-1"></a>lmer_four_groups <span class="ot">=</span> lme4<span class="sc">::</span><span class="fu">lmer</span> (f0 <span class="sc">~</span> group <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>speaker), <span class="at">data =</span> h95)</span>
<span id="cb29-2"><a href="comparing-many-groups-anova-and-interactions.html#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (lmer_four_groups)</span>
<span id="cb29-3"><a href="comparing-many-groups-anova-and-interactions.html#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Linear mixed model fit by REML [&#39;lmerMod&#39;]</span></span>
<span id="cb29-4"><a href="comparing-many-groups-anova-and-interactions.html#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Formula: f0 ~ group + (1 | speaker)</span></span>
<span id="cb29-5"><a href="comparing-many-groups-anova-and-interactions.html#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="do">##    Data: h95</span></span>
<span id="cb29-6"><a href="comparing-many-groups-anova-and-interactions.html#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb29-7"><a href="comparing-many-groups-anova-and-interactions.html#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="do">## REML criterion at convergence: 13468</span></span>
<span id="cb29-8"><a href="comparing-many-groups-anova-and-interactions.html#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb29-9"><a href="comparing-many-groups-anova-and-interactions.html#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Scaled residuals: </span></span>
<span id="cb29-10"><a href="comparing-many-groups-anova-and-interactions.html#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="do">##    Min     1Q Median     3Q    Max </span></span>
<span id="cb29-11"><a href="comparing-many-groups-anova-and-interactions.html#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="do">## -4.644 -0.561 -0.086  0.470  4.808 </span></span>
<span id="cb29-12"><a href="comparing-many-groups-anova-and-interactions.html#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb29-13"><a href="comparing-many-groups-anova-and-interactions.html#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="do">## Random effects:</span></span>
<span id="cb29-14"><a href="comparing-many-groups-anova-and-interactions.html#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="do">##  Groups   Name        Variance Std.Dev.</span></span>
<span id="cb29-15"><a href="comparing-many-groups-anova-and-interactions.html#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="do">##  speaker  (Intercept) 430      20.7    </span></span>
<span id="cb29-16"><a href="comparing-many-groups-anova-and-interactions.html#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="do">##  Residual             141      11.9    </span></span>
<span id="cb29-17"><a href="comparing-many-groups-anova-and-interactions.html#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="do">## Number of obs: 1668, groups:  speaker, 139</span></span>
<span id="cb29-18"><a href="comparing-many-groups-anova-and-interactions.html#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb29-19"><a href="comparing-many-groups-anova-and-interactions.html#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="do">## Fixed effects:</span></span>
<span id="cb29-20"><a href="comparing-many-groups-anova-and-interactions.html#cb29-20" aria-hidden="true" tabindex="-1"></a><span class="do">##             Estimate Std. Error t value</span></span>
<span id="cb29-21"><a href="comparing-many-groups-anova-and-interactions.html#cb29-21" aria-hidden="true" tabindex="-1"></a><span class="do">## (Intercept)   206.51       1.91  107.93</span></span>
<span id="cb29-22"><a href="comparing-many-groups-anova-and-interactions.html#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="do">## group1         29.56       3.44    8.59</span></span>
<span id="cb29-23"><a href="comparing-many-groups-anova-and-interactions.html#cb29-23" aria-hidden="true" tabindex="-1"></a><span class="do">## group2         31.84       3.91    8.15</span></span>
<span id="cb29-24"><a href="comparing-many-groups-anova-and-interactions.html#cb29-24" aria-hidden="true" tabindex="-1"></a><span class="do">## group3        -75.29       2.93  -25.73</span></span>
<span id="cb29-25"><a href="comparing-many-groups-anova-and-interactions.html#cb29-25" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb29-26"><a href="comparing-many-groups-anova-and-interactions.html#cb29-26" aria-hidden="true" tabindex="-1"></a><span class="do">## Correlation of Fixed Effects:</span></span>
<span id="cb29-27"><a href="comparing-many-groups-anova-and-interactions.html#cb29-27" aria-hidden="true" tabindex="-1"></a><span class="do">##        (Intr) group1 group2</span></span>
<span id="cb29-28"><a href="comparing-many-groups-anova-and-interactions.html#cb29-28" aria-hidden="true" tabindex="-1"></a><span class="do">## group1  0.065              </span></span>
<span id="cb29-29"><a href="comparing-many-groups-anova-and-interactions.html#cb29-29" aria-hidden="true" tabindex="-1"></a><span class="do">## group2  0.287 -0.464       </span></span>
<span id="cb29-30"><a href="comparing-many-groups-anova-and-interactions.html#cb29-30" aria-hidden="true" tabindex="-1"></a><span class="do">## group3 -0.216 -0.286 -0.402</span></span></code></pre></div>
<p>The results provided by <code>lmer</code> are very similar to those provided by <code>brm</code>:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="comparing-many-groups-anova-and-interactions.html#cb30-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">fixef</span> (model_four_groups)</span>
<span id="cb30-2"><a href="comparing-many-groups-anova-and-interactions.html#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="do">##           Estimate Est.Error    Q2.5   Q97.5</span></span>
<span id="cb30-3"><a href="comparing-many-groups-anova-and-interactions.html#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Intercept  206.486    1.9287 202.670 210.213</span></span>
<span id="cb30-4"><a href="comparing-many-groups-anova-and-interactions.html#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="do">## group1      29.532    3.5239  22.783  36.645</span></span>
<span id="cb30-5"><a href="comparing-many-groups-anova-and-interactions.html#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="do">## group2      31.878    3.9764  24.351  39.684</span></span>
<span id="cb30-6"><a href="comparing-many-groups-anova-and-interactions.html#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="do">## group3     -75.176    2.9037 -80.889 -69.620</span></span></code></pre></div>
<p>Group 1 (boys) and group 2 (girls) have very similar effects to each other. Are they different? Using our <code>brm</code> model this can be answered easily, as shown above (and reproduced below):</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="comparing-many-groups-anova-and-interactions.html#cb31-1" aria-hidden="true" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">hypothesis</span> (model_four_groups, <span class="st">&quot;group2 - group1 = 0&quot;</span>)[[<span class="dv">1</span>]][,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb31-2"><a href="comparing-many-groups-anova-and-interactions.html#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="do">##            Hypothesis Estimate Est.Error CI.Lower CI.Upper</span></span>
<span id="cb31-3"><a href="comparing-many-groups-anova-and-interactions.html#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="do">## 1 (group2-group1) = 0   2.3459    6.4375  -10.282   15.038</span></span></code></pre></div>
<p>Unfortunately, there is no way to answer this question given the information presented in the <code>lmer</code> model above. This is because the effects are only being estimates as differences to the mean, and not to group 1 or group 2. If we <em>did</em> want to investigate this difference specifically, we would need to refit the model using a different coding scheme. For example, if we used treatment coding group 1 (boys) would be the intercept, and the group effects would represent differences to this. We fit a model like this below:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="comparing-many-groups-anova-and-interactions.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span> (<span class="at">contrasts =</span> <span class="fu">rep</span>(<span class="st">&quot;contr.treatment&quot;</span>,<span class="dv">2</span>))</span>
<span id="cb32-2"><a href="comparing-many-groups-anova-and-interactions.html#cb32-2" aria-hidden="true" tabindex="-1"></a>lmer_four_groups_treatment <span class="ot">=</span> lme4<span class="sc">::</span><span class="fu">lmer</span> (f0 <span class="sc">~</span> group <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>speaker), <span class="at">data =</span> h95)</span>
<span id="cb32-3"><a href="comparing-many-groups-anova-and-interactions.html#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (lmer_four_groups_treatment)</span>
<span id="cb32-4"><a href="comparing-many-groups-anova-and-interactions.html#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Linear mixed model fit by REML [&#39;lmerMod&#39;]</span></span>
<span id="cb32-5"><a href="comparing-many-groups-anova-and-interactions.html#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Formula: f0 ~ group + (1 | speaker)</span></span>
<span id="cb32-6"><a href="comparing-many-groups-anova-and-interactions.html#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="do">##    Data: h95</span></span>
<span id="cb32-7"><a href="comparing-many-groups-anova-and-interactions.html#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb32-8"><a href="comparing-many-groups-anova-and-interactions.html#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="do">## REML criterion at convergence: 13466</span></span>
<span id="cb32-9"><a href="comparing-many-groups-anova-and-interactions.html#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb32-10"><a href="comparing-many-groups-anova-and-interactions.html#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="do">## Scaled residuals: </span></span>
<span id="cb32-11"><a href="comparing-many-groups-anova-and-interactions.html#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="do">##    Min     1Q Median     3Q    Max </span></span>
<span id="cb32-12"><a href="comparing-many-groups-anova-and-interactions.html#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="do">## -4.644 -0.561 -0.086  0.470  4.808 </span></span>
<span id="cb32-13"><a href="comparing-many-groups-anova-and-interactions.html#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb32-14"><a href="comparing-many-groups-anova-and-interactions.html#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="do">## Random effects:</span></span>
<span id="cb32-15"><a href="comparing-many-groups-anova-and-interactions.html#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="do">##  Groups   Name        Variance Std.Dev.</span></span>
<span id="cb32-16"><a href="comparing-many-groups-anova-and-interactions.html#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="do">##  speaker  (Intercept) 430      20.7    </span></span>
<span id="cb32-17"><a href="comparing-many-groups-anova-and-interactions.html#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="do">##  Residual             141      11.9    </span></span>
<span id="cb32-18"><a href="comparing-many-groups-anova-and-interactions.html#cb32-18" aria-hidden="true" tabindex="-1"></a><span class="do">## Number of obs: 1668, groups:  speaker, 139</span></span>
<span id="cb32-19"><a href="comparing-many-groups-anova-and-interactions.html#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb32-20"><a href="comparing-many-groups-anova-and-interactions.html#cb32-20" aria-hidden="true" tabindex="-1"></a><span class="do">## Fixed effects:</span></span>
<span id="cb32-21"><a href="comparing-many-groups-anova-and-interactions.html#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="do">##             Estimate Std. Error t value</span></span>
<span id="cb32-22"><a href="comparing-many-groups-anova-and-interactions.html#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="do">## (Intercept)   236.07       4.04   58.39</span></span>
<span id="cb32-23"><a href="comparing-many-groups-anova-and-interactions.html#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="do">## groupg          2.28       6.29    0.36</span></span>
<span id="cb32-24"><a href="comparing-many-groups-anova-and-interactions.html#cb32-24" aria-hidden="true" tabindex="-1"></a><span class="do">## groupm       -104.86       5.11  -20.50</span></span>
<span id="cb32-25"><a href="comparing-many-groups-anova-and-interactions.html#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="do">## groupw        -15.67       5.05   -3.10</span></span>
<span id="cb32-26"><a href="comparing-many-groups-anova-and-interactions.html#cb32-26" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb32-27"><a href="comparing-many-groups-anova-and-interactions.html#cb32-27" aria-hidden="true" tabindex="-1"></a><span class="do">## Correlation of Fixed Effects:</span></span>
<span id="cb32-28"><a href="comparing-many-groups-anova-and-interactions.html#cb32-28" aria-hidden="true" tabindex="-1"></a><span class="do">##        (Intr) groupg groupm</span></span>
<span id="cb32-29"><a href="comparing-many-groups-anova-and-interactions.html#cb32-29" aria-hidden="true" tabindex="-1"></a><span class="do">## groupg -0.643              </span></span>
<span id="cb32-30"><a href="comparing-many-groups-anova-and-interactions.html#cb32-30" aria-hidden="true" tabindex="-1"></a><span class="do">## groupm -0.791  0.508       </span></span>
<span id="cb32-31"><a href="comparing-many-groups-anova-and-interactions.html#cb32-31" aria-hidden="true" tabindex="-1"></a><span class="do">## groupw -0.800  0.514  0.632</span></span></code></pre></div>
<p>Notice that our group 2 predictor (<code>group</code>) is now equal to 2.3, the Hz difference between boys and girls. The value of the standard error (<code>Std. Error</code>) is 6.3, representing the uncertainty in the estimate. These values correspond closely to the estimates of 2.3 and 6.4 respectively provided by our Bayesian model using the hypothesis function above.</p>
<p>Obviously this situation is not ideal if you plan to compare many groups. In contrast, with our <code>brm</code> model we can easily compare any of the four groups using the method outlined above, without ever having to re-fit the model.</p>
</div>
</div>
<div id="exercises-3" class="section level2" number="4.8">
<h2><span class="header-section-number">4.8</span> Exercises</h2>

</div>
</div>
<!-- Default Statcounter code for statsbook
https://santiagobarreda.github.io/stats-class/ -->
<script type="text/javascript">
var sc_project=12454226; 
var sc_invisible=1; 
var sc_security="a1959418"; 
</script>
<script type="text/javascript"
src="https://www.statcounter.com/counter/counter.js"
async></script>
<noscript><div class="statcounter"><a title="Web Analytics"
href="https://statcounter.com/" target="_blank"><img
class="statcounter"
src="https://c.statcounter.com/12454226/0/a1959418/1/"
alt="Web Analytics"></a></div></noscript>
<!-- End of Statcounter Code -->
            </section>

          </div>
        </div>
      </div>
<a href="comparing-two-groups-of-observations-factors-and-contrasts.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="continuous-predictors-and-their-interactions-with-factors.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
