--- 
title: "An Quick Introduction to Multilevel Bayesian Models"
author: "Santiago Bareda"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
url: 'http\://santiagobarreda.com'
description: "An Quick Introduction to Multilevel Bayesian Models"
---

# Introduction {-}

This book will focus on a conceptual introduction to multilevel Bayesian models. I am going to talk about math as possible and as a result I am going to avoid details, proofs, etc. I am just going to try to convey some of the more important and useful concepts necessary to begin to understand these models and to use them in your own work. 

I am purposely skipping a lot of details and being slightly hazy, or potentially even slightly inaccurate, in the interests of keeping things simple. The thing is, there are a million resources for learning abut these topics in a rigorous manner. What I am trying to provide here is a quick conceptual explanation that will allow you to understand common research designs, their associated statistical models, and how these can be implemented in a Bayesian multilevel model. 